# GCN Corpus Decision Dossier

This notebook shows the extracted rows that motivated the thirteen corpus decisions recorded in notebook A. It reads only the extracted interim Parquet tables and their manifest, performs no extraction or normalization, and writes no data product; notebook C measures what applying the decisions changes.

In [1]:
import inspect
import json
import re
from collections import Counter
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq
from IPython.display import display

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
repo_root = Path.cwd().resolve()
while not (repo_root / 'data' / 'interim' / 'gcn_corpus').is_dir():
    if repo_root.parent == repo_root:
        raise FileNotFoundError('data/interim/gcn_corpus was not found')
    repo_root = repo_root.parent
corpus_dir = repo_root / 'data' / 'interim' / 'gcn_corpus'
circulars = pq.read_table(corpus_dir / 'circulars.parquet').to_pandas()
evidence = pq.read_table(corpus_dir / 'evidence_spans.parquet').to_pandas()
photometry = pq.read_table(corpus_dir / 'photometry_spans.parquet').to_pandas()
manifest = json.loads((corpus_dir / 'manifest.json').read_text(encoding='utf-8'))
expected = {'circulars': (12012, 11), 'evidence': (63277, 20), 'photometry': (37795, 30)}
frames = {'circulars': circulars, 'evidence': evidence, 'photometry': photometry}
controls = pd.DataFrame([[name, frame.shape, expected[name], frame.shape == expected[name]] for name, frame in frames.items()], columns=['table', 'observed', 'expected', 'PASS'])
display(controls)
if not controls['PASS'].all():
    raise RuntimeError('An extracted-table shape control failed')
def populated(value):
    return not pd.isna(value) and not (isinstance(value, str) and value == '')
annotations = pd.concat([evidence.assign(layer='evidence'), photometry.assign(layer='photometry')], ignore_index=True)

        table     observed     expected  PASS
0   circulars  (12012, 11)  (12012, 11)  True
1    evidence  (63277, 20)  (63277, 20)  True
2  photometry  (37795, 30)  (37795, 30)  True

## Decision 1 — what identifies an annotation

**Observed.** The extracted photometry contains 407 offset ranges with multiple annotations: 330 groups of two, 67 of three, and 10 of four. **Why it matters.** Removing `span_index` would collapse 494 distinct annotations that share their character range. **Decided.** An annotation is keyed by `(circular_id, layer, span_start, span_end, span_index)`. **Scope.** The ambiguity reaches 901 annotations across 407 photometry offset ranges.

In [2]:
offset_sizes = photometry.groupby(['circular_id', 'span_start', 'span_end']).size()
multi_sizes = offset_sizes[offset_sizes > 1]
distribution = multi_sizes.value_counts().sort_index()
summary = pd.DataFrame({
    'record_type': 'group_size_distribution',
    'group_size': distribution.index,
    'groups': distribution.values,
})
summary['annotations_in_groups'] = summary['group_size'] * summary['groups']
summary['annotations_collapsed_without_span_index'] = (summary['group_size'] - 1) * summary['groups']
summary = pd.concat([summary, pd.DataFrame([{
    'record_type': 'total',
    'groups': len(multi_sizes),
    'annotations_in_groups': int(multi_sizes.sum()),
    'annotations_collapsed_without_span_index': int((multi_sizes - 1).sum()),
}])], ignore_index=True)
key = sorted(multi_sizes[multi_sizes == 4].index)[0]
example = photometry[(photometry['circular_id'] == key[0]) & (photometry['span_start'] == key[1]) & (photometry['span_end'] == key[2])].copy()
differing = [column for column in example.columns if example[column].nunique(dropna=False) > 1]
example.insert(0, 'record_type', 'size_four_annotation')
example.insert(1, 'differing_fields', ', '.join(differing))
decision_1_evidence = pd.concat([summary, example], ignore_index=True, sort=False)
display(decision_1_evidence)

,record_type,group_size,groups,annotations_in_groups,annotations_collapsed_without_span_index,differing_fields,circular_id,span_index,text_sha256,span_start,span_end,text,measurement_type,target,certainty,magnitude_or_limit,magnitude_error,limit_sigma,unit,photometric_band,photometric_system,obs_time_raw,obs_time_type,obs_time_reference,exposure_time_raw,instrument,instrument_provenance,comment,provenance_inherited,extractor_id,extractor_version,method,rule_id,confidence,needs_review,schema_version
0,group_size_distribution,2.0,330.0,660.0,330.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,group_size_distribution,3.0,67.0,201.0,134.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,group_size_distribution,4.0,10.0,40.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,total,NaN,407.0,901.0,494.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,size_four_annotation,NaN,NaN,NaN,NaN,"span_index, magnitude_or_limit",39462.0,0.0,13793ef96d58a146fa7791f7289774c398d275c6da1a49c8a34c38dcfd5c8fdf,2159.0,2301.0,| 2014974 | AT2025cpl | 86.327994 | -47.827215 | 2025-02-24 03:45:38.271 | 22.487 | 0.043 | 22.151 | 0.031 | 21.744 | 0.053 | 21.894 | 0.106 |,detection,counterpart,confirmed,22.487,0.106,None,mag,None,unknown,2025-02-24 03:45:38.271,utc_datetime,absolute_time,None,None,None,Photometry from a multi-object catalog table; verify association with the event.; missing photometric band; photometric system is unknown,[],photometry-row-v1,0.1,table-parse,photometry_row.pipe,0.7,True,0.1
5,size_four_annotation,NaN,NaN,NaN,NaN,"span_index, magnitude_or_limit",39462.0,1.0,13793ef96d58a146fa7791f7289774c398d275c6da1a49c8a34c38dcfd5c8fdf,2159.0,2301.0,| 2014974 | AT2025cpl | 86.327994 | -47.827215 | 2025-02-24 03:45:38.271 | 22.487 | 0.043 | 22.151 | 0.031 | 21.744 | 0.053 | 21.894 | 0.106 |,detection,counterpart,confirmed,22.151,0.106,None,mag,None,unknown,2025-02-24 03:45:38.271,utc_datetime,absolute_time,None,None,None,Photometry from a multi-object catalog table; verify association with the event.; missing photometric band; photometric system is unknown,[],photometry-row-v1,0.1,table-parse,photometry_row.pipe,0.7,True,0.1
6,size_four_annotation,NaN,NaN,NaN,NaN,"span_index, magnitude_or_limit",39462.0,2.0,13793ef96d58a146fa7791f7289774c398d275c6da1a49c8a34c38dcfd5c8fdf,2159.0,2301.0,| 2014974 | AT2025cpl | 86.327994 | -47.827215 | 2025-02-24 03:45:38.271 | 22.487 | 0.043 | 22.151 | 0.031 | 21.744 | 0.053 | 21.894 | 0.106 |,detection,counterpart,confirmed,21.744,0.106,None,mag,None,unknown,2025-02-24 03:45:38.271,utc_datetime,absolute_time,None,None,None,Photometry from a multi-object catalog table; verify association with the event.; missing photometric band; photometric system is unknown,[],photometry-row-v1,0.1,table-parse,photometry_row.pipe,0.7,True,0.1
7,size_four_annotation,NaN,NaN,NaN,NaN,"span_index, magnitude_or_limit",39462.0,3.0,13793ef96d58a146fa7791f7289774c398d275c6da1a49c8a34c38dcfd5c8fdf,2159.0,2301.0,| 2014974 | AT2025cpl | 86.327994 | -47.827215 | 2025-02-24 03:45:38.271 | 22.487 | 0.043 | 22.151 | 0.031 | 21.744 | 0.053 | 21.894 | 0.106 |,detection,counterpart,confirmed,21.894,0.106,None,mag,None,unknown,2025-02-24 03:45:38.271,utc_datetime,absolute_time,None,None,None,Photometry from a multi-object catalog table; verify association with the event.; missing photometric band; photometric system is unknown,[],photometry-row-v1,0.1,table-parse,photometry_row.pipe,0.7,True,0.1

## Decision 2 — a declared field no rule writes

**Observed.** `source_circular_id` is empty on all 63,277 evidence rows, while every other evidence column is populated somewhere; zero observed rules write it. **Why it matters.** Keeping a permanently empty field suggests provenance that the extraction does not provide. **Decided.** Drop `source_circular_id` from the normalized evidence table. **Scope.** One declared column and all 63,277 evidence rows are covered.

In [3]:
column_rows = []
for column in evidence.columns:
    present = evidence[column].map(populated)
    rule_count = evidence.loc[present, 'rule_id'].dropna().nunique()
    column_rows.append({
        'column': column,
        'dtype': str(evidence[column].dtype),
        'null_rows': int(evidence[column].isna().sum()),
        'empty_string_rows': int(evidence[column].map(lambda value: isinstance(value, str) and value == '').sum()),
        'populated_rows': int(present.sum()),
        'rules_with_populated_value': int(rule_count),
    })
decision_2_evidence = pd.DataFrame(column_rows).sort_values(['populated_rows', 'column'], kind='stable')
display(decision_2_evidence)

,column,dtype,null_rows,empty_string_rows,populated_rows,rules_with_populated_value
2,source_circular_id,object,63277,0,0,0
11,unit,object,48921,5814,8542,14
12,comment,object,49508,0,13769,51
10,value,object,2320,0,60957,78
8,target,object,978,0,62299,86
9,certainty,object,0,0,63277,103
0,circular_id,int64,0,0,63277,103
17,confidence,float64,0,0,63277,103
13,extractor_id,object,0,0,63277,103
14,extractor_version,object,0,0,63277,103
7,label,object,0,0,63277,103
15,method,object,0,0,63277,103
18,needs_review,bool,0,0,63277,103
16,rule_id,object,0,0,63277,103
19,schema_version,object,0,0,63277,103
5,span_end,int64,0,0,63277,103
1,span_index,int64,0,0,63277,103
4,span_start,int64,0,0,63277,103
6,text,object,0,0,63277,103
3,text_sha256,object,0,0,63277,103

## Decisions 3 and 9 — spans that share text

**Observed.** Evidence has 1,251 partial-overlap pairs (1,017 crossing, 221 sharing a boundary, 13 strictly contained), while photometry has 407 identical-offset groups and no partial pairs; 30,685 photometry texts carry boundary whitespace. **Why it matters.** Overlaps are meaningful coexisting annotations, and trimming table-row text would invalidate exact canonical offsets. **Decided.** Retain every overlap with an explicit flag and preserve `text` byte for byte. **Scope.** Decision 3 reaches every intersecting pair, while Decision 9 preserves whitespace on 30,685 photometry rows.

In [4]:
def partial_pairs(frame):
    rows = []
    for circular_id, group in frame.groupby('circular_id', sort=True):
        active = []
        for index, row in group.sort_values(['span_start', 'span_end', 'span_index'], kind='stable').iterrows():
            active = [(old_index, old) for old_index, old in active if old['span_end'] > row['span_start']]
            for old_index, old in active:
                if (old['span_start'], old['span_end']) != (row['span_start'], row['span_end']):
                    shape = 'strict_containment' if old['span_start'] < row['span_start'] and row['span_end'] < old['span_end'] else 'shared_boundary' if row['span_end'] <= old['span_end'] else 'crossing'
                    rows.append([circular_id, shape, old['label'], row['label'], old['span_start'], old['span_end'], old['text'], row['span_start'], row['span_end'], row['text']])
            active.append((index, row))
    return pd.DataFrame(rows, columns=['circular_id', 'shape', 'outer_label', 'inner_label', 'first_start', 'first_end', 'first_text', 'second_start', 'second_end', 'second_text'])
pairs = partial_pairs(evidence)
summary = pd.DataFrame([['layer_summary', 'evidence', len(pairs), int((evidence.groupby(['circular_id', 'span_start', 'span_end']).size() > 1).sum())], ['layer_summary', 'photometry', 0, int((photometry.groupby(['circular_id', 'span_start', 'span_end']).size() > 1).sum())]], columns=['record_type', 'layer', 'count', 'identical_offset_groups'])
shapes = pairs['shape'].value_counts().rename_axis('shape').reset_index(name='count').assign(record_type='containment_shape')
cross_tab = pairs[pairs['shape'] != 'crossing'].groupby(['outer_label', 'inner_label']).size().reset_index(name='count').assign(record_type='outer_by_inner')
samples = pairs.sort_values(['circular_id', 'first_start', 'second_start'], kind='stable').head(10).assign(record_type='overlap_pair')
decision_3_evidence = pd.concat([summary, shapes, cross_tab, samples], ignore_index=True, sort=False)
display(decision_3_evidence)
whitespace_rows = []
for layer, frame in [('evidence', evidence), ('photometry', photometry)]:
    mask = frame['text'].map(lambda value: isinstance(value, str) and value != value.strip())
    whitespace_rows.append({'record_type': 'layer_summary', 'layer': layer, 'rows_with_boundary_whitespace': int(mask.sum())})
row = photometry[photometry['text'].map(lambda value: isinstance(value, str) and value.endswith('\n'))].iloc[0]
canonical = circulars.set_index('circular_id').at[row['circular_id'], 'canonical_text']
whitespace_rows.append({'record_type': 'repr_example', 'layer': 'photometry', 'circular_id': row['circular_id'], 'span_start': row['span_start'], 'span_end': row['span_end'], 'text_repr': repr(row['text']), 'exact_slice_matches': canonical[row['span_start']:row['span_end']] == row['text'], 'trimmed_slice_matches': canonical[row['span_start']:row['span_end']] == row['text'].strip()})
decision_9_evidence = pd.DataFrame(whitespace_rows)
display(decision_9_evidence)

,record_type,layer,count,identical_offset_groups,shape,outer_label,inner_label,circular_id,first_start,first_end,first_text,second_start,second_end,second_text
0,layer_summary,evidence,1251.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,layer_summary,photometry,0.0,407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,containment_shape,NaN,1213.0,NaN,crossing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,containment_shape,NaN,25.0,NaN,shared_boundary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,containment_shape,NaN,13.0,NaN,strict_containment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,outer_by_inner,NaN,2.0,NaN,NaN,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,outer_by_inner,NaN,1.0,NaN,NaN,HIGH_ENERGY_PROPERTY,EVENT_IDENTITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,outer_by_inner,NaN,2.0,NaN,NaN,HIGH_ENERGY_PROPERTY,T90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,outer_by_inner,NaN,1.0,NaN,NaN,LOCALIZATION,TRIGGER_INSTRUMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,outer_by_inner,NaN,29.0,NaN,NaN,NEGATIVE_STATEMENT,EVENT_IDENTITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,outer_by_inner,NaN,2.0,NaN,NaN,SPECTROSCOPY,EVENT_IDENTITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,outer_by_inner,NaN,1.0,NaN,NaN,SPECTROSCOPY,HOST_CONTEXT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33141.0,520.0,528.0,long GRB,525.0,536.0,GRB 230101A
13,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33143.0,1243.0,1261.0,short-duration GRB,1258.0,1269.0,GRB 230102A
14,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33145.0,511.0,519.0,long GRB,516.0,527.0,GRB 221230A
15,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33155.0,254.0,263.0,long\n\nGRB,260.0,270.0,GRB 230106
16,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33170.0,986.0,1003.0,long-duration GRB,1000.0,1011.0,GRB 230114A
17,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33199.0,510.0,518.0,long GRB,515.0,526.0,GRB 230119A
18,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33200.0,665.0,683.0,short-duration GRB,680.0,691.0,GRB 230116B
19,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33218.0,986.0,1004.0,short-duration GRB,1001.0,1012.0,GRB 230114B
20,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33236.0,517.0,526.0,short GRB,523.0,534.0,GRB 230129A
21,overlap_pair,NaN,NaN,NaN,crossing,CLASSIFICATION_INTERPRETATION,EVENT_IDENTITY,33246.0,980.0,997.0,long duration GRB,994.0,1005.0,GRB 230126A

,record_type,layer,rows_with_boundary_whitespace,circular_id,span_start,span_end,text_repr,exact_slice_matches,trimmed_slice_matches
0,layer_summary,evidence,176.0,NaN,NaN,NaN,NaN,NaN,NaN
1,layer_summary,photometry,30685.0,NaN,NaN,NaN,NaN,NaN,NaN
2,repr_example,photometry,NaN,33226.0,859.0,873.0,'r > 21.14 mag\n',True,False

## Decision 4 — circulars that produced nothing

**Observed.** Fifty-seven of 12,012 circulars produce no evidence or photometry; 29 of their subjects contain `not a`, compared with 241 subjects corpus-wide. **Why it matters.** Zero output is a property worth retaining, and the shortest circulars show that text length alone does not determine whether rules fire. **Decided.** Keep every circular and attach annotation counts rather than dropping empty-output documents. **Scope.** The decision preserves 57 circular rows that would otherwise disappear.

In [5]:
evidence_counts = evidence.groupby('circular_id').size()
photometry_counts = photometry.groupby('circular_id').size()
counts = circulars['circular_id'].map(evidence_counts).fillna(0).astype(int) + circulars['circular_id'].map(photometry_counts).fillna(0).astype(int)
zero = circulars[counts.eq(0)][['circular_id', 'year', 'subject', 'text_length', 'was_edited']].copy()
zero.insert(0, 'record_type', 'zero_output_circular')
substrings = ['correction', 'retraction', 'erratum', 'GCN Circular', 'not a', 'clarification', 'notice']
substring_rows = [{'record_type': 'subject_substring', 'substring': term, 'zero_output_rows': int(zero['subject'].str.contains(term, case=False, na=False).sum()), 'all_corpus_rows': int(circulars['subject'].str.contains(term, case=False, na=False).sum())} for term in substrings]
shortest = circulars.nsmallest(20, ['text_length', 'circular_id'])[['circular_id', 'year', 'subject', 'text_length', 'was_edited']].copy()
shortest['n_evidence'] = shortest['circular_id'].map(evidence_counts).fillna(0).astype(int)
shortest['n_photometry'] = shortest['circular_id'].map(photometry_counts).fillna(0).astype(int)
shortest.insert(0, 'record_type', 'twenty_shortest')
decision_4_evidence = pd.concat([zero, pd.DataFrame(substring_rows), shortest], ignore_index=True, sort=False)
display(decision_4_evidence)

,record_type,circular_id,year,subject,text_length,was_edited,substring,zero_output_rows,all_corpus_rows,n_evidence,n_photometry
0,zero_output_circular,33299.0,2023.0,Fermi Gamma-ray Burst Monitor triggers 230206723/697396830 and 230206797/697403223 are not GRBs,694.0,False,NaN,NaN,NaN,NaN,NaN
1,zero_output_circular,33473.0,2023.0,VZLUSAT-2 detection of SGR 1806-20,2211.0,False,NaN,NaN,NaN,NaN,NaN
2,zero_output_circular,33495.0,2023.0,SGR 1806-20: Correction to GCN 33494,522.0,False,NaN,NaN,NaN,NaN,NaN
3,zero_output_circular,33638.0,2023.0,New GCN Circulars Portal for Rapid Communications on Astronomical Transients is Online,2382.0,False,NaN,NaN,NaN,NaN,NaN
4,zero_output_circular,34192.0,2023.0,Swift Trigger 1178410 is not an astrophysical event,758.0,False,NaN,NaN,NaN,NaN,NaN
5,zero_output_circular,34502.0,2023.0,Swift Triggers 1186280 and 1186291 are not GRBs,593.0,False,NaN,NaN,NaN,NaN,NaN
6,zero_output_circular,34509.0,2023.0,Swift triggers 1186294-1186304 are not astrophysical transients,464.0,False,NaN,NaN,NaN,NaN,NaN
7,zero_output_circular,34633.0,2023.0,Swift Attitude Control Affecting Some UVOT Images,900.0,False,NaN,NaN,NaN,NaN,NaN
8,zero_output_circular,34691.0,2023.0,Swift Trigger 1191994 is not an astrophysical event,767.0,False,NaN,NaN,NaN,NaN,NaN
9,zero_output_circular,34724.0,2023.0,"Swift Triggers 1192480, 1192481, 1192482 and 1192483 are not astrophysical events",850.0,False,NaN,NaN,NaN,NaN,NaN
10,zero_output_circular,34771.0,2023.0,Swift Triggers 1192735 and 1192737 are not astrophysical events,445.0,False,NaN,NaN,NaN,NaN,NaN
11,zero_output_circular,34774.0,2023.0,Swift Triggers 1192745 and 1192747 are not astrophysical events,467.0,False,NaN,NaN,NaN,NaN,NaN
12,zero_output_circular,34874.0,2023.0,The photometry of the transient in Messier 31 field: GMG observation,1520.0,False,NaN,NaN,NaN,NaN,NaN
13,zero_output_circular,34926.0,2023.0,New Swift-BAT/GUANO and IceCube Notices Available via GCN Kafka,3341.0,False,NaN,NaN,NaN,NaN,NaN
14,zero_output_circular,34968.0,2023.0,LIGO/Virgo/KAGRA O4 Landscape,543.0,False,NaN,NaN,NaN,NaN,NaN
15,zero_output_circular,35432.0,2023.0,"Swift Triggers 1205103, 1205104, 1205107 and 1205110 are not astrophysical events",463.0,False,NaN,NaN,NaN,NaN,NaN
16,zero_output_circular,35552.0,2024.0,Swift Triggers 1209369 and 1209370 are not astrophysical events,872.0,False,NaN,NaN,NaN,NaN,NaN
17,zero_output_circular,35553.0,2024.0,Swift Triggers 1209371 through 1209374 are not astrophysical events,524.0,False,NaN,NaN,NaN,NaN,NaN
18,zero_output_circular,35555.0,2024.0,Swift Triggers 1209401 and 1209403 are not astrophysical events,556.0,False,NaN,NaN,NaN,NaN,NaN
19,zero_output_circular,35556.0,2024.0,Swift Trigger 1209406 is not an astrophysical event,358.0,False,NaN,NaN,NaN,NaN,NaN
20,zero_output_circular,35577.0,2024.0,"Swift triggers 1209631, 1209632, 1209635 and 1209644 are not interesting astrophysical events",489.0,False,NaN,NaN,NaN,NaN,NaN
21,zero_output_circular,35626.0,2024.0,Swift trigger 1210856 is not astrophysical,423.0,False,NaN,NaN,NaN,NaN,NaN
22,zero_output_circular,35638.0,2024.0,Swift Trigger 1211211 and 1211212 are not astrophysical,532.0,False,NaN,NaN,NaN,NaN,NaN
23,zero_output_circular,35661.0,2024.0,"Swift-BAT triggers 1212787, 1212789 are not astrophysical.",416.0,False,NaN,NaN,NaN,NaN,NaN
24,zero_output_circular,35737.0,2024.0,Swift Triggers 12156887-1215690 are not astrophysical events.,428.0,False,NaN,NaN,NaN,NaN,NaN
25,zero_output_circular,35767.0,2024.0,Swift-BAT triggers 1216743-1216748 are not astrophysical,416.0,False,NaN,NaN,NaN,NaN,NaN
26,zero_output_circular,35768.0,2024.0,Swift-BAT triggers 1216751 and 1216753 are not astrophysical events,417.0,False,NaN,NaN,NaN,NaN,NaN
27,zero_output_circular,35779.0,2024.0,Swift-BAT triggers 1216907-1216911 are not astrophysical,417.0,False,NaN,NaN,NaN,NaN,NaN
28,zero_output_circular,35789.0,2024.0,Swift-BAT triggers 1217218-1217222 are not astrophysical,400.0,False,NaN,NaN,NaN,NaN,NaN
29,zero_output_circular,35815.0,2024.0,Swift-BAT triggers 1217729-1217732 are not astrophysical,399.0,False,NaN,NaN,NaN,NaN,NaN
30,zero_output_circular,35816.0,2024.0,Swift-BAT triggers 1217733 - 1217736 are not astrophysical events,425.0,False,NaN,NaN,NaN,NaN,NaN
31,zero_output_circular,35840.0,2024.0,Swift BAT Triggers 1218081 and 1218082 are not astrophysical,362.0,False,NaN,NaN,NaN,NaN,NaN
32,zero_output_circular,35919.0,2024.0,Swift Trigger 1219909 and 1219910 are not a astrophysical,372.0,False,NaN,NaN,NaN,NaN,NaN
33,zero_output_circular,35920.0,2024.0,"Swift triggers 1219917, 1219917 and 1219922 were not astrophysical",384.0,False,NaN,NaN,NaN,NaN,NaN
34,zero_output_circular,35925.0,2024.0,"Swift Triggers 1220090, 1220091 and 1220092 are not astrophysical",389.0,False,NaN,NaN,NaN,NaN,NaN
35,zero_output_circular,35926.0,2024.0,"Swift Triggers 1220093, 1220094, 1220095 and 1220096 are not astrophysical",407.0,False,NaN,NaN,NaN,NaN,NaN
36,zero_output_circular,35928.0,2024.0,"Swift Triggers 1220155, 1220156, 1220157, 1220158, 1220160 and 1220161 were not astrophysical",446.0,False,NaN,NaN,NaN,NaN,NaN
37,zero_output_circular,35953.0,2024.0,Swift satellite in safe mode,1177.0,False,NaN,NaN,NaN,NaN,NaN
38,zero_output_circular,36007.0,2024.0,X-ray transient EP20240331a: MeerLICHT optical upper limits,1506.0,False,NaN,NaN,NaN,NaN,NaN
39,zero_output_circular,36033.0,2024.0,Swift satellite resumes pointed science observations,1579.0,False,NaN,NaN,NaN,NaN,NaN
40,zero_output_circular,36400.0,2024.0,Fermi GBM triggers 736668287/240506253 and 736669277/240506265 are not GRBs,524.0,False,NaN,NaN,NaN,NaN,NaN
41,zero_output_circular,36590.0,2024.0,LXT 240528A: GSP optical upper limit,926.0,False,NaN,NaN,NaN,NaN,NaN
42,zero_output_circular,36605.0,2024.0,Swift Trigger 1232465: consistent with noise,893.0,False,NaN,NaN,NaN,NaN,NaN
43,zero_output_circular,37606.0,2024.0,Insight-HXMT ToO observations of X-ray bursts from SGR 1E 1841-045 / Kes 73,1563.0,False,NaN,NaN,NaN,NaN,NaN
44,zero_output_circular,37686.0,2024.0,NuEm-240926A: Upper limits from a search for coincident neutrino events in IceCube,1575.0,False,NaN,NaN,NaN,NaN,NaN
45,zero_output_circular,39372.0,2025.0,SVOM/sb25021804: QSO variability in Liverpool Telescope observations,1326.0,False,NaN,NaN,NaN,NaN,NaN
46,zero_output_circular,39399.0,2025.0,SVOM trigger sb25022102 is not an astrophysical event,837.0,False,NaN,NaN,NaN,NaN,NaN
47,zero_output_circular,39563.0,2025.0,INTEGRAL: end of scientific operations,686.0,False,NaN,NaN,NaN,NaN,NaN
48,zero_output_circular,39883.0,2025.0,FRB 20250316A: Pan-STARRS r and i-band imaging and photometry,2043.0,True,NaN,NaN,NaN,NaN,NaN
49,zero_output_circular,39909.0,2025.0,FRB 20250316A: FTW optical observations,2685.0,False,NaN,NaN,NaN,NaN,NaN
50,zero_output_circular,40663.0,2025.0,"GRBAlpha reentry on June 9, 2025",1937.0,False,NaN,NaN,NaN,NaN,NaN
51,zero_output_circular,41138.0,2025.0,SVOM J195836+32283/sb25072103: NIR observations with WINTER,1648.0,False,NaN,NaN,NaN,NaN,NaN
52,zero_output_circular,41144.0,2025.0,SVOM J195836+32283/sb25072103: Second VT observation,1620.0,False,NaN,NaN,NaN,NaN,NaN
53,zero_output_circular,42889.0,2025.0,Swift trigger 1418333 is not an astrophysical source,437.0,False,NaN,NaN,NaN,NaN,NaN
54,zero_output_circular,43334.0,2026.0,FRB 20251229A: A potentially hyperactive repeating fast radio burst source,2788.0,False,NaN,NaN,NaN,NaN,NaN
55,zero_output_circular,43431.0,2026.0,FRB 20251229A: Updated CHIME/FRB Baseband Localization of FRB 20251229A,1047.0,False,NaN,NaN,NaN,NaN,NaN
56,zero_output_circular,43470.0,2026.0,Trigger 1442421: Swift detection of HMXB 1A 1118-61,673.0,False,NaN,NaN,NaN,NaN,NaN
57,subject_substring,NaN,NaN,NaN,NaN,NaN,correction,1.0,61.0,NaN,NaN
58,subject_substring,NaN,NaN,NaN,NaN,NaN,retraction,0.0,41.0,NaN,NaN
59,subject_substring,NaN,NaN,NaN,NaN,NaN,erratum,0.0,0.0,NaN,NaN
60,subject_substring,NaN,NaN,NaN,NaN,NaN,GCN Circular,1.0,5.0,NaN,NaN
61,subject_substring,NaN,NaN,NaN,NaN,NaN,not a,29.0,241.0,NaN,NaN
62,subject_substring,NaN,NaN,NaN,NaN,NaN,clarification,0.0,1.0,NaN,NaN
63,subject_substring,NaN,NaN,NaN,NaN,NaN,notice,1.0,2.0,NaN,NaN
64,twenty_shortest,36963.0,2024.0,EP-WXT trigger 01709002661 is not a real source,349.0,False,NaN,NaN,NaN,6.0,0.0
65,twenty_shortest,34151.0,2023.0,IBAS trigger number 10311: not a real GRB,353.0,False,NaN,NaN,NaN,3.0,0.0
66,twenty_shortest,34229.0,2023.0,Swift Trigger 1180063 is not a GRB,354.0,False,NaN,NaN,NaN,1.0,0.0
67,twenty_shortest,35556.0,2024.0,Swift Trigger 1209406 is not an astrophysical event,358.0,False,NaN,NaN,NaN,0.0,0.0
68,twenty_shortest,39702.0,2025.0,The EP-WXT trigger 01709132551 is not a real source,359.0,False,NaN,NaN,NaN,6.0,0.0
69,twenty_shortest,35840.0,2024.0,Swift BAT Triggers 1218081 and 1218082 are not astrophysical,362.0,False,NaN,NaN,NaN,0.0,0.0
70,twenty_shortest,35822.0,2024.0,Swift Trigger 1217799 is not a GRB,366.0,False,NaN,NaN,NaN,3.0,0.0
71,twenty_shortest,34263.0,2023.0,IBAS trigger number 10337: not a real GRB,370.0,False,NaN,NaN,NaN,3.0,0.0
72,twenty_shortest,43966.0,2026.0,Retraction of GCN 43965: GRB is actually solar flare,371.0,False,NaN,NaN,NaN,1.0,0.0
73,twenty_shortest,35919.0,2024.0,Swift Trigger 1219909 and 1219910 are not a astrophysical,372.0,False,NaN,NaN,NaN,0.0,0.0
74,twenty_shortest,39579.0,2025.0,The EP-WXT trigger 01709132212 is not a real source,378.0,False,NaN,NaN,NaN,6.0,0.0
75,twenty_shortest,35772.0,2024.0,Swift Trigger 1216864 is not an astrophysical event,382.0,False,NaN,NaN,NaN,1.0,0.0
76,twenty_shortest,39123.0,2025.0,The EP-WXT trigger 01709131153 is not a real source,383.0,False,NaN,NaN,NaN,5.0,0.0
77,twenty_shortest,35906.0,2024.0,Swift Trigger 1219325 is not a GRB,384.0,False,NaN,NaN,NaN,2.0,0.0
78,twenty_shortest,35920.0,2024.0,"Swift triggers 1219917, 1219917 and 1219922 were not astrophysical",384.0,False,NaN,NaN,NaN,0.0,0.0
79,twenty_shortest,35925.0,2024.0,"Swift Triggers 1220090, 1220091 and 1220092 are not astrophysical",389.0,False,NaN,NaN,NaN,0.0,0.0
80,twenty_shortest,34065.0,2023.0,LIGO/Virgo/KAGRA S230622ba: Retraction of GW compact binary merger candidate,393.0,False,NaN,NaN,NaN,3.0,0.0
81,twenty_shortest,38332.0,2024.0,LIGO/Virgo/KAGRA S241126dm: Retraction of GW compact binary merger candidate,395.0,False,NaN,NaN,NaN,3.0,0.0
82,twenty_shortest,33617.0,2023.0,GRB 230414B (correction GRB name in the GCN 33615): Mondy optical afterglow candidate,396.0,False,NaN,NaN,NaN,2.0,0.0
83,twenty_shortest,34307.0,2023.0,LIGO/Virgo/KAGRA S230731an: not observable by Fermi-GBM,396.0,False,NaN,NaN,NaN,3.0,0.0

## Decision 5 — what the rules say they could not resolve

**Observed.** The rules mark 11,815 annotations for review: 5,583 evidence spans and 6,232 photometry spans, with every reviewed row carrying a comment. **Why it matters.** Confidence alone does not encode unresolved interpretation, because 298 reviewed evidence rows still have confidence 1.0. **Decided.** Preserve `needs_review` and `comment` unchanged. **Scope.** The fields carry rule-authored review information on all 11,815 flagged annotations.

In [6]:
layer_review = annotations.groupby('layer').agg(total_rows=('needs_review', 'size'), reviewed_rows=('needs_review', 'sum')).reset_index().assign(record_type='layer_review')
confidence_review = annotations.groupby(['layer', 'confidence', 'needs_review'], dropna=False).size().reset_index(name='rows').assign(record_type='confidence_by_review')
rule_review = annotations.groupby(['layer', 'rule_id'], dropna=False).agg(total_rows=('rule_id', 'size'), reviewed_rows=('needs_review', 'sum')).reset_index()
rule_review['reviewed_pct'] = (100 * rule_review['reviewed_rows'] / rule_review['total_rows']).round(3)
rule_review['review_behavior'] = rule_review.apply(lambda row: 'always' if row['reviewed_rows'] == row['total_rows'] else 'never' if row['reviewed_rows'] == 0 else 'sometimes', axis=1)
rule_review['record_type'] = 'rule_review'
comment_frames = []
for layer, frame in [('evidence', evidence), ('photometry', photometry)]:
    comments = frame.loc[frame['needs_review'] & frame['comment'].map(populated), 'comment'].value_counts().head(15).rename_axis('comment').reset_index(name='rows')
    comments['layer'] = layer
    comments['record_type'] = 'review_comment_top_15'
    comment_frames.append(comments)
decision_5_evidence = pd.concat([layer_review, confidence_review, rule_review, *comment_frames], ignore_index=True, sort=False)
display(decision_5_evidence)

,layer,total_rows,reviewed_rows,record_type,confidence,needs_review,rows,rule_id,reviewed_pct,review_behavior,comment
0,evidence,63277.0,5583.0,layer_review,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,photometry,37795.0,6232.0,layer_review,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,evidence,NaN,NaN,confidence_by_review,0.50,True,5284.0,NaN,NaN,NaN,NaN
3,evidence,NaN,NaN,confidence_by_review,0.60,True,1.0,NaN,NaN,NaN,NaN
4,evidence,NaN,NaN,confidence_by_review,1.00,False,57694.0,NaN,NaN,NaN,NaN
5,evidence,NaN,NaN,confidence_by_review,1.00,True,298.0,NaN,NaN,NaN,NaN
6,photometry,NaN,NaN,confidence_by_review,0.65,True,2957.0,NaN,NaN,NaN,NaN
7,photometry,NaN,NaN,confidence_by_review,0.70,True,3275.0,NaN,NaN,NaN,NaN
8,photometry,NaN,NaN,confidence_by_review,0.90,False,1306.0,NaN,NaN,NaN,NaN
9,photometry,NaN,NaN,confidence_by_review,0.95,False,30257.0,NaN,NaN,NaN,NaN
10,evidence,3.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.class_exclusion,0.000,never,NaN
11,evidence,1.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.extended_emission,0.000,never,NaN
12,evidence,4.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.firm_classification,0.000,never,NaN
13,evidence,1073.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.grb_class,0.000,never,NaN
14,evidence,2.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.inferred_phenomenon,0.000,never,NaN
15,evidence,51.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.interpretation,0.000,never,NaN
16,evidence,54.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.physical_cause,0.000,never,NaN
17,evidence,869.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.qualified_class,0.000,never,NaN
18,evidence,1.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.this_is,0.000,never,NaN
19,evidence,3.0,0.0,rule_review,NaN,NaN,NaN,classification_interpretation.type_grb,0.000,never,NaN
20,evidence,974.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.candidate_role,0.000,never,NaN
21,evidence,4.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.confirmed_role,0.000,never,NaN
22,evidence,445.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.identify,0.000,never,NaN
23,evidence,45.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.identify_as,0.000,never,NaN
24,evidence,35.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.likely_role,0.000,never,NaN
25,evidence,1094.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.modality_counterpart,0.000,never,NaN
26,evidence,472.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.role_relation,0.000,never,NaN
27,evidence,1.0,0.0,rule_review,NaN,NaN,NaN,counterpart_association.suggest,0.000,never,NaN
28,evidence,841.0,0.0,rule_review,NaN,NaN,NaN,duration.duration_general,0.000,never,NaN
29,evidence,1.0,0.0,rule_review,NaN,NaN,NaN,duration.t50_explicit,0.000,never,NaN
30,evidence,1238.0,47.0,rule_review,NaN,NaN,NaN,duration.t90_explicit,3.796,sometimes,NaN
31,evidence,244.0,0.0,rule_review,NaN,NaN,NaN,duration.t90_nearby,0.000,never,NaN
32,evidence,89.0,0.0,rule_review,NaN,NaN,NaN,duration.t90_t50_pair_t50,0.000,never,NaN
33,evidence,89.0,0.0,rule_review,NaN,NaN,NaN,duration.t90_t50_pair_t90,0.000,never,NaN
34,evidence,1342.0,446.0,rule_review,NaN,NaN,NaN,event_identity.at_sn,33.234,sometimes,NaN
35,evidence,4225.0,58.0,rule_review,NaN,NaN,NaN,event_identity.ep,1.373,sometimes,NaN
36,evidence,13.0,13.0,rule_review,NaN,NaN,NaN,event_identity.ep_dayfraction,100.000,always,NaN
37,evidence,365.0,365.0,rule_review,NaN,NaN,NaN,event_identity.ep_wxt_trigger,100.000,always,NaN
38,evidence,16566.0,368.0,rule_review,NaN,NaN,NaN,event_identity.grb,2.221,sometimes,NaN
39,evidence,720.0,720.0,rule_review,NaN,NaN,NaN,event_identity.grb_dayfraction,100.000,always,NaN
40,evidence,4.0,2.0,rule_review,NaN,NaN,NaN,event_identity.gw,50.000,sometimes,NaN
41,evidence,778.0,12.0,rule_review,NaN,NaN,NaN,event_identity.icecube,1.542,sometimes,NaN
42,evidence,3532.0,37.0,rule_review,NaN,NaN,NaN,event_identity.sname,1.048,sometimes,NaN
43,evidence,275.0,146.0,rule_review,NaN,NaN,NaN,event_identity.ztf,53.091,sometimes,NaN
44,evidence,816.0,0.0,rule_review,NaN,NaN,NaN,high_energy.alpha,0.000,never,NaN
45,evidence,459.0,0.0,rule_review,NaN,NaN,NaN,high_energy.beta,0.000,never,NaN
46,evidence,69.0,4.0,rule_review,NaN,NaN,NaN,high_energy.eiso,5.797,sometimes,NaN
47,evidence,951.0,17.0,rule_review,NaN,NaN,NaN,high_energy.epeak,1.788,sometimes,NaN
48,evidence,1032.0,12.0,rule_review,NaN,NaN,NaN,high_energy.fluence,1.163,sometimes,NaN
49,evidence,810.0,0.0,rule_review,NaN,NaN,NaN,high_energy.peak_flux,0.000,never,NaN
50,evidence,1067.0,0.0,rule_review,NaN,NaN,NaN,high_energy.photon_index,0.000,never,NaN
51,evidence,547.0,0.0,rule_review,NaN,NaN,NaN,high_energy.powerlaw_index,0.000,never,NaN
52,evidence,222.0,0.0,rule_review,NaN,NaN,NaN,high_energy.spectral_index,0.000,never,NaN
53,evidence,6.0,0.0,rule_review,NaN,NaN,NaN,host_context.ambiguous,0.000,never,NaN
54,evidence,121.0,0.0,rule_review,NaN,NaN,NaN,host_context.candidate,0.000,never,NaN
55,evidence,27.0,0.0,rule_review,NaN,NaN,NaN,host_context.context,0.000,never,NaN
56,evidence,297.0,0.0,rule_review,NaN,NaN,NaN,host_context.host,0.000,never,NaN
57,evidence,12.0,0.0,rule_review,NaN,NaN,NaN,host_context.offset,0.000,never,NaN
58,evidence,1868.0,0.0,rule_review,NaN,NaN,NaN,lightcurve_evolution.fade_decline,0.000,never,NaN
59,evidence,66.0,0.0,rule_review,NaN,NaN,NaN,lightcurve_evolution.flatten_plateau,0.000,never,NaN
60,evidence,104.0,0.0,rule_review,NaN,NaN,NaN,lightcurve_evolution.negative,0.000,never,NaN
61,evidence,412.0,0.0,rule_review,NaN,NaN,NaN,lightcurve_evolution.rise_brightening,0.000,never,NaN
62,evidence,258.0,0.0,rule_review,NaN,NaN,NaN,lightcurve_evolution.variability,0.000,never,NaN
63,evidence,2660.0,0.0,rule_review,NaN,NaN,NaN,localization.error_radius,0.000,never,NaN
64,evidence,1768.0,0.0,rule_review,NaN,NaN,NaN,localization.radec_decimal,0.000,never,NaN
65,evidence,4.0,0.0,rule_review,NaN,NaN,NaN,localization.radec_decimal_sexagesimal,0.000,never,NaN
66,evidence,480.0,0.0,rule_review,NaN,NaN,NaN,localization.radec_sexagesimal,0.000,never,NaN
67,evidence,2.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.absent_phenomenon,0.000,never,NaN
68,evidence,1.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.cannot_confirm,0.000,never,NaN
69,evidence,14.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.false_trigger,0.000,never,NaN
70,evidence,4.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.identity_rejection,0.000,never,NaN
71,evidence,85.0,1.0,rule_review,NaN,NaN,NaN,negative_statement.no_counterpart,1.176,sometimes,NaN
72,evidence,81.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.no_evidence,0.000,never,NaN
73,evidence,364.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.no_significant,0.000,never,NaN
74,evidence,9.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.not_associated,0.000,never,NaN
75,evidence,5.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.not_confirmed,0.000,never,NaN
76,evidence,16.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.not_consistent,0.000,never,NaN
77,evidence,203.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.not_grb,0.000,never,NaN
78,evidence,39.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.not_real,0.000,never,NaN
79,evidence,52.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.retraction,0.000,never,NaN
80,evidence,13.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.rules_out,0.000,never,NaN
81,evidence,6.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.spurious,0.000,never,NaN
82,evidence,19.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.unlikely,0.000,never,NaN
83,evidence,65.0,0.0,rule_review,NaN,NaN,NaN,negative_statement.unrelated,0.000,never,NaN
84,evidence,627.0,214.0,rule_review,NaN,NaN,NaN,redshift.redshift_word,34.131,sometimes,NaN
85,evidence,319.0,155.0,rule_review,NaN,NaN,NaN,redshift.z_equals,48.589,sometimes,NaN
86,evidence,3.0,1.0,rule_review,NaN,NaN,NaN,redshift.z_range,33.333,sometimes,NaN
87,evidence,11.0,3.0,rule_review,NaN,NaN,NaN,redshift.z_spec,27.273,sometimes,NaN
88,evidence,423.0,0.0,rule_review,NaN,NaN,NaN,spectroscopy.features,0.000,never,NaN
89,evidence,318.0,0.0,rule_review,NaN,NaN,NaN,spectroscopy.observation,0.000,never,NaN
90,evidence,90.0,0.0,rule_review,NaN,NaN,NaN,spectroscopy.spectrum,0.000,never,NaN
91,evidence,16.0,0.0,rule_review,NaN,NaN,NaN,trigger_instrument.agile_mcal,0.000,never,NaN
92,evidence,95.0,76.0,rule_review,NaN,NaN,NaN,trigger_instrument.astrosat_czti,80.000,sometimes,NaN
93,evidence,96.0,17.0,rule_review,NaN,NaN,NaN,trigger_instrument.calet_cgbm,17.708,sometimes,NaN
94,evidence,775.0,63.0,rule_review,NaN,NaN,NaN,trigger_instrument.ep_wxt,8.129,sometimes,NaN
95,evidence,2266.0,623.0,rule_review,NaN,NaN,NaN,trigger_instrument.fermi_gbm,27.493,sometimes,NaN
96,evidence,137.0,88.0,rule_review,NaN,NaN,NaN,trigger_instrument.fermi_lat,64.234,sometimes,NaN
97,evidence,206.0,147.0,rule_review,NaN,NaN,NaN,trigger_instrument.gecam,71.359,sometimes,NaN
98,evidence,22.0,18.0,rule_review,NaN,NaN,NaN,trigger_instrument.grbalpha,81.818,sometimes,NaN
99,evidence,217.0,5.0,rule_review,NaN,NaN,NaN,trigger_instrument.icecube,2.304,sometimes,NaN
100,evidence,172.0,135.0,rule_review,NaN,NaN,NaN,trigger_instrument.integral,78.488,sometimes,NaN
101,evidence,373.0,144.0,rule_review,NaN,NaN,NaN,trigger_instrument.konus_wind,38.606,sometimes,NaN
102,evidence,138.0,30.0,rule_review,NaN,NaN,NaN,trigger_instrument.maxi,21.739,sometimes,NaN
103,evidence,646.0,175.0,rule_review,NaN,NaN,NaN,trigger_instrument.svom_eclairs,27.090,sometimes,NaN
104,evidence,367.0,266.0,rule_review,NaN,NaN,NaN,trigger_instrument.svom_grm,72.480,sometimes,NaN
105,evidence,1388.0,208.0,rule_review,NaN,NaN,NaN,trigger_instrument.swift_bat,14.986,sometimes,NaN
106,evidence,60.0,45.0,rule_review,NaN,NaN,NaN,trigger_instrument.vzlusat_2,75.000,sometimes,NaN
107,evidence,624.0,624.0,rule_review,NaN,NaN,NaN,trigger_time.clock,100.000,always,NaN
108,evidence,1525.0,9.0,rule_review,NaN,NaN,NaN,trigger_time.clock_on_date,0.590,sometimes,NaN
109,evidence,314.0,26.0,rule_review,NaN,NaN,NaN,trigger_time.date_before_clock,8.280,sometimes,NaN
110,evidence,1237.0,221.0,rule_review,NaN,NaN,NaN,trigger_time.iso,17.866,sometimes,NaN
111,evidence,9.0,5.0,rule_review,NaN,NaN,NaN,trigger_time.mjd,55.556,sometimes,NaN
112,evidence,316.0,37.0,rule_review,NaN,NaN,NaN,trigger_time.t0_explicit,11.709,sometimes,NaN
113,photometry,1419.0,724.0,rule_review,NaN,NaN,NaN,photometry_prose.prose_band_eq,51.022,sometimes,NaN
114,photometry,73.0,68.0,rule_review,NaN,NaN,NaN,photometry_prose.prose_brightness,93.151,sometimes,NaN
115,photometry,2.0,2.0,rule_review,NaN,NaN,NaN,photometry_prose.prose_enumerated_limits,100.000,always,NaN
116,photometry,963.0,459.0,rule_review,NaN,NaN,NaN,photometry_prose.prose_limit_gt,47.664,sometimes,NaN
117,photometry,1530.0,1524.0,rule_review,NaN,NaN,NaN,photometry_prose.prose_limit_upto,99.608,sometimes,NaN
118,photometry,275.0,179.0,rule_review,NaN,NaN,NaN,photometry_prose.prose_magnitude_of,65.091,sometimes,NaN
119,photometry,1.0,1.0,rule_review,NaN,NaN,NaN,photometry_prose.prose_sigma_depth,100.000,always,NaN
120,photometry,318.0,266.0,rule_review,NaN,NaN,NaN,photometry_row.bordered,83.648,sometimes,NaN
121,photometry,30275.0,1630.0,rule_review,NaN,NaN,NaN,photometry_row.pipe,5.384,sometimes,NaN
122,photometry,2939.0,1379.0,rule_review,NaN,NaN,NaN,photometry_row.whitespace,46.921,sometimes,NaN
123,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,2040.0,NaN,NaN,NaN,Multiple instruments have trigger context; the annotator must confirm the primary one.
124,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,1069.0,NaN,NaN,NaN,Event name absent from the subject; verify whether it is an alias of the main event or a referenced/comparison event.
125,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,720.0,NaN,NaN,NaN,Day-fraction format (MASTER/Fermi); it may correspond to a GRB with an official letter suffix. Verify the mapping to the canonical event.
126,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,526.0,NaN,NaN,NaN,"Trigger time without an adjacent date in the text; the annotator must complete the date (for example, from the event name or context)."
127,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,396.0,NaN,NaN,NaN,Multiple times have trigger context; the annotator must choose the correct one.
128,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,365.0,NaN,NaN,NaN,EP-WXT trigger identifier; the annotator must verify the mapping to the canonical event/source.
129,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,308.0,NaN,NaN,NaN,Redshift without explicit attribution to event or context; verify whether it belongs to the event/afterglow/host or to a context galaxy.
130,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,65.0,NaN,NaN,NaN,Classified as a context/intervening redshift; verify that it is not the event redshift.
131,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,17.0,NaN,NaN,NaN,"Unit not identified for Epeak; verify the reported value.; Fermi/GBM, 10-1000 keV"
132,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,13.0,NaN,NaN,NaN,EP day-fraction format; verify the mapping to the canonical event.
133,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,12.0,NaN,NaN,NaN,Duration unit not identified; verify the reported event duration.; SVOM/ECLAIRs
134,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,11.0,NaN,NaN,NaN,Duration unit not identified; verify the reported event duration.; AstroSat/CZTI
135,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,7.0,NaN,NaN,NaN,Duration unit not identified; verify the reported event duration.; SVOM/GRM
136,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,4.0,NaN,NaN,NaN,"Duration unit not identified; verify the reported event duration.; SVOM/ECLAIRs, 5-120 keV"
137,evidence,NaN,NaN,review_comment_top_15,NaN,NaN,4.0,NaN,NaN,NaN,Unit not identified for Eiso; verify the reported value.
138,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,1490.0,NaN,NaN,NaN,Photometric band not found; the annotator must confirm it. Photometric system is unknown; verify AB or Vega.
139,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,1424.0,NaN,NaN,NaN,photometric system is unknown
140,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,718.0,NaN,NaN,NaN,Photometric system is unknown; verify AB or Vega.
141,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,395.0,NaN,NaN,NaN,missing photometric band; photometric system is unknown
142,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,303.0,NaN,NaN,NaN,missing observation time; missing photometric band; photometric system is unknown
143,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,238.0,NaN,NaN,NaN,Measurement time not found in the circular; the annotator must confirm it.
144,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,207.0,NaN,NaN,NaN,Measurement time not found in the circular; the annotator must confirm it. Photometric system is unknown; verify AB or Vega.
145,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,204.0,NaN,NaN,NaN,missing observation time; photometric system is unknown
146,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,189.0,NaN,NaN,NaN,Photometry from a multi-object catalog table; verify association with the event.; missing photometric band; photometric system is unknown
147,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,171.0,NaN,NaN,NaN,missing observation time; Photometry from a multi-object catalog table; verify association with the event.; missing photometric band; photometric system is unknown
148,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,154.0,NaN,NaN,NaN,missing photometric band
149,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,121.0,NaN,NaN,NaN,missing observation time
150,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,110.0,NaN,NaN,NaN,Multiple exposure descriptions found; verify the associated exposure.
151,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,68.0,NaN,NaN,NaN,Photometric system is unknown; verify AB or Vega. Multiple exposure descriptions found; verify the associated exposure.
152,photometry,NaN,NaN,review_comment_top_15,NaN,NaN,58.0,NaN,NaN,NaN,time value does not match expected subtype relative_to_trigger

## Decision 6 — corrupted characters

**Observed.** Four annotation rows contain U+FFFD in their own string fields, while 39 canonical circular texts contain 516 occurrences. **Why it matters.** Affected-row counts and replacement-character occurrence counts describe different damage, and the lost source character cannot be recovered from U+FFFD. **Decided.** Flag affected rows without repairing their values. **Scope.** Four annotations and 39 circulars are identified, with ten circular contexts displayed below.

In [7]:
affected_annotations = []
for layer, frame in [('evidence', evidence), ('photometry', photometry)]:
    string_columns = [column for column in frame.columns if frame[column].dtype == object]
    mask = frame[string_columns].apply(lambda column: column.map(lambda value: isinstance(value, str) and '�' in value)).any(axis=1)
    affected = frame[mask].copy()
    for column in string_columns:
        affected[column] = affected[column].map(lambda value: repr(value) if isinstance(value, str) else value)
    affected.insert(0, 'layer', layer)
    affected.insert(0, 'record_type', 'affected_annotation')
    affected_annotations.append(affected)
circular_mask = circulars['canonical_text'].str.contains('�', regex=False)
contexts = []
for row in circulars[circular_mask].sort_values('circular_id').head(10).itertuples():
    position = row.canonical_text.index('�')
    contexts.append({'record_type': 'circular_context', 'circular_id': row.circular_id, 'year': row.year, 'occurrences': row.canonical_text.count('�'), 'context_repr': repr(row.canonical_text[max(0, position - 60):position + 61])})
metrics = pd.DataFrame([{'record_type': 'metric', 'affected_annotation_rows': sum(len(frame) for frame in affected_annotations), 'affected_circular_rows': int(circular_mask.sum()), 'canonical_text_occurrences': int(circulars.loc[circular_mask, 'canonical_text'].str.count('�').sum())}])
decision_6_evidence = pd.concat([metrics, *affected_annotations, pd.DataFrame(contexts)], ignore_index=True, sort=False)
display(decision_6_evidence)

,record_type,affected_annotation_rows,affected_circular_rows,canonical_text_occurrences,layer,circular_id,span_index,source_circular_id,text_sha256,span_start,span_end,text,label,target,certainty,value,unit,comment,extractor_id,extractor_version,method,rule_id,confidence,needs_review,schema_version,measurement_type,magnitude_or_limit,magnitude_error,limit_sigma,photometric_band,photometric_system,obs_time_raw,obs_time_type,obs_time_reference,exposure_time_raw,instrument,instrument_provenance,provenance_inherited,year,occurrences,context_repr
0,metric,4.0,39.0,516.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,affected_annotation,NaN,NaN,NaN,photometry,33182.0,0.0,NaN,'a4c7d14423ed6132f7b165a2cc8df1267ebe11378f34fb8b5f9ffccb8f2d7fb6',1138.0,1208.0,' 2459961.41763334 | 0.94 | 8 x 300 (stacked) | g��� | 21.04 +/- 0.07 |',NaN,'counterpart','confirmed',NaN,'mag',None,'photometry-row-v1','0.1','table-parse','photometry_row.pipe',0.95,False,'0.1','detection','21.04','0.07',None,'g���','AB','2459961.41763334','jd','absolute_time','8 x 300 (stacked)',None,None,"'[""secondary_time_col=1:0.94(relative_to_trigger)""]'",NaN,NaN,NaN
2,affected_annotation,NaN,NaN,NaN,photometry,33182.0,0.0,NaN,'a4c7d14423ed6132f7b165a2cc8df1267ebe11378f34fb8b5f9ffccb8f2d7fb6',1209.0,1279.0,' 2459961.44794164 | 1.67 | 8 x 300 (stacked) | r��� | 19.99 +/- 0.05 |',NaN,'counterpart','confirmed',NaN,'mag',None,'photometry-row-v1','0.1','table-parse','photometry_row.pipe',0.95,False,'0.1','detection','19.99','0.05',None,'r���','AB','2459961.44794164','jd','absolute_time','8 x 300 (stacked)',None,None,"'[""secondary_time_col=1:1.67(relative_to_trigger)""]'",NaN,NaN,NaN
3,affected_annotation,NaN,NaN,NaN,photometry,33182.0,0.0,NaN,'a4c7d14423ed6132f7b165a2cc8df1267ebe11378f34fb8b5f9ffccb8f2d7fb6',1280.0,1342.0,' 2459961.47255148 | 2.26 | 5 x 300 (stacked) | i��� | >19.84 |',NaN,'counterpart','confirmed',NaN,'mag',None,'photometry-row-v1','0.1','table-parse','photometry_row.pipe',0.95,False,'0.1','upper_limit','19.84',None,None,'i���','AB','2459961.47255148','jd','absolute_time','5 x 300 (stacked)',None,None,"'[""secondary_time_col=1:2.26(relative_to_trigger)""]'",NaN,NaN,NaN
4,affected_annotation,NaN,NaN,NaN,photometry,33637.0,0.0,NaN,'2831af8d1dd46d8744b718ddb1d7096847365e220483a98e76b831e03d9c2917',1338.0,1405.0,'T+7.8 hrs ������||1080s ||R ||19.1 +/- 0.2 ||1.5',NaN,'counterpart','confirmed',NaN,'mag','photometric system is unknown','photometry-row-v1','0.1','table-parse','photometry_row.pipe',0.70,True,'0.1','detection','19.1','0.2',None,'R','unknown','T+7.8 hrs ������','relative_to_trigger','trigger_time_t0','1080s',None,None,"'[""secondary_time_col=4:1.5(relative_to_trigger)""]'",NaN,NaN,NaN
5,circular_context,NaN,NaN,NaN,NaN,33132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,6.0,'ch is\n RA(J2000) = 22h 25m 02.47s\n Dec(J2000) = +25d 08��� 18.6���\nwith an estimated uncertainty of 5 arcmin radius.'
6,circular_context,NaN,NaN,NaN,NaN,33151.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,2.0,"'ttps://fermi.gsfc.nasa.gov/ssc/data/access/gbm/""\nFSSC: Data � Data Access � GBM - Fermi Gamma-ray Space Telescope<https:/'"
7,circular_context,NaN,NaN,NaN,NaN,33167.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,2.0,' at 5.45 deg from the IC-Cascade-230109A \nbest-fit position.�� In a preliminary analysis of LAT data over 30 days \nbefore'
8,circular_context,NaN,NaN,NaN,NaN,33170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,8.0,"'uni.cz>\n\nJ. Ripa (Masaryk U.), A. Pal (Konkoly Observatory),�� N. Werner (Masaryk \nU.), M. Ohno (Hiroshima U.),�� L. Mesz'"
9,circular_context,NaN,NaN,NaN,NaN,33182.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,18.0,"""r the Swift/BAT trigger and took multiple exposures in the g���, r' and i��� filters. We clearly detected the afterglow i"""
10,circular_context,NaN,NaN,NaN,NaN,33212.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,2.0,"'he timescales of 1-month \nprior to T0, one of these objects,�� the source 4FGL J0100.3+0745 \nassociated to the BL Lac obj'"
11,circular_context,NaN,NaN,NaN,NaN,33218.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,8.0,"'uni.cz>\n\nJ. Ripa (Masaryk U.), A. Pal (Konkoly Observatory),�� N. Werner (Masaryk \nU.), M. Ohno (Hiroshima U.),�� L. Mesz'"
12,circular_context,NaN,NaN,NaN,NaN,33229.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,14.0,'mzlp was first detected on 2023-01-28 06:14 UT at r = 17.42 �� 0.04\nmag. ZTF23aabmzlp faded by 2.3 magnitudes in 6.2 hour'
13,circular_context,NaN,NaN,NaN,NaN,33243.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,2.0,"' (University \nof Sydney, CSIRO), B. Marcote (JIV-ERIC), M. P��rez-Torres (IAA-CSIC), L. \nRhodes (University of Oxford), O'"
14,circular_context,NaN,NaN,NaN,NaN,33281.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,3.0,"'Goethe Univ.), J. Palmerio \n(GEPI, Paris obs. and IAP), V. D���Elia (SSDC and INAF-OAR), B. Schneider \n(MIT), L. Izzo (DA'"

## Decision 7 — values that are not numbers

**Observed.** Of 32,540 populated `exposure_time_raw` values, 29,968 parse as floats and 2,572 fail across 1,110 distinct forms; the three other quantitative fields have no parse failures. **Why it matters.** Absence and an unparsed textual duration must remain distinguishable. **Decided.** Add a numeric companion only for exposure time while retaining the raw field. **Scope.** The parse decision applies to all 32,540 populated exposure values, with the 30 most frequent failures shown.

In [8]:
parse_rows = []
failure_rows = []
for column in ['exposure_time_raw', 'magnitude_or_limit', 'magnitude_error', 'limit_sigma']:
    values = photometry.loc[photometry[column].map(populated), column].astype(str)
    parsed = pd.to_numeric(values, errors='coerce')
    failed = values[parsed.isna()]
    parse_rows.append({'record_type': 'parse_summary', 'field': column, 'populated_rows': len(values), 'parsed_rows': int(parsed.notna().sum()), 'failed_rows': len(failed), 'distinct_failed_values': int(failed.nunique())})
    if column == 'exposure_time_raw':
        for value, rows in failed.value_counts().head(30).items():
            failure_rows.append({'record_type': 'top_30_exposure_failure', 'field': column, 'raw_value_repr': repr(value), 'rows': int(rows), 'distinct_failed_values_total': int(failed.nunique())})
decision_7_evidence = pd.concat([pd.DataFrame(parse_rows), pd.DataFrame(failure_rows)], ignore_index=True, sort=False)
display(decision_7_evidence)

,record_type,field,populated_rows,parsed_rows,failed_rows,distinct_failed_values,raw_value_repr,rows,distinct_failed_values_total
0,parse_summary,exposure_time_raw,32540.0,29968.0,2572.0,1110.0,NaN,NaN,NaN
1,parse_summary,magnitude_or_limit,37795.0,37795.0,0.0,0.0,NaN,NaN,NaN
2,parse_summary,magnitude_error,3976.0,3976.0,0.0,0.0,NaN,NaN,NaN
3,parse_summary,limit_sigma,1693.0,1693.0,0.0,0.0,NaN,NaN,NaN
4,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'4x90s exposures',71.0,1110.0
5,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300s',44.0,1110.0
6,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'8x60s',39.0,1110.0
7,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300 * 6',32.0,1110.0
8,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'3x200 s exposures',30.0,1110.0
9,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'600s',28.0,1110.0
10,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'180s',21.0,1110.0
11,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300*3',19.0,1110.0
12,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'4x45s exposures',18.0,1110.0
13,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'90s',18.0,1110.0
14,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300 * 1',18.0,1110.0
15,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'200s',17.0,1110.0
16,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'5x200 s ',16.0,1110.0
17,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'6*50 sec',16.0,1110.0
18,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'45*6',15.0,1110.0
19,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'50 sec',14.0,1110.0
20,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'4 exposures of 600 s',14.0,1110.0
21,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'10x180s',13.0,1110.0
22,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'R',13.0,1110.0
23,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'5x200 s',12.0,1110.0
24,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300*2',12.0,1110.0
25,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'10 x 180 s ',12.0,1110.0
26,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'30*120',11.0,1110.0
27,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300 * 24',11.0,1110.0
28,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300 * 12',11.0,1110.0
29,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'300 sec * 6',11.0,1110.0
30,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'6x300 s exposures',11.0,1110.0
31,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'2x300s',10.0,1110.0
32,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'120s',10.0,1110.0
33,top_30_exposure_failure,exposure_time_raw,NaN,NaN,NaN,NaN,'45.0*2',10.0,1110.0

## Decision 8 — vocabulary that is not closed

**Observed.** `photometric_band` has 207 distinct states including null: apostrophe variants (`r'`, 171 rows; `r’`, 3), 18 cells carrying a following table value, and two magnitude-with-error strings in the band column. **Why it matters.** These values mix real vocabulary variation with extraction defects, so recoding them here would obscure what the rules emitted. **Decided.** Normalize no free-text value in the corpus build. **Scope.** The complete band inventory and distinct-value counts for `value`, `unit`, `instrument`, and both comment columns are retained as observed.

In [9]:
band_counts = photometry['photometric_band'].value_counts(dropna=False)
band_rows = []
for value, rows in band_counts.items():
    text = value if isinstance(value, str) else None
    if text in {"r'", 'r’'}:
        population = 'same_filter_apostrophe_forms'
    elif isinstance(text, str) and '\t' in text:
        population = 'next_table_column_attached'
    elif isinstance(text, str) and re.fullmatch(r'\d+(?:\.\d+)?±\d+(?:\.\d+)?', text):
        population = 'magnitude_in_band_column'
    else:
        population = 'other_observed_value'
    band_rows.append({'record_type': 'photometric_band_inventory', 'column': 'photometric_band', 'value_repr': repr(value), 'rows': int(rows), 'population': population})
distinct_rows = []
for table, frame, column in [('evidence', evidence, 'value'), ('evidence', evidence, 'unit'), ('photometry', photometry, 'instrument'), ('evidence', evidence, 'comment'), ('photometry', photometry, 'comment')]:
    values = frame.loc[frame[column].map(populated), column]
    distinct_rows.append({'record_type': 'distinct_value_count', 'table': table, 'column': column, 'populated_rows': len(values), 'distinct_values': int(values.nunique())})
decision_8_evidence = pd.concat([pd.DataFrame(band_rows), pd.DataFrame(distinct_rows)], ignore_index=True, sort=False)
display(decision_8_evidence)

,record_type,column,value_repr,rows,population,table,populated_rows,distinct_values
0,photometric_band_inventory,photometric_band,'C',26777.0,other_observed_value,NaN,NaN,NaN
1,photometric_band_inventory,photometric_band,None,2837.0,other_observed_value,NaN,NaN,NaN
2,photometric_band_inventory,photometric_band,'r',1254.0,other_observed_value,NaN,NaN,NaN
3,photometric_band_inventory,photometric_band,'R',593.0,other_observed_value,NaN,NaN,NaN
4,photometric_band_inventory,photometric_band,'i',521.0,other_observed_value,NaN,NaN,NaN
5,photometric_band_inventory,photometric_band,'z',424.0,other_observed_value,NaN,NaN,NaN
6,photometric_band_inventory,photometric_band,'g',388.0,other_observed_value,NaN,NaN,NaN
7,photometric_band_inventory,photometric_band,'P-',343.0,other_observed_value,NaN,NaN,NaN
8,photometric_band_inventory,photometric_band,'P/',336.0,other_observed_value,NaN,NaN,NaN
9,photometric_band_inventory,photometric_band,'P\\\\',283.0,other_observed_value,NaN,NaN,NaN
10,photometric_band_inventory,photometric_band,'u',260.0,other_observed_value,NaN,NaN,NaN
11,photometric_band_inventory,photometric_band,'P',226.0,other_observed_value,NaN,NaN,NaN
12,photometric_band_inventory,photometric_band,'VT_R',209.0,other_observed_value,NaN,NaN,NaN
13,photometric_band_inventory,photometric_band,'L',197.0,other_observed_value,NaN,NaN,NaN
14,photometric_band_inventory,photometric_band,'v',194.0,other_observed_value,NaN,NaN,NaN
15,photometric_band_inventory,photometric_band,'VT_B',193.0,other_observed_value,NaN,NaN,NaN
16,photometric_band_inventory,photometric_band,'Rc',193.0,other_observed_value,NaN,NaN,NaN
17,photometric_band_inventory,photometric_band,"""r'""",171.0,same_filter_apostrophe_forms,NaN,NaN,NaN
18,photometric_band_inventory,photometric_band,'white',169.0,other_observed_value,NaN,NaN,NaN
19,photometric_band_inventory,photometric_band,'b',147.0,other_observed_value,NaN,NaN,NaN
20,photometric_band_inventory,photometric_band,'V',137.0,other_observed_value,NaN,NaN,NaN
21,photometric_band_inventory,photometric_band,'J',133.0,other_observed_value,NaN,NaN,NaN
22,photometric_band_inventory,photometric_band,'I',115.0,other_observed_value,NaN,NaN,NaN
23,photometric_band_inventory,photometric_band,'w1',97.0,other_observed_value,NaN,NaN,NaN
24,photometric_band_inventory,photometric_band,'CR',89.0,other_observed_value,NaN,NaN,NaN
25,photometric_band_inventory,photometric_band,"""g'""",87.0,other_observed_value,NaN,NaN,NaN
26,photometric_band_inventory,photometric_band,'w2',87.0,other_observed_value,NaN,NaN,NaN
27,photometric_band_inventory,photometric_band,'H',83.0,other_observed_value,NaN,NaN,NaN
28,photometric_band_inventory,photometric_band,'Ic',80.0,other_observed_value,NaN,NaN,NaN
29,photometric_band_inventory,photometric_band,'B',76.0,other_observed_value,NaN,NaN,NaN
30,photometric_band_inventory,photometric_band,'m2',72.0,other_observed_value,NaN,NaN,NaN
31,photometric_band_inventory,photometric_band,'white_FC',68.0,other_observed_value,NaN,NaN,NaN
32,photometric_band_inventory,photometric_band,'Lim',62.0,other_observed_value,NaN,NaN,NaN
33,photometric_band_inventory,photometric_band,'w',60.0,other_observed_value,NaN,NaN,NaN
34,photometric_band_inventory,photometric_band,"""i'""",56.0,other_observed_value,NaN,NaN,NaN
35,photometric_band_inventory,photometric_band,'P\\',52.0,other_observed_value,NaN,NaN,NaN
36,photometric_band_inventory,photometric_band,'u_FC',51.0,other_observed_value,NaN,NaN,NaN
37,photometric_band_inventory,photometric_band,'uvw2',36.0,other_observed_value,NaN,NaN,NaN
38,photometric_band_inventory,photometric_band,'uvw1',36.0,other_observed_value,NaN,NaN,NaN
39,photometric_band_inventory,photometric_band,'Clear',34.0,other_observed_value,NaN,NaN,NaN
40,photometric_band_inventory,photometric_band,'clear',33.0,other_observed_value,NaN,NaN,NaN
41,photometric_band_inventory,photometric_band,'uvm2',30.0,other_observed_value,NaN,NaN,NaN
42,photometric_band_inventory,photometric_band,'sdssr',27.0,other_observed_value,NaN,NaN,NaN
43,photometric_band_inventory,photometric_band,'r (AB)',23.0,other_observed_value,NaN,NaN,NaN
44,photometric_band_inventory,photometric_band,'G',21.0,other_observed_value,NaN,NaN,NaN
45,photometric_band_inventory,photometric_band,'sdssg',19.0,other_observed_value,NaN,NaN,NaN
46,photometric_band_inventory,photometric_band,'Rc (Vega)',19.0,other_observed_value,NaN,NaN,NaN
47,photometric_band_inventory,photometric_band,'n/d',17.0,other_observed_value,NaN,NaN,NaN
48,photometric_band_inventory,photometric_band,'none',13.0,other_observed_value,NaN,NaN,NaN
49,photometric_band_inventory,photometric_band,'sdssr (AB)',11.0,other_observed_value,NaN,NaN,NaN
50,photometric_band_inventory,photometric_band,'K',11.0,other_observed_value,NaN,NaN,NaN
51,photometric_band_inventory,photometric_band,'o',10.0,other_observed_value,NaN,NaN,NaN
52,photometric_band_inventory,photometric_band,'Luminance',9.0,other_observed_value,NaN,NaN,NaN
53,photometric_band_inventory,photometric_band,"""z'""",9.0,other_observed_value,NaN,NaN,NaN
54,photometric_band_inventory,photometric_band,'4x180s',7.0,other_observed_value,NaN,NaN,NaN
55,photometric_band_inventory,photometric_band,'U',6.0,other_observed_value,NaN,NaN,NaN
56,photometric_band_inventory,photometric_band,'n/d n/d',5.0,other_observed_value,NaN,NaN,NaN
57,photometric_band_inventory,photometric_band,'m475',5.0,other_observed_value,NaN,NaN,NaN
58,photometric_band_inventory,photometric_band,'m600',5.0,other_observed_value,NaN,NaN,NaN
59,photometric_band_inventory,photometric_band,'m625',5.0,other_observed_value,NaN,NaN,NaN
60,photometric_band_inventory,photometric_band,'m550',5.0,other_observed_value,NaN,NaN,NaN
61,photometric_band_inventory,photometric_band,'m575',5.0,other_observed_value,NaN,NaN,NaN
62,photometric_band_inventory,photometric_band,'m675',5.0,other_observed_value,NaN,NaN,NaN
63,photometric_band_inventory,photometric_band,'50x40s',5.0,other_observed_value,NaN,NaN,NaN
64,photometric_band_inventory,photometric_band,'m650',5.0,other_observed_value,NaN,NaN,NaN
65,photometric_band_inventory,photometric_band,'m700',5.0,other_observed_value,NaN,NaN,NaN
66,photometric_band_inventory,photometric_band,'m450',5.0,other_observed_value,NaN,NaN,NaN
67,photometric_band_inventory,photometric_band,'m775',5.0,other_observed_value,NaN,NaN,NaN
68,photometric_band_inventory,photometric_band,'m750',5.0,other_observed_value,NaN,NaN,NaN
69,photometric_band_inventory,photometric_band,'Ks',5.0,other_observed_value,NaN,NaN,NaN
70,photometric_band_inventory,photometric_band,'m725',5.0,other_observed_value,NaN,NaN,NaN
71,photometric_band_inventory,photometric_band,'white (fc)',4.0,other_observed_value,NaN,NaN,NaN
72,photometric_band_inventory,photometric_band,'m525',4.0,other_observed_value,NaN,NaN,NaN
73,photometric_band_inventory,photometric_band,'m825',4.0,other_observed_value,NaN,NaN,NaN
74,photometric_band_inventory,photometric_band,'m400',4.0,other_observed_value,NaN,NaN,NaN
75,photometric_band_inventory,photometric_band,'Gaia G',4.0,other_observed_value,NaN,NaN,NaN
76,photometric_band_inventory,photometric_band,'m425',4.0,other_observed_value,NaN,NaN,NaN
77,photometric_band_inventory,photometric_band,'m500',4.0,other_observed_value,NaN,NaN,NaN
78,photometric_band_inventory,photometric_band,'T-BRO',4.0,other_observed_value,NaN,NaN,NaN
79,photometric_band_inventory,photometric_band,'m800',4.0,other_observed_value,NaN,NaN,NaN
80,photometric_band_inventory,photometric_band,'SDSS',4.0,other_observed_value,NaN,NaN,NaN
81,photometric_band_inventory,photometric_band,'orange',4.0,other_observed_value,NaN,NaN,NaN
82,photometric_band_inventory,photometric_band,'m850',4.0,other_observed_value,NaN,NaN,NaN
83,photometric_band_inventory,photometric_band,'i (AB)',4.0,other_observed_value,NaN,NaN,NaN
84,photometric_band_inventory,photometric_band,'z’',3.0,other_observed_value,NaN,NaN,NaN
85,photometric_band_inventory,photometric_band,'sdssi (AB)',3.0,other_observed_value,NaN,NaN,NaN
86,photometric_band_inventory,photometric_band,'m875',3.0,other_observed_value,NaN,NaN,NaN
87,photometric_band_inventory,photometric_band,'g (AB)',3.0,other_observed_value,NaN,NaN,NaN
88,photometric_band_inventory,photometric_band,'ODK16 f/6.8',3.0,other_observed_value,NaN,NaN,NaN
89,photometric_band_inventory,photometric_band,'SDSS-r',3.0,other_observed_value,NaN,NaN,NaN
90,photometric_band_inventory,photometric_band,'R (Vega)',3.0,other_observed_value,NaN,NaN,NaN
91,photometric_band_inventory,photometric_band,'13:54:44',3.0,other_observed_value,NaN,NaN,NaN
92,photometric_band_inventory,photometric_band,'15:02:22',3.0,other_observed_value,NaN,NaN,NaN
93,photometric_band_inventory,photometric_band,'60x40s',3.0,other_observed_value,NaN,NaN,NaN
94,photometric_band_inventory,photometric_band,'r’',3.0,same_filter_apostrophe_forms,NaN,NaN,NaN
95,photometric_band_inventory,photometric_band,'wh',3.0,other_observed_value,NaN,NaN,NaN
96,photometric_band_inventory,photometric_band,'u (fc)',3.0,other_observed_value,NaN,NaN,NaN
97,photometric_band_inventory,photometric_band,'SDSS-i',3.0,other_observed_value,NaN,NaN,NaN
98,photometric_band_inventory,photometric_band,'180',3.0,other_observed_value,NaN,NaN,NaN
99,photometric_band_inventory,photometric_band,'Apparent',3.0,other_observed_value,NaN,NaN,NaN
100,photometric_band_inventory,photometric_band,'DECam-z',3.0,other_observed_value,NaN,NaN,NaN
101,photometric_band_inventory,photometric_band,'white (FC)',3.0,other_observed_value,NaN,NaN,NaN
102,photometric_band_inventory,photometric_band,'DECam-r',2.0,other_observed_value,NaN,NaN,NaN
103,photometric_band_inventory,photometric_band,'y',2.0,other_observed_value,NaN,NaN,NaN
104,photometric_band_inventory,photometric_band,'W2',2.0,other_observed_value,NaN,NaN,NaN
105,photometric_band_inventory,photometric_band,'Z',2.0,other_observed_value,NaN,NaN,NaN
106,photometric_band_inventory,photometric_band,'Grp',2.0,other_observed_value,NaN,NaN,NaN
107,photometric_band_inventory,photometric_band,'5x180s',2.0,other_observed_value,NaN,NaN,NaN
108,photometric_band_inventory,photometric_band,'T180',2.0,other_observed_value,NaN,NaN,NaN
109,photometric_band_inventory,photometric_band,'Open',2.0,other_observed_value,NaN,NaN,NaN
110,photometric_band_inventory,photometric_band,'Gbp',2.0,other_observed_value,NaN,NaN,NaN
111,photometric_band_inventory,photometric_band,'M2',2.0,other_observed_value,NaN,NaN,NaN
112,photometric_band_inventory,photometric_band,'i’',2.0,other_observed_value,NaN,NaN,NaN
113,photometric_band_inventory,photometric_band,'Red',2.0,other_observed_value,NaN,NaN,NaN
114,photometric_band_inventory,photometric_band,'g’',2.0,other_observed_value,NaN,NaN,NaN
115,photometric_band_inventory,photometric_band,'Hs',2.0,other_observed_value,NaN,NaN,NaN
116,photometric_band_inventory,photometric_band,'22.31',2.0,other_observed_value,NaN,NaN,NaN
117,photometric_band_inventory,photometric_band,'R (AB)',2.0,other_observed_value,NaN,NaN,NaN
118,photometric_band_inventory,photometric_band,'Quatro F4',2.0,other_observed_value,NaN,NaN,NaN
119,photometric_band_inventory,photometric_band,'21.70',2.0,other_observed_value,NaN,NaN,NaN
120,photometric_band_inventory,photometric_band,'cyan',1.0,other_observed_value,NaN,NaN,NaN
121,photometric_band_inventory,photometric_band,'Johnson V',1.0,other_observed_value,NaN,NaN,NaN
122,photometric_band_inventory,photometric_band,'59x120',1.0,other_observed_value,NaN,NaN,NaN
123,photometric_band_inventory,photometric_band,'Mr',1.0,other_observed_value,NaN,NaN,NaN
124,photometric_band_inventory,photometric_band,'sdssi',1.0,other_observed_value,NaN,NaN,NaN
125,photometric_band_inventory,photometric_band,'Mg',1.0,other_observed_value,NaN,NaN,NaN
126,photometric_band_inventory,photometric_band,'265181',1.0,other_observed_value,NaN,NaN,NaN
127,photometric_band_inventory,photometric_band,'wh_FC',1.0,other_observed_value,NaN,NaN,NaN
128,photometric_band_inventory,photometric_band,'267775',1.0,other_observed_value,NaN,NaN,NaN
129,photometric_band_inventory,photometric_band,'White',1.0,other_observed_value,NaN,NaN,NaN
130,photometric_band_inventory,photometric_band,'i���',1.0,other_observed_value,NaN,NaN,NaN
131,photometric_band_inventory,photometric_band,'r���',1.0,other_observed_value,NaN,NaN,NaN
132,photometric_band_inventory,photometric_band,'g���',1.0,other_observed_value,NaN,NaN,NaN
133,photometric_band_inventory,photometric_band,'Mu',1.0,other_observed_value,NaN,NaN,NaN
134,photometric_band_inventory,photometric_band,'AT2023jtu',1.0,other_observed_value,NaN,NaN,NaN
135,photometric_band_inventory,photometric_band,'c',1.0,other_observed_value,NaN,NaN,NaN
136,photometric_band_inventory,photometric_band,'19.20±0.14',1.0,magnitude_in_band_column,NaN,NaN,NaN
137,photometric_band_inventory,photometric_band,'AT2023jpc',1.0,other_observed_value,NaN,NaN,NaN
138,photometric_band_inventory,photometric_band,'17.83±0.01',1.0,magnitude_in_band_column,NaN,NaN,NaN
139,photometric_band_inventory,photometric_band,'ztfg',1.0,other_observed_value,NaN,NaN,NaN
140,photometric_band_inventory,photometric_band,'Mv',1.0,other_observed_value,NaN,NaN,NaN
141,photometric_band_inventory,photometric_band,'267587',1.0,other_observed_value,NaN,NaN,NaN
142,photometric_band_inventory,photometric_band,'uw1',1.0,other_observed_value,NaN,NaN,NaN
143,photometric_band_inventory,photometric_band,'8x180s',1.0,other_observed_value,NaN,NaN,NaN
144,photometric_band_inventory,photometric_band,'Wh',1.0,other_observed_value,NaN,NaN,NaN
145,photometric_band_inventory,photometric_band,'r’\t162',1.0,next_table_column_attached,NaN,NaN,NaN
146,photometric_band_inventory,photometric_band,'54x40s',1.0,other_observed_value,NaN,NaN,NaN
147,photometric_band_inventory,photometric_band,'Limiting',1.0,other_observed_value,NaN,NaN,NaN
148,photometric_band_inventory,photometric_band,'78x40s',1.0,other_observed_value,NaN,NaN,NaN
149,photometric_band_inventory,photometric_band,'g’\t227',1.0,next_table_column_attached,NaN,NaN,NaN
150,photometric_band_inventory,photometric_band,'WHITE',1.0,other_observed_value,NaN,NaN,NaN
151,photometric_band_inventory,photometric_band,'UVM2',1.0,other_observed_value,NaN,NaN,NaN
152,photometric_band_inventory,photometric_band,'i’ (AB)',1.0,other_observed_value,NaN,NaN,NaN
153,photometric_band_inventory,photometric_band,'Newton T200',1.0,other_observed_value,NaN,NaN,NaN
154,photometric_band_inventory,photometric_band,'Telescope Live T200',1.0,other_observed_value,NaN,NaN,NaN
155,photometric_band_inventory,photometric_band,'UVW2',1.0,other_observed_value,NaN,NaN,NaN
156,photometric_band_inventory,photometric_band,'UVW1',1.0,other_observed_value,NaN,NaN,NaN
157,photometric_band_inventory,photometric_band,'19.8',1.0,other_observed_value,NaN,NaN,NaN
158,photometric_band_inventory,photometric_band,'40x40s',1.0,other_observed_value,NaN,NaN,NaN
159,photometric_band_inventory,photometric_band,'G+Gbp+Grp',1.0,other_observed_value,NaN,NaN,NaN
160,photometric_band_inventory,photometric_band,'SDSS-g',1.0,other_observed_value,NaN,NaN,NaN
161,photometric_band_inventory,photometric_band,'um2',1.0,other_observed_value,NaN,NaN,NaN
162,photometric_band_inventory,photometric_band,'Clear (G)',1.0,other_observed_value,NaN,NaN,NaN
163,photometric_band_inventory,photometric_band,'uw2',1.0,other_observed_value,NaN,NaN,NaN
164,photometric_band_inventory,photometric_band,'43x40s',1.0,other_observed_value,NaN,NaN,NaN
165,photometric_band_inventory,photometric_band,'58x40s',1.0,other_observed_value,NaN,NaN,NaN
166,photometric_band_inventory,photometric_band,'16.41',1.0,other_observed_value,NaN,NaN,NaN
167,photometric_band_inventory,photometric_band,'20.7 0.1',1.0,other_observed_value,NaN,NaN,NaN
168,photometric_band_inventory,photometric_band,'Y',1.0,other_observed_value,NaN,NaN,NaN
169,photometric_band_inventory,photometric_band,'W1',1.0,other_observed_value,NaN,NaN,NaN
170,photometric_band_inventory,photometric_band,'21.47 0.09',1.0,other_observed_value,NaN,NaN,NaN
171,photometric_band_inventory,photometric_band,'Ic (Vega)',1.0,other_observed_value,NaN,NaN,NaN
172,photometric_band_inventory,photometric_band,'u (FC)',1.0,other_observed_value,NaN,NaN,NaN
173,photometric_band_inventory,photometric_band,'sdssg (AB)',1.0,other_observed_value,NaN,NaN,NaN
174,photometric_band_inventory,photometric_band,'v_FC',1.0,other_observed_value,NaN,NaN,NaN
175,photometric_band_inventory,photometric_band,'m625\t17.64',1.0,next_table_column_attached,NaN,NaN,NaN
176,photometric_band_inventory,photometric_band,'m600\t17.86',1.0,next_table_column_attached,NaN,NaN,NaN
177,photometric_band_inventory,photometric_band,'m575\t17.85',1.0,next_table_column_attached,NaN,NaN,NaN
178,photometric_band_inventory,photometric_band,'m550\t17.88',1.0,next_table_column_attached,NaN,NaN,NaN
179,photometric_band_inventory,photometric_band,'m525\t17.98',1.0,next_table_column_attached,NaN,NaN,NaN
180,photometric_band_inventory,photometric_band,'m500\t18.07',1.0,next_table_column_attached,NaN,NaN,NaN
181,photometric_band_inventory,photometric_band,'m475\t18.04',1.0,next_table_column_attached,NaN,NaN,NaN
182,photometric_band_inventory,photometric_band,'m450\t18.00',1.0,next_table_column_attached,NaN,NaN,NaN
183,photometric_band_inventory,photometric_band,'m425\t18.29',1.0,next_table_column_attached,NaN,NaN,NaN
184,photometric_band_inventory,photometric_band,'m400\t18.34',1.0,next_table_column_attached,NaN,NaN,NaN
185,photometric_band_inventory,photometric_band,'B (Vega)',1.0,other_observed_value,NaN,NaN,NaN
186,photometric_band_inventory,photometric_band,'m650\t17.57',1.0,next_table_column_attached,NaN,NaN,NaN
187,photometric_band_inventory,photometric_band,'m750\t17.36',1.0,next_table_column_attached,NaN,NaN,NaN
188,photometric_band_inventory,photometric_band,'20.41',1.0,other_observed_value,NaN,NaN,NaN
189,photometric_band_inventory,photometric_band,'m700\t17.58',1.0,next_table_column_attached,NaN,NaN,NaN
190,photometric_band_inventory,photometric_band,'m675\t17.73',1.0,next_table_column_attached,NaN,NaN,NaN
191,photometric_band_inventory,photometric_band,'22.13',1.0,other_observed_value,NaN,NaN,NaN
192,photometric_band_inventory,photometric_band,'21.63',1.0,other_observed_value,NaN,NaN,NaN
193,photometric_band_inventory,photometric_band,'21.61',1.0,other_observed_value,NaN,NaN,NaN
194,photometric_band_inventory,photometric_band,'21.89',1.0,other_observed_value,NaN,NaN,NaN
195,photometric_band_inventory,photometric_band,'20.70',1.0,other_observed_value,NaN,NaN,NaN
196,photometric_band_inventory,photometric_band,'21.58',1.0,other_observed_value,NaN,NaN,NaN
197,photometric_band_inventory,photometric_band,'20.82',1.0,other_observed_value,NaN,NaN,NaN
198,photometric_band_inventory,photometric_band,'21.02',1.0,other_observed_value,NaN,NaN,NaN
199,photometric_band_inventory,photometric_band,'m750\t17.41',1.0,next_table_column_attached,NaN,NaN,NaN
200,photometric_band_inventory,photometric_band,'22.23',1.0,other_observed_value,NaN,NaN,NaN
201,photometric_band_inventory,photometric_band,'22.46',1.0,other_observed_value,NaN,NaN,NaN
202,photometric_band_inventory,photometric_band,'19.14',1.0,other_observed_value,NaN,NaN,NaN
203,photometric_band_inventory,photometric_band,'18.77',1.0,other_observed_value,NaN,NaN,NaN
204,photometric_band_inventory,photometric_band,'0.16825',1.0,other_observed_value,NaN,NaN,NaN
205,photometric_band_inventory,photometric_band,'0.17324',1.0,other_observed_value,NaN,NaN,NaN
206,photometric_band_inventory,photometric_band,'0.17823',1.0,other_observed_value,NaN,NaN,NaN
207,distinct_value_count,value,NaN,NaN,NaN,evidence,60957.0,16206.0
208,distinct_value_count,unit,NaN,NaN,NaN,evidence,8542.0,16.0
209,distinct_value_count,instrument,NaN,NaN,NaN,photometry,29613.0,282.0
210,distinct_value_count,comment,NaN,NaN,NaN,evidence,13769.0,212.0
211,distinct_value_count,comment,NaN,NaN,NaN,photometry,6232.0,56.0

## Decisions 10 and 11 — time and inherited provenance

**Observed.** All circular publication times are non-null UTC values; 653 circulars were edited later, and their retained annotations belong to edited text. `provenance_inherited` is a serialized JSON list with five token types and nine token-to-column checks, all populated. **Why it matters.** Publication and edit times carry different meanings, while inheritance metadata explains structured values without replacing them. **Decided.** Use `created_on_utc` as public time, retain the edit flag, and preserve serialized provenance. **Scope.** Time handling distinguishes 653 edited circulars; provenance is retained on all 37,795 photometry rows.

In [10]:
created = pd.to_datetime(circulars['created_on_utc'], utc=True, format='mixed')
edited = pd.to_datetime(circulars['edited_on_utc'], utc=True, format='mixed')
edit_mask = circulars['was_edited']
gaps = (edited[edit_mask] - created[edit_mask]).dt.total_seconds() / 3600
edited_ids = set(circulars.loc[edit_mask, 'circular_id'])
time_rows = [['created_on_utc', str(created.dtype), str(created.dt.tz), int(created.isna().sum()), created.min(), created.max(), None, None, None], ['edited_on_utc', str(edited.dtype), str(edited.dt.tz), int(edited.isna().sum()), edited.min(), edited.max(), None, None, None], ['edited_gap_hours', str(gaps.dtype), None, int(gaps.isna().sum()), gaps.min(), gaps.max(), gaps.quantile(.25), gaps.median(), gaps.quantile(.75)], ['edited_circulars', None, None, 0, None, None, None, int(edit_mask.sum()), None], ['annotations_on_edited_circulars', None, None, 0, None, None, None, int(evidence['circular_id'].isin(edited_ids).sum() + photometry['circular_id'].isin(edited_ids).sum()), None]]
decision_10_evidence = pd.DataFrame(time_rows, columns=['field', 'dtype', 'timezone', 'nulls', 'min', 'max', 'p25', 'median_or_count', 'p75'])
display(decision_10_evidence)
parsed_provenance = photometry['provenance_inherited'].map(json.loads)
def token_type(token):
    if token.startswith('secondary_time_col='): return 'secondary_time_col'
    if token.startswith('combined_time_cols='): return 'combined_time_cols'
    if token.startswith('photometric_system='): return 'photometric_system'
    return token.split(':', 1)[0]
token_counts = Counter(token_type(token) for values in parsed_provenance for token in values)
token_fields = {'secondary_time_col': ['obs_time_raw', 'obs_time_type', 'obs_time_reference'], 'combined_time_cols': ['obs_time_raw', 'obs_time_type', 'obs_time_reference'], 'photometric_system': ['photometric_system'], 'system_expected_unknown_for_clear_unfiltered': ['photometric_system'], 'system_from_uvot_convention': ['photometric_system']}
provenance_rows = []
for token, columns in token_fields.items():
    mask = parsed_provenance.map(lambda values: any(token_type(value) == token for value in values))
    for column in columns:
        provenance_rows.append({'storage_type': str(pq.read_schema(corpus_dir / 'photometry_spans.parquet').field('provenance_inherited').type), 'token_type': token, 'token_occurrences': token_counts[token], 'rows_with_token': int(mask.sum()), 'corresponding_column': column, 'populated_rows': int(photometry.loc[mask, column].map(populated).sum()), 'null_or_empty_rows': int((~photometry.loc[mask, column].map(populated)).sum())})
decision_11_evidence = pd.DataFrame(provenance_rows)
display(decision_11_evidence)

,field,dtype,timezone,nulls,min,max,p25,median_or_count,p75
0,created_on_utc,"datetime64[ns, UTC]",UTC,0,2023-01-01 02:26:46+00:00,2026-07-19 15:10:41.186000+00:00,NaN,NaN,NaN
1,edited_on_utc,"datetime64[ns, UTC]",UTC,11359,2024-04-03 18:46:19.777000+00:00,2026-07-15 13:28:22.527000+00:00,NaN,NaN,NaN
2,edited_gap_hours,float64,None,0,0.035096,28791.059736,4.089521,14.989129,48.082382
3,edited_circulars,None,None,0,None,None,NaN,653.000000,NaN
4,annotations_on_edited_circulars,None,None,0,None,None,NaN,5437.000000,NaN

,storage_type,token_type,token_occurrences,rows_with_token,corresponding_column,populated_rows,null_or_empty_rows
0,string,secondary_time_col,29211,29020,obs_time_raw,29020,0
1,string,secondary_time_col,29211,29020,obs_time_type,29020,0
2,string,secondary_time_col,29211,29020,obs_time_reference,29020,0
3,string,combined_time_cols,301,301,obs_time_raw,301,0
4,string,combined_time_cols,301,301,obs_time_type,301,0
5,string,combined_time_cols,301,301,obs_time_reference,301,0
6,string,photometric_system,383,383,photometric_system,383,0
7,string,system_expected_unknown_for_clear_unfiltered,27855,27855,photometric_system,27855,0
8,string,system_from_uvot_convention,1147,1147,photometric_system,1147,0

## Decisions 12 and 13 — the schema and the generation

**Observed.** Runtime model declarations contain 57 vocabulary values across seven fields, 17 of which carry zero rows; 15 extractor versions and 113 rules produced the extracted spans, with six rules firing once. **Why it matters.** Zero-use declared values remain part of the schema, and a generation cannot be identified from tables alone. **Decided.** Preserve declared vocabularies whole and accompany the corpus with a manifest of versions, rules, and hashes. **Scope.** Decision 12 covers all 57 declared values; Decision 13 records one generation containing 101,072 annotations.

In [11]:
from skyportal_corpus.extraction_v2.annotations import EventEvidenceAnnotation
from skyportal_corpus.extraction_v2.photometry_annotations import PhotometricMeasurementAnnotation

def declared_vocabularies(model):
    namespace = vars(inspect.getmodule(model))
    found = {}
    for decorator in model.__pydantic_decorators__.field_validators.values():
        function = getattr(decorator.func, '__func__', decorator.func)
        referenced = [namespace[name] for name in function.__code__.co_names if isinstance(namespace.get(name), frozenset)]
        if len(referenced) == 1:
            for field in decorator.info.fields: found[field] = referenced[0]
    return found
vocabulary_rows = []
for layer, model, frame in [('EVENT_EVIDENCE', EventEvidenceAnnotation, evidence), ('PHOTOMETRIC_MEASUREMENT', PhotometricMeasurementAnnotation, photometry)]:
    for field, values in declared_vocabularies(model).items():
        counts = frame[field].value_counts()
        for value in sorted(values): vocabulary_rows.append([layer, field, value, int(counts.get(value, 0))])
decision_12_evidence = pd.DataFrame(vocabulary_rows, columns=['layer', 'field', 'declared_value', 'rows'])
decision_12_evidence['has_zero_rows'] = decision_12_evidence['rows'].eq(0)
display(decision_12_evidence)
rule_counts = annotations['rule_id'].value_counts()
top_two_share = 100 * rule_counts.head(2).sum() / len(annotations)
generation_rows = [{'record_type': 'summary', 'rules': rule_counts.size, 'top_two_share_pct': round(top_two_share, 3), 'rules_firing_once': int(rule_counts.eq(1).sum()), 'extractors': len(manifest['extractors']), 'annotations': len(annotations)}]
for rule_id, rows in rule_counts[rule_counts.eq(1)].items(): generation_rows.append({'record_type': 'rule_firing_once', 'rule_id': rule_id, 'rows': int(rows)})
for item in manifest['extractors']: generation_rows.append({'record_type': 'extractor_version', **item})
decision_13_evidence = pd.DataFrame(generation_rows)
display(decision_13_evidence)

,layer,field,declared_value,rows,has_zero_rows
0,EVENT_EVIDENCE,label,CLASSIFICATION_INTERPRETATION,2061,False
1,EVENT_EVIDENCE,label,COUNTERPART_ASSOCIATION,3070,False
2,EVENT_EVIDENCE,label,DURATION_GENERAL,931,False
3,EVENT_EVIDENCE,label,EVENT_IDENTITY,27820,False
4,EVENT_EVIDENCE,label,HIGH_ENERGY_PROPERTY,5973,False
5,EVENT_EVIDENCE,label,HOST_CONTEXT,463,False
6,EVENT_EVIDENCE,label,LIGHTCURVE_EVOLUTION,2708,False
7,EVENT_EVIDENCE,label,LOCALIZATION,4912,False
8,EVENT_EVIDENCE,label,NEGATIVE_STATEMENT,978,False
9,EVENT_EVIDENCE,label,REDSHIFT_CONTEXT,65,False
10,EVENT_EVIDENCE,label,REDSHIFT_EVENT,895,False
11,EVENT_EVIDENCE,label,SPECTROSCOPY,831,False
12,EVENT_EVIDENCE,label,T90,1571,False
13,EVENT_EVIDENCE,label,TRIGGER_INSTRUMENT,6974,False
14,EVENT_EVIDENCE,label,TRIGGER_TIME,4025,False
15,EVENT_EVIDENCE,target,counterpart,6831,False
16,EVENT_EVIDENCE,target,event,47894,False
17,EVENT_EVIDENCE,target,host,508,False
18,EVENT_EVIDENCE,target,instrument,6974,False
19,EVENT_EVIDENCE,target,nearby_galaxy,92,False
20,EVENT_EVIDENCE,target,unknown,0,True
21,EVENT_EVIDENCE,certainty,candidate,3056,False
22,EVENT_EVIDENCE,certainty,confirmed,56816,False
23,EVENT_EVIDENCE,certainty,rejected,444,False
24,EVENT_EVIDENCE,certainty,tentative,2498,False
25,EVENT_EVIDENCE,certainty,unclear,463,False
26,PHOTOMETRIC_MEASUREMENT,measurement_type,detection,5394,False
27,PHOTOMETRIC_MEASUREMENT,measurement_type,non_detection,0,True
28,PHOTOMETRIC_MEASUREMENT,measurement_type,unclear,0,True
29,PHOTOMETRIC_MEASUREMENT,measurement_type,upper_limit,32401,False
30,PHOTOMETRIC_MEASUREMENT,target,counterpart,36094,False
31,PHOTOMETRIC_MEASUREMENT,target,event,1701,False
32,PHOTOMETRIC_MEASUREMENT,target,host,0,True
33,PHOTOMETRIC_MEASUREMENT,target,instrument,0,True
34,PHOTOMETRIC_MEASUREMENT,target,nearby_galaxy,0,True
35,PHOTOMETRIC_MEASUREMENT,target,unknown,0,True
36,PHOTOMETRIC_MEASUREMENT,certainty,candidate,0,True
37,PHOTOMETRIC_MEASUREMENT,certainty,confirmed,36773,False
38,PHOTOMETRIC_MEASUREMENT,certainty,rejected,0,True
39,PHOTOMETRIC_MEASUREMENT,certainty,tentative,1022,False
40,PHOTOMETRIC_MEASUREMENT,certainty,unclear,0,True
41,PHOTOMETRIC_MEASUREMENT,obs_time_type,calendar_date,0,True
42,PHOTOMETRIC_MEASUREMENT,obs_time_type,jd,219,False
43,PHOTOMETRIC_MEASUREMENT,obs_time_type,mjd,806,False
44,PHOTOMETRIC_MEASUREMENT,obs_time_type,other_timezone,0,True
45,PHOTOMETRIC_MEASUREMENT,obs_time_type,relative_to_trigger,5842,False
46,PHOTOMETRIC_MEASUREMENT,obs_time_type,start_time_plus_exposure,0,True
47,PHOTOMETRIC_MEASUREMENT,obs_time_type,unclear,0,True
48,PHOTOMETRIC_MEASUREMENT,obs_time_type,utc_datetime,29592,False
49,PHOTOMETRIC_MEASUREMENT,obs_time_reference,absolute_time,30617,False
50,PHOTOMETRIC_MEASUREMENT,obs_time_reference,observation_mid,0,True
51,PHOTOMETRIC_MEASUREMENT,obs_time_reference,observation_start,0,True
52,PHOTOMETRIC_MEASUREMENT,obs_time_reference,trigger_time_t0,5842,False
53,PHOTOMETRIC_MEASUREMENT,obs_time_reference,unknown,0,True
54,PHOTOMETRIC_MEASUREMENT,instrument_provenance,explicit_column,28683,False
55,PHOTOMETRIC_MEASUREMENT,instrument_provenance,inferred_column,417,False
56,PHOTOMETRIC_MEASUREMENT,instrument_provenance,prose_same_sentence,513,False

,record_type,rules,top_two_share_pct,rules_firing_once,extractors,annotations,rule_id,rows,extractor_id,extractor_version
0,summary,113.0,46.344,6.0,15.0,101072.0,NaN,NaN,NaN,NaN
1,rule_firing_once,NaN,NaN,NaN,NaN,NaN,duration.t50_explicit,1.0,NaN,NaN
2,rule_firing_once,NaN,NaN,NaN,NaN,NaN,negative_statement.cannot_confirm,1.0,NaN,NaN
3,rule_firing_once,NaN,NaN,NaN,NaN,NaN,classification_interpretation.extended_emission,1.0,NaN,NaN
4,rule_firing_once,NaN,NaN,NaN,NaN,NaN,classification_interpretation.this_is,1.0,NaN,NaN
5,rule_firing_once,NaN,NaN,NaN,NaN,NaN,counterpart_association.suggest,1.0,NaN,NaN
6,rule_firing_once,NaN,NaN,NaN,NaN,NaN,photometry_prose.prose_sigma_depth,1.0,NaN,NaN
7,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,event-identity-v1,0.1
8,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trigger-time-v1,0.1
9,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,localization-v1,0.1
10,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trigger-instrument-v1,0.1
11,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,redshift-v1,0.1
12,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,duration-v1,0.1
13,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high-energy-v1,0.1
14,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative-statement-v1,0.1
15,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lightcurve-evolution-v1,0.1
16,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,counterpart-association-v1,0.1
17,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classification-interpretation-v1,0.1
18,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,host-context-v1,0.1
19,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,spectroscopy-v1,0.1
20,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,photometry-row-v1,0.1
21,extractor_version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,photometry-prose-v1,0.1

## What this record establishes

Each of the thirteen decisions appears here with the data that motivated
it, measured over the extracted tables and without importing the code
that applies them.

This corpus is built with the extraction rules as they stand. That choice
runs through the document: where a measurement reveals a rule defect —
the uncertainty misassigned across rows carrying several magnitudes, the
classification labels landing in the instrument field, the negation
phrasing no rule covers — the corpus records the output as produced and
the defect is documented. Repairing it here would mean the corpus no
longer reflects what the rules emit.

Two decisions correct nothing and measure a great deal.
`vocabulary_coverage` counts how many of the 57 declared values the rules
emit, and the answer is 40: four of the 17 absent ones are precisely
those annotators had to enter by hand during the validation campaign. And
`needs_review` retains the 11,815 annotations where the rule itself
states what it could not resolve, each with its comment.

The corpus is accompanied by a manifest carrying the extractor versions,
the rule inventory and the hash of each table. The project's other two
corpora do not carry one, because they do not need it: they derive from
frozen captures rather than from code that will change.