# INCEpTION gold corpus - countable evaluation (E)

This notebook evaluates the pre-annotation review campaign using only countable,
structured corpus fields. It reads exclusively from `data/gcn_gold_corpus/` and does
not inspect, classify, or aggregate free-text comment content. Evidence and photometry
remain separate throughout.

## 1. Perimeter

The perimeter includes corpus rows, document records, and document-annotator
assignments. The expected 28 "annotators" are assignment rows; the corpus contains
fewer distinct people because one person may review multiple documents.

In [1]:
import importlib.util
import json
from pathlib import Path

import nbformat
import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 360)

ROOT = next(path for path in [Path.cwd(), *Path.cwd().parents]
            if (path / "data/gcn_gold_corpus").is_dir())
CORPUS = ROOT / "data/gcn_gold_corpus"
OUTPUT = ROOT / "data/interim/gcn_gold_eval"
OUTPUT.mkdir(parents=True, exist_ok=True)

COMMON_COLUMNS = [
    "document_name", "layer_source", "begin", "end", "span_index",
    "covered_text", "match_status", "changed_fields", "has_category",
    "is_annotator_note",
]
EVIDENCE_FEATURES = ["label", "target", "certainty", "value", "unit"]
PHOTOMETRY_FEATURES = [
    "measurement_type", "photometric_system", "target", "certainty",
    "magnitude_or_limit", "magnitude_error", "limit_sigma", "unit",
    "photometric_band", "obs_time_raw", "obs_time_type", "obs_time_reference",
    "exposure_time_raw", "timezone_raw", "instrument",
]
TABLES = {
    "evidence": pd.read_parquet(
        CORPUS / "evidence_spans.parquet",
        columns=COMMON_COLUMNS + EVIDENCE_FEATURES),
    "photometry": pd.read_parquet(
        CORPUS / "photometry_spans.parquet",
        columns=COMMON_COLUMNS + PHOTOMETRY_FEATURES),
}
assignments = pd.read_parquet(
    CORPUS / "annotators.parquet", columns=["document_name", "annotator"])
documents = pd.read_parquet(CORPUS / "documents.parquet")
assert all("comment" not in frame.columns for frame in TABLES.values())

expected = {
    "evidence_spans": 6615,
    "photometry_spans": 2741,
    "annotator_assignments": 28,
    "documents": 10,
}
observed = {
    "evidence_spans": len(TABLES["evidence"]),
    "photometry_spans": len(TABLES["photometry"]),
    "annotator_assignments": len(assignments),
    "documents": len(documents),
}
perimeter = pd.DataFrame([
    {"measure": name, "expected": expected[name], "observed": value,
     "status": "PASS" if value == expected[name] else "DEVIATION"}
    for name, value in observed.items()
])
display(perimeter)
print(f"Distinct annotator names: {assignments['annotator'].nunique()}")
print("Free-text comment columns loaded: 0")

                 measure  expected  observed status
0         evidence_spans      6615      6615   PASS
1       photometry_spans      2741      2741   PASS
2  annotator_assignments        28        28   PASS
3              documents        10        10   PASS

Distinct annotator names: 10
Free-text comment columns loaded: 0

## 2. Review depth

`n_baseline_reviewed` is `accepted + corrected + deleted`. The pair-level
`acceptance_rate` uses `accepted / (accepted + corrected)`, matching the first
acceptance definition in Part 3.

In [2]:
assignment_pairs = assignments[["document_name", "annotator"]].drop_duplicates()
pair_frames = []
for layer, frame in TABLES.items():
    reviewed = frame.loc[frame["layer_source"].ne("INITIAL_CAS")]
    counts = (reviewed.groupby(["document_name", "layer_source", "match_status"])
              .size().unstack(fill_value=0).reset_index()
              .rename(columns={"layer_source": "annotator"}))
    for status in ["accepted", "corrected", "created", "deleted"]:
        if status not in counts:
            counts[status] = 0
    profile = assignment_pairs.merge(
        counts, on=["document_name", "annotator"], how="left")
    profile[["accepted", "corrected", "created", "deleted"]] = profile[[
        "accepted", "corrected", "created", "deleted"]].fillna(0).astype(int)
    profile.insert(2, "layer", layer)
    profile = profile.rename(columns={
        "accepted": "n_accepted", "corrected": "n_corrected",
        "created": "n_created", "deleted": "n_deleted",
    })
    profile["n_baseline_reviewed"] = (
        profile["n_accepted"] + profile["n_corrected"] + profile["n_deleted"])
    denominator = profile["n_accepted"] + profile["n_corrected"]
    profile["acceptance_rate"] = profile["n_accepted"].div(
        denominator.where(denominator.ne(0)))
    pair_frames.append(profile[[
        "document_name", "annotator", "layer", "n_baseline_reviewed",
        "n_accepted", "n_corrected", "n_created", "n_deleted", "acceptance_rate"]])
per_pair_profile = pd.concat(pair_frames, ignore_index=True).sort_values(
    ["layer", "document_name", "annotator"]).reset_index(drop=True)
per_pair_profile.to_csv(
    OUTPUT / "per_pair_profile.csv", index=False, lineterminator="\n")
display(per_pair_profile)

                  document_name      annotator       layer  n_baseline_reviewed  n_accepted  n_corrected  n_created  n_deleted  acceptance_rate
0             event_2025aji.xmi        Camille    evidence                  201         188            9          3          4         0.954315
1             event_2025aji.xmi        Patrice    evidence                  201         195            6          1          0         0.970149
2             event_2025aji.xmi         Xinyue    evidence                  201         201            0          1          0         1.000000
3             event_2026owq.xmi         Dahlia    evidence                  204         195            9          0          0         0.955882
4             event_2026owq.xmi          Sarah    evidence                  204         197            7          5          0         0.965686
5             event_2026owq.xmi         Zhanat    evidence                  204         196            8          1          0         0.960784
6    event_EP-260623_025405.xmi         Dahlia    evidence                   96          91            5         10          0         0.947917
7    event_EP-260623_025405.xmi         Yodgor    evidence                   96          96            0          0          0         1.000000
8   event_GCN-251013_173943.xmi         Andrii    evidence                  237         237            0          0          0         1.000000
9   event_GCN-251013_173943.xmi          Eslam    evidence                  237         237            0          0          0         1.000000
10  event_GCN-251013_173943.xmi          Sarah    evidence                  237         222           15         16          0         0.936709
11  event_GCN-251222_170549.xmi        Camille    evidence                  242         224           18          0          0         0.925620
12  event_GCN-251222_170549.xmi  Priyadarshini    evidence                  242         227           15         14          0         0.938017
13  event_GCN-260604_202037.xmi          Sarah    evidence                  146         136           10          0          0         0.931507
14  event_GCN-260604_202037.xmi         Yodgor    evidence                  146         146            0          4          0         1.000000
15  event_GCN-260614_134953.xmi        Patrice    evidence                   73          72            1          1          0         0.986301
16  event_GCN-260614_134953.xmi  Priyadarshini    evidence                   73          66            7          4          0         0.904110
17  event_GRB-241025_013651.xmi        Camille    evidence                  157         151            5          2          1         0.967949
18  event_GRB-241025_013651.xmi          Eslam    evidence                  157         157            0          0          0         1.000000
19  event_GRB-241025_013651.xmi         Xinyue    evidence                  157         157            0          0          0         1.000000
20        event_GRB-260708A.xmi        Camille    evidence                   68          58           10          2          0         0.852941
21        event_GRB-260708A.xmi          Eslam    evidence                   68          55           13         15          0         0.808824
22        event_GRB-260708A.xmi        Patrice    evidence                   68          60            8          0          0         0.882353
23        event_GRB-260708A.xmi         Zhanat    evidence                   68          60            8          2          0         0.882353
24          event_GRB241030.xmi         Dahlia    evidence                  259         238           21          8          0         0.918919
25          event_GRB241030.xmi  Priyadarshini    evidence                  259         237           22         22          0         0.915058
26          event_GRB241030.xmi         Yodgor    evidence                  259         259            0          0          0         1.000000
27          event_GRB241030.xmi         Zhanat    evidence                  259         232           27          2          0         0.895753
28            event_2025aji.xmi        Camille  photometry                  109          63           46         13          0         0.577982
29            event_2025aji.xmi        Patrice  photometry                  109          85           24          0          0         0.779817
30            event_2025aji.xmi         Xinyue  photometry                  109         109            0          0          0         1.000000
31            event_2026owq.xmi         Dahlia  photometry                   68          10           58          1          0         0.147059
32            event_2026owq.xmi          Sarah  photometry                   68          38           30         11          0         0.558824
33            event_2026owq.xmi         Zhanat  photometry                   68          44           24          1          0         0.647059
34   event_EP-260623_025405.xmi         Dahlia  photometry                   19           0           19          5          0         0.000000
35   event_EP-260623_025405.xmi         Yodgor  photometry                   19          19            0          6          0         1.000000
36  event_GCN-251013_173943.xmi         Andrii  photometry                  266         266            0          0          0         1.000000
37  event_GCN-251013_173943.xmi          Eslam  photometry                  266         266            0          0          0         1.000000
38  event_GCN-251013_173943.xmi          Sarah  photometry                  266         107          159         24          0         0.402256
39  event_GCN-251222_170549.xmi        Camille  photometry                   37          10           27          4          0         0.270270
40  event_GCN-251222_170549.xmi  Priyadarshini  photometry                   37           8           29          8          0         0.216216
41  event_GCN-260604_202037.xmi          Sarah  photometry                   62           2           60          7          0         0.032258
42  event_GCN-260604_202037.xmi         Yodgor  photometry                   62          58            4          9          0         0.935484
43  event_GCN-260614_134953.xmi        Patrice  photometry                    7           7            0          0          0         1.000000
44  event_GCN-260614_134953.xmi  Priyadarshini  photometry                    7           0            7          0          0         0.000000
45  event_GRB-241025_013651.xmi        Camille  photometry                   45          32           13          3          0         0.711111
46  event_GRB-241025_013651.xmi          Eslam  photometry                   45          45            0          0          0         1.000000
47  event_GRB-241025_013651.xmi         Xinyue  photometry                   45          45            0          0          0         1.000000
48        event_GRB-260708A.xmi        Camille  photometry                    3           1            2          0          0         0.333333
49        event_GRB-260708A.xmi          Eslam  photometry                    3           0            3          2          0         0.000000
50        event_GRB-260708A.xmi        Patrice  photometry                    3           1            2          1          0         0.333333
51        event_GRB-260708A.xmi         Zhanat  photometry                    3           0            3          1          0         0.000000
52          event_GRB241030.xmi         Dahlia  photometry                   54           0           54          6          0         0.000000
53          event_GRB241030.xmi  Priyadarshini  photometry                   54           7           47         11          0         0.129630
54          event_GRB241030.xmi         Yodgor  photometry                   54          54            0          8          0         1.000000
55          event_GRB241030.xmi         Zhanat  photometry                   54          14           40          8          0         0.259259

In [3]:
per_annotator_profile = (per_pair_profile.groupby(["annotator", "layer"], as_index=False)
    .agg(n_documents=("document_name", "nunique"),
         n_baseline_reviewed=("n_baseline_reviewed", "sum"),
         n_accepted=("n_accepted", "sum"), n_corrected=("n_corrected", "sum"),
         n_created=("n_created", "sum"), n_deleted=("n_deleted", "sum")))
denominator = per_annotator_profile["n_accepted"] + per_annotator_profile["n_corrected"]
per_annotator_profile["acceptance_rate"] = per_annotator_profile["n_accepted"].div(
    denominator.where(denominator.ne(0)))
per_annotator_profile = per_annotator_profile.sort_values(
    ["layer", "acceptance_rate", "annotator"]).reset_index(drop=True)
per_annotator_profile.to_csv(
    OUTPUT / "per_annotator_profile.csv", index=False, lineterminator="\n")
display(per_annotator_profile)

        annotator       layer  n_documents  n_baseline_reviewed  n_accepted  n_corrected  n_created  n_deleted  acceptance_rate
0          Zhanat    evidence            3                  531         488           43          5          0         0.919021
1   Priyadarshini    evidence            3                  574         530           44         40          0         0.923345
2         Camille    evidence            4                  668         621           42          7          5         0.936652
3          Dahlia    evidence            3                  559         524           35         18          0         0.937388
4           Sarah    evidence            3                  587         555           32         21          0         0.945486
5         Patrice    evidence            3                  342         327           15          2          0         0.956140
6           Eslam    evidence            3                  462         449           13         15          0         0.971861
7          Andrii    evidence            1                  237         237            0          0          0         1.000000
8          Xinyue    evidence            2                  358         358            0          1          0         1.000000
9          Yodgor    evidence            3                  501         501            0          4          0         1.000000
10         Dahlia  photometry            3                  141          10          131         12          0         0.070922
11  Priyadarshini  photometry            3                   98          15           83         19          0         0.153061
12          Sarah  photometry            3                  396         147          249         42          0         0.371212
13         Zhanat  photometry            3                  125          58           67         10          0         0.464000
14        Camille  photometry            4                  194         106           88         20          0         0.546392
15        Patrice  photometry            3                  119          93           26          1          0         0.781513
16         Yodgor  photometry            3                  135         131            4         23          0         0.970370
17          Eslam  photometry            3                  314         311            3          2          0         0.990446
18         Andrii  photometry            1                  266         266            0          0          0         1.000000
19         Xinyue  photometry            2                  154         154            0          0          0         1.000000

In [4]:
acceptance_ranges = []
for layer, rows in per_annotator_profile.groupby("layer"):
    minimum = rows["acceptance_rate"].min()
    maximum = rows["acceptance_rate"].max()
    acceptance_ranges.append({
        "layer": layer,
        "minimum_acceptance_rate": minimum,
        "minimum_annotators": ", ".join(sorted(
            rows.loc[rows["acceptance_rate"].eq(minimum), "annotator"])),
        "maximum_acceptance_rate": maximum,
        "maximum_annotators": ", ".join(sorted(
            rows.loc[rows["acceptance_rate"].eq(maximum), "annotator"])),
    })
acceptance_ranges = pd.DataFrame(acceptance_ranges)
display(acceptance_ranges)

        layer  minimum_acceptance_rate minimum_annotators  maximum_acceptance_rate      maximum_annotators
0    evidence                 0.919021             Zhanat                      1.0  Andrii, Xinyue, Yodgor
1  photometry                 0.070922             Dahlia                      1.0          Andrii, Xinyue

Acceptance rates span **91.90%-100%** for evidence and **7.09%-100%** for
photometry. Therefore an acceptance rate from this campaign measures review depth and
editing practice as well as the pre-annotation system. The variation is reported
descriptively; it is not a judgement about the quality of any individual's work.

## 3. Acceptance rate: two countable definitions

A corrected row is **comment-only** exactly when parsed `changed_fields` equals
`["comment"]`. Every other corrected row contains at least one content field. Under
definition (b), a correction that only adds a comment does not modify the extracted data.

In [5]:
reviewed_frames = []
for layer, frame in TABLES.items():
    rows = frame.loc[frame["layer_source"].ne("INITIAL_CAS")].copy()
    rows["layer"] = layer
    rows["annotator"] = rows["layer_source"]
    rows["parsed_changed_fields"] = rows["changed_fields"].map(
        lambda value: json.loads(value) if isinstance(value, str) else [])
    reviewed_frames.append(rows)
reviewed_spans = pd.concat(reviewed_frames, ignore_index=True, sort=False)
corrected_rows = reviewed_spans.loc[reviewed_spans["match_status"].eq("corrected")].copy()
corrected_rows["correction_kind"] = np.where(
    corrected_rows["parsed_changed_fields"].map(lambda fields: fields == ["comment"]),
    "comment_only", "content")
correction_split = (corrected_rows.groupby(["layer", "correction_kind"]).size()
                    .unstack(fill_value=0).reset_index())
correction_split["total_corrected"] = (
    correction_split["comment_only"] + correction_split["content"])
correction_split.to_csv(
    OUTPUT / "correction_split.csv", index=False, lineterminator="\n")
display(correction_split)
print(f"Corpus-wide comment-only corrections: {int(correction_split['comment_only'].sum())}")
print(f"Corpus-wide content corrections: {int(correction_split['content'].sum())}")

correction_kind       layer  comment_only  content  total_corrected
0                  evidence           167       57              224
1                photometry           276      375              651

Corpus-wide comment-only corrections: 443
Corpus-wide content corrections: 432

In [6]:
def acceptance_summary(rows, perimeter):
    output_rows = []
    for layer, layer_rows in rows.groupby("layer"):
        accepted = int(layer_rows["match_status"].eq("accepted").sum())
        corrected = int(layer_rows["match_status"].eq("corrected").sum())
        content_corrected = int((layer_rows["match_status"].eq("corrected") &
            layer_rows["parsed_changed_fields"].map(
                lambda fields: fields != ["comment"])).sum())
        output_rows.append({
            "perimeter": perimeter, "layer": layer, "n_accepted": accepted,
            "n_all_corrected": corrected, "n_content_corrected": content_corrected,
            "acceptance_all_corrections": accepted / (accepted + corrected),
            "acceptance_content_corrections_only": accepted / (
                accepted + content_corrected),
        })
    return pd.DataFrame(output_rows)


acceptance_rates = acceptance_summary(reviewed_spans, "all annotators")
active_annotators = {
    layer: set(rows.loc[rows["n_corrected"].gt(0), "annotator"])
    for layer, rows in per_annotator_profile.groupby("layer")
}
active_rows = pd.concat([
    reviewed_spans.loc[
        reviewed_spans["layer"].eq(layer) &
        reviewed_spans["annotator"].isin(names)]
    for layer, names in active_annotators.items()
], ignore_index=True)
acceptance_active = acceptance_summary(active_rows, "n_corrected > 0 in layer")
acceptance_active["excluded_annotators"] = acceptance_active["layer"].map(
    lambda layer: ", ".join(sorted(
        set(per_annotator_profile.loc[
            per_annotator_profile["layer"].eq(layer), "annotator"]) -
        active_annotators[layer])))
acceptance_rates.to_csv(
    OUTPUT / "acceptance_rates.csv", index=False, lineterminator="\n")
acceptance_active.to_csv(
    OUTPUT / "acceptance_rates_active_reviewers.csv", index=False, lineterminator="\n")
display(acceptance_rates)
display(acceptance_active)

        perimeter       layer  n_accepted  n_all_corrected  n_content_corrected  acceptance_all_corrections  acceptance_content_corrections_only
0  all annotators    evidence        4590              224                   57                    0.953469                             0.987734
1  all annotators  photometry        1291              651                  375                    0.664779                             0.774910

                  perimeter       layer  n_accepted  n_all_corrected  n_content_corrected  acceptance_all_corrections  acceptance_content_corrections_only     excluded_annotators
0  n_corrected > 0 in layer    evidence        3494              224                   57                    0.939753                             0.983948  Andrii, Xinyue, Yodgor
1  n_corrected > 0 in layer  photometry         871              651                  375                    0.572273                             0.699037          Andrii, Xinyue

In [7]:
content_by_document = (corrected_rows.loc[corrected_rows["correction_kind"].eq("content")]
    .groupby(["document_name", "layer"]).size()
    .rename("n_content_corrected").reset_index())
acceptance_by_document = (per_pair_profile.groupby(
    ["document_name", "layer"], as_index=False)
    .agg(n_accepted=("n_accepted", "sum"), n_corrected=("n_corrected", "sum")))
acceptance_by_document = acceptance_by_document.merge(
    content_by_document, on=["document_name", "layer"], how="left")
acceptance_by_document["n_content_corrected"] = (
    acceptance_by_document["n_content_corrected"].fillna(0).astype(int))
acceptance_by_document["acceptance_all_corrections"] = (
    acceptance_by_document["n_accepted"] /
    (acceptance_by_document["n_accepted"] + acceptance_by_document["n_corrected"]))
acceptance_by_document["acceptance_content_corrections_only"] = (
    acceptance_by_document["n_accepted"] /
    (acceptance_by_document["n_accepted"] +
     acceptance_by_document["n_content_corrected"]))
acceptance_by_document = acceptance_by_document.sort_values(
    ["layer", "acceptance_all_corrections", "document_name"])
acceptance_by_document.to_csv(
    OUTPUT / "acceptance_by_document.csv", index=False, lineterminator="\n")
display(acceptance_by_document)

                  document_name       layer  n_accepted  n_corrected  n_content_corrected  acceptance_all_corrections  acceptance_content_corrections_only
16        event_GRB-260708A.xmi    evidence         233           39                    9                    0.856618                             0.962810
8   event_GCN-251222_170549.xmi    evidence         451           33                   17                    0.931818                             0.963675
18          event_GRB241030.xmi    evidence         966           70                   14                    0.932432                             0.985714
12  event_GCN-260614_134953.xmi    evidence         138            8                    3                    0.945205                             0.978723
2             event_2026owq.xmi    evidence         588           24                    1                    0.960784                             0.998302
10  event_GCN-260604_202037.xmi    evidence         282           10                    1                    0.965753                             0.996466
4    event_EP-260623_025405.xmi    evidence         187            5                    1                    0.973958                             0.994681
0             event_2025aji.xmi    evidence         584           15                    8                    0.974958                             0.986486
6   event_GCN-251013_173943.xmi    evidence         696           15                    0                    0.978903                             1.000000
14  event_GRB-241025_013651.xmi    evidence         465            5                    3                    0.989362                             0.993590
17        event_GRB-260708A.xmi  photometry           2           10                   10                    0.166667                             0.166667
9   event_GCN-251222_170549.xmi  photometry          18           56                   54                    0.243243                             0.250000
19          event_GRB241030.xmi  photometry          75          141                  132                    0.347222                             0.362319
3             event_2026owq.xmi  photometry          92          112                   82                    0.450980                             0.528736
11  event_GCN-260604_202037.xmi  photometry          60           64                    4                    0.483871                             0.937500
5    event_EP-260623_025405.xmi  photometry          19           19                   19                    0.500000                             0.500000
13  event_GCN-260614_134953.xmi  photometry           7            7                    7                    0.500000                             0.500000
1             event_2025aji.xmi  photometry         257           70                   55                    0.785933                             0.823718
7   event_GCN-251013_173943.xmi  photometry         639          159                    1                    0.800752                             0.998437
15  event_GRB-241025_013651.xmi  photometry         122           13                   11                    0.903704                             0.917293

## 4. Precision, recall, and F1

- **TP**: a baseline span kept by the annotator (`accepted` or `corrected`).
- **FP**: a baseline span deleted by the annotator.
- **FN**: a span created by the annotator with no baseline counterpart.

Created rows with `is_annotator_note=True` are excluded. Precision is an upper bound:
the annotation guide instructed reviewers to keep incorrect pre-annotations and explain
them in free text rather than delete them, so deletions are near zero. Part 4b presents
the bounded version using only structured rejection signals. Recall depends on review
depth because a missing span is counted only when a reviewer added it.

In [8]:
reviewed_spans["is_annotator_note"] = reviewed_spans["is_annotator_note"].fillna(False)
excluded_notes = reviewed_spans.loc[
    reviewed_spans["match_status"].eq("created") &
    reviewed_spans["is_annotator_note"]]
excluded_note_counts = (excluded_notes.groupby("layer").size()
                        .reindex(["evidence", "photometry"], fill_value=0)
                        .reset_index(name="excluded_annotator_notes"))
display(excluded_note_counts)


def metric_counts(rows):
    tp = int(rows["match_status"].isin(["accepted", "corrected"]).sum())
    fp = int(rows["match_status"].eq("deleted").sum())
    fn = int((rows["match_status"].eq("created") &
              ~rows["is_annotator_note"]).sum())
    precision = tp / (tp + fp) if tp + fp else np.nan
    recall = tp / (tp + fn) if tp + fn else np.nan
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else np.nan
    return {"tp": tp, "fp": fp, "fn": fn, "precision": precision,
            "recall": recall, "f1": f1}


metrics_micro = pd.DataFrame([
    {"layer": layer, **metric_counts(rows)}
    for layer, rows in reviewed_spans.groupby("layer")
])
metrics_micro.to_csv(
    OUTPUT / "metrics_micro.csv", index=False, lineterminator="\n")
display(metrics_micro)

        layer  excluded_annotator_notes
0    evidence                        11
1  photometry                        36

        layer    tp  fp   fn  precision    recall        f1
0    evidence  4814   5  102   0.998962  0.979251  0.989009
1  photometry  1942   0   93   1.000000  0.954300  0.976616

In [9]:
annotator_metric_rows = []
for (annotator, layer), rows in reviewed_spans.groupby(["annotator", "layer"]):
    annotator_metric_rows.append({"annotator": annotator, "layer": layer,
                                  **metric_counts(rows)})
metrics_by_annotator = pd.DataFrame(annotator_metric_rows).merge(
    per_annotator_profile[["annotator", "layer", "n_corrected"]],
    on=["annotator", "layer"], validate="one_to_one")
metrics_by_annotator["zero_corrections"] = metrics_by_annotator["n_corrected"].eq(0)
metrics_by_annotator = metrics_by_annotator.sort_values(
    ["layer", "f1", "annotator"]).reset_index(drop=True)
metrics_by_annotator.to_csv(
    OUTPUT / "metrics_by_annotator.csv", index=False, lineterminator="\n")
display(metrics_by_annotator)

        annotator       layer   tp  fp  fn  precision    recall        f1  n_corrected  zero_corrections
0   Priyadarshini    evidence  574   0  40   1.000000  0.934853  0.966330           44             False
1           Eslam    evidence  462   0  15   1.000000  0.968553  0.984026           13             False
2          Dahlia    evidence  559   0  18   1.000000  0.968804  0.984155           35             False
3         Camille    evidence  663   5   7   0.992515  0.989552  0.991031           42             False
4           Sarah    evidence  587   0  10   1.000000  0.983250  0.991554           32             False
5          Zhanat    evidence  531   0   5   1.000000  0.990672  0.995314           43             False
6          Yodgor    evidence  501   0   4   1.000000  0.992079  0.996024            0              True
7         Patrice    evidence  342   0   2   1.000000  0.994186  0.997085           15             False
8          Xinyue    evidence  358   0   1   1.000000  0.997214  0.998605            0              True
9          Andrii    evidence  237   0   0   1.000000  1.000000  1.000000            0              True
10  Priyadarshini  photometry   98   0  19   1.000000  0.837607  0.911628           83             False
11         Yodgor  photometry  135   0  23   1.000000  0.854430  0.921502            4             False
12        Camille  photometry  194   0  20   1.000000  0.906542  0.950980           88             False
13         Dahlia  photometry  141   0  12   1.000000  0.921569  0.959184          131             False
14         Zhanat  photometry  125   0  10   1.000000  0.925926  0.961538           67             False
15          Sarah  photometry  396   0   6   1.000000  0.985075  0.992481          249             False
16        Patrice  photometry  119   0   1   1.000000  0.991667  0.995816           26             False
17          Eslam  photometry  314   0   2   1.000000  0.993671  0.996825            3             False
18         Andrii  photometry  266   0   0   1.000000  1.000000  1.000000            0              True
19         Xinyue  photometry  154   0   0   1.000000  1.000000  1.000000            0              True

In [10]:
category_metric_rows = []
for layer, rows in reviewed_spans.groupby("layer"):
    category_column = "label" if layer == "evidence" else "measurement_type"
    item_key = ["document_name", "begin", "end", "span_index"]
    baseline = TABLES[layer].loc[
        TABLES[layer]["layer_source"].eq("INITIAL_CAS"),
        item_key + [category_column]].rename(
            columns={category_column: "baseline_category"})
    categorized = rows.merge(baseline, on=item_key, how="left", validate="many_to_one")
    categorized["evaluation_category"] = np.where(
        categorized["match_status"].eq("created"),
        categorized[category_column], categorized["baseline_category"])
    categorized["evaluation_category"] = categorized[
        "evaluation_category"].fillna("<UNSET>")
    for category, category_rows in categorized.groupby("evaluation_category"):
        counts = metric_counts(category_rows)
        support = counts["tp"] + counts["fp"] + counts["fn"]
        category_metric_rows.append({
            "layer": layer, "category": category, "support": support,
            "interpretable": support >= 20, **counts,
        })
metrics_by_category = pd.DataFrame(category_metric_rows).sort_values(
    ["layer", "f1", "category"], na_position="first").reset_index(drop=True)
metrics_by_category.to_csv(
    OUTPUT / "metrics_by_category.csv", index=False, lineterminator="\n")
display(metrics_by_category)

         layer                       category  support  interpretable    tp  fp  fn  precision    recall        f1
0     evidence                        <UNSET>        3          False     0   0   3        NaN  0.000000       NaN
1     evidence                   LOCALIZATION      257           True   221   2  34   0.991031  0.866667  0.924686
2     evidence             TRIGGER_INSTRUMENT      433           True   411   0  22   1.000000  0.949192  0.973934
3     evidence               REDSHIFT_CONTEXT       20           True    19   0   1   1.000000  0.950000  0.974359
4     evidence                 REDSHIFT_EVENT      145           True   139   0   6   1.000000  0.958621  0.978873
5     evidence                   TRIGGER_TIME      219           True   212   2   5   0.990654  0.976959  0.983759
6     evidence        COUNTERPART_ASSOCIATION      509           True   495   0  14   1.000000  0.972495  0.986056
7     evidence                   SPECTROSCOPY      116           True   113   0   3   1.000000  0.974138  0.986900
8     evidence           HIGH_ENERGY_PROPERTY      439           True   430   0   9   1.000000  0.979499  0.989643
9     evidence  CLASSIFICATION_INTERPRETATION      108           True   107   0   1   1.000000  0.990741  0.995349
10    evidence           LIGHTCURVE_EVOLUTION      381           True   378   0   3   1.000000  0.992126  0.996047
11    evidence                 EVENT_IDENTITY     2158           True  2156   1   1   0.999536  0.999536  0.999536
12    evidence               DURATION_GENERAL       33           True    33   0   0   1.000000  1.000000  1.000000
13    evidence                   HOST_CONTEXT       17          False    17   0   0   1.000000  1.000000  1.000000
14    evidence             NEGATIVE_STATEMENT        9          False     9   0   0   1.000000  1.000000  1.000000
15    evidence                            T90       74           True    74   0   0   1.000000  1.000000  1.000000
16  photometry                        <UNSET>        6          False     0   0   6        NaN  0.000000       NaN
17  photometry                      detection     1608           True  1529   0  79   1.000000  0.950871  0.974817
18  photometry                    upper_limit      421           True   413   0   8   1.000000  0.980998  0.990408

## 4b. Declared rejections: a lower bound on precision

### 4b.1 Signal A: certainty changed to `rejected`

Signal A requires an exact matched pair with `match_status == "corrected"`,
`"certainty"` in the parsed `changed_fields`, a baseline certainty other than
`rejected`, and an annotator certainty equal to `rejected`. The test reads only
structured span columns; no free-text comment is loaded or classified.

In [11]:
ITEM_KEY = ["document_name", "begin", "end", "span_index"]
declared_pair_frames = []
for layer, frame in TABLES.items():
    category_column = "label" if layer == "evidence" else "measurement_type"
    baseline = frame.loc[
        frame["layer_source"].eq("INITIAL_CAS"),
        ITEM_KEY + [category_column, "certainty", "covered_text"],
    ].rename(columns={
        category_column: "baseline_category",
        "certainty": "baseline_certainty",
        "covered_text": "baseline_text",
    })
    matched = reviewed_spans.loc[
        reviewed_spans["layer"].eq(layer)
        & reviewed_spans["match_status"].isin(["accepted", "corrected"])
    ].copy()
    matched = matched.rename(columns={category_column: "annotator_category"})
    paired = matched.merge(baseline, on=ITEM_KEY, how="left", validate="many_to_one")
    paired["signal_a"] = (
        paired["match_status"].eq("corrected")
        & paired["parsed_changed_fields"].map(lambda fields: "certainty" in fields)
        & paired["baseline_certainty"].fillna("").ne("rejected")
        & paired["certainty"].fillna("").eq("rejected")
    )
    annotator_blank = (paired["annotator_category"].isna()
                       | paired["annotator_category"].astype("string").str.strip().eq(""))
    baseline_present = (paired["baseline_category"].notna()
                        & paired["baseline_category"].astype("string").str.strip().ne(""))
    paired["signal_b"] = (baseline_present & ~paired["has_category"].fillna(False)
                           & annotator_blank)
    declared_pair_frames.append(paired)

declared_pairs = pd.concat(declared_pair_frames, ignore_index=True, sort=False)
signal_a_rows = declared_pairs.loc[declared_pairs["signal_a"]].copy()
signal_b_rows = declared_pairs.loc[declared_pairs["signal_b"]].copy()
declared_rows = declared_pairs.loc[
    declared_pairs[["signal_a", "signal_b"]].any(axis=1)].copy()
declared_rows["signals"] = declared_rows.apply(
    lambda row: "+".join(name for name, hit in
                         [("A", row["signal_a"]), ("B", row["signal_b"])] if hit), axis=1)
declared_export = declared_rows[[
    "signals", "layer", "document_name", "annotator", "begin", "end",
    "span_index", "baseline_category", "annotator_category", "baseline_text",
    "baseline_certainty", "certainty", "match_status", "has_category",
]].sort_values(["layer", "document_name", "annotator", "begin", "end"])
declared_export.to_csv(
    OUTPUT / "declared_rejections.csv", index=False, lineterminator="\n")

signal_a_by_layer = (signal_a_rows.groupby("layer").size()
                     .reindex(["evidence", "photometry"], fill_value=0)
                     .reset_index(name="signal_a"))
signal_a_by_annotator = (signal_a_rows.groupby(["layer", "annotator"]).size()
                         .reset_index(name="signal_a"))
signal_a_by_category = (signal_a_rows.groupby(["layer", "baseline_category"]).size()
                        .reset_index(name="signal_a"))
signal_a_listing = signal_a_rows[[
    "document_name", "annotator", "layer", "baseline_category", "baseline_text",
    "baseline_certainty", "certainty",
]].rename(columns={"baseline_category": "label_or_measurement_type",
                   "baseline_text": "span_text",
                   "certainty": "annotator_certainty"})
display(signal_a_by_layer)
display(signal_a_by_annotator)
display(signal_a_by_category)
display(signal_a_listing)
print(f"Declared rejection rows exported: {len(declared_export)}")

        layer  signal_a
0    evidence        14
1  photometry         0

      layer annotator  signal_a
0  evidence   Camille        14

      layer   baseline_category  signal_a
0  evidence        LOCALIZATION         1
1  evidence  TRIGGER_INSTRUMENT        11
2  evidence        TRIGGER_TIME         2

                    document_name annotator     layer label_or_measurement_type                  span_text baseline_certainty annotator_certainty
2125  event_GCN-251222_170549.xmi   Camille  evidence        TRIGGER_INSTRUMENT               SVOM/ECLAIRs          confirmed            rejected
2128  event_GCN-251222_170549.xmi   Camille  evidence        TRIGGER_INSTRUMENT                   SVOM/GRM          confirmed            rejected
2132  event_GCN-251222_170549.xmi   Camille  evidence        TRIGGER_INSTRUMENT               SVOM/ECLAIRs          confirmed            rejected
2133  event_GCN-251222_170549.xmi   Camille  evidence              TRIGGER_TIME    2025-12-22T17:05:46 UTC          confirmed            rejected
2142  event_GCN-251222_170549.xmi   Camille  evidence        TRIGGER_INSTRUMENT               SVOM/ECLAIRs          confirmed            rejected
2280  event_GCN-251222_170549.xmi   Camille  evidence        TRIGGER_INSTRUMENT               SVOM ECLAIRs          confirmed            rejected
2281  event_GCN-251222_170549.xmi   Camille  evidence        TRIGGER_INSTRUMENT                        GRM          confirmed            rejected
2330  event_GCN-251222_170549.xmi   Camille  evidence        TRIGGER_INSTRUMENT               SVOM/ECLAIRs          confirmed            rejected
3043  event_GRB-241025_013651.xmi   Camille  evidence              LOCALIZATION  uncertainty of 4.8 arcsec          confirmed            rejected
3514        event_GRB-260708A.xmi   Camille  evidence        TRIGGER_INSTRUMENT                  Fermi-LAT          confirmed            rejected
3523        event_GRB-260708A.xmi   Camille  evidence              TRIGGER_TIME     2026-07-08 22:40:00 UT          confirmed            rejected
3536        event_GRB-260708A.xmi   Camille  evidence        TRIGGER_INSTRUMENT                      GECAM          confirmed            rejected
3540        event_GRB-260708A.xmi   Camille  evidence        TRIGGER_INSTRUMENT                  Fermi/LAT          confirmed            rejected
3551        event_GRB-260708A.xmi   Camille  evidence        TRIGGER_INSTRUMENT                  Fermi/LAT          confirmed            rejected

Declared rejection rows exported: 20

### 4b.2 Signal B: category cleared

Signal B is an `accepted` or `corrected` matched pair whose baseline category is
non-null and non-blank, while the annotator row has both
`has_category.fillna(False) == False` and a null or blank category feature. The category
feature is `label` for evidence and `measurement_type` for photometry.

In [12]:
signal_b_by_layer = (signal_b_rows.groupby("layer").size()
                     .reindex(["evidence", "photometry"], fill_value=0)
                     .reset_index(name="signal_b"))
signal_b_by_annotator = (signal_b_rows.groupby(["layer", "annotator"]).size()
                         .reset_index(name="signal_b"))
signal_b_listing = signal_b_rows[[
    "document_name", "annotator", "layer", "baseline_category", "baseline_text",
    "annotator_category", "has_category", "match_status",
]].rename(columns={"baseline_category": "label_or_measurement_type",
                   "baseline_text": "span_text"})
signal_overlap = declared_pairs.loc[
    declared_pairs["signal_a"] & declared_pairs["signal_b"]]
display(signal_b_by_layer)
display(signal_b_by_annotator)
display(signal_b_listing)
print(f"Signal A/B overlap: {len(signal_overlap)}")
print(f"Deduplicated declared rejections: {len(declared_rows)}")

        layer  signal_b
0    evidence         4
1  photometry         2

        layer annotator  signal_b
0    evidence   Camille         3
1    evidence     Sarah         1
2  photometry   Camille         1
3  photometry     Sarah         1

                    document_name annotator       layer label_or_measurement_type                                                                                                                span_text annotator_category  has_category match_status
2116  event_GCN-251222_170549.xmi   Camille    evidence              TRIGGER_TIME                                                                                               17:05:51 UT on 22 Dec 2025               None         False    corrected
2324  event_GCN-251222_170549.xmi   Camille    evidence            REDSHIFT_EVENT                                                                                                    redshift of z = 3.171               None         False    corrected
2703  event_GCN-260604_202037.xmi     Sarah    evidence            REDSHIFT_EVENT                                                                                                        z = 0.86 +/- 0.09               None         False    corrected
3143  event_GRB-241025_013651.xmi   Camille    evidence   COUNTERPART_ASSOCIATION                                                                                                        optical afterglow               None         False    corrected
4894            event_2025aji.xmi   Camille  photometry                 detection                                                                                            37.92       19.32   0.11    i               None         False    corrected
5958  event_GCN-251013_173943.xmi     Sarah  photometry               upper_limit     13347 | 2025-10-13 21:21:09 |         MASTER-SAAO | (23h 03m 02.87s , -00d 29m 15.8s) |   C |   120 | 19.9 |                       None         False    corrected

Signal A/B overlap: 0
Deduplicated declared rejections: 20

### 4b.3 Precision as a bounded interval

The upper bound retains Part 4's definition (`FP = deleted`). For the lower bound,
deduplicated Signal A and Signal B rows move from TP to FP:
`FP = deleted + declared rejection` and `TP = kept - declared rejection`.

In [13]:
def precision_bounds(rows, declared_count):
    upper = metric_counts(rows)
    lower_tp = upper["tp"] - declared_count
    lower_fp = upper["fp"] + declared_count
    lower_precision = lower_tp / (lower_tp + lower_fp) if lower_tp + lower_fp else np.nan
    return {
        "kept_upper": upper["tp"], "deleted": upper["fp"],
        "declared_rejections": declared_count,
        "precision_lower": lower_precision, "precision_upper": upper["precision"],
    }

layer_bounds = []
for layer, rows in reviewed_spans.groupby("layer"):
    n_declared = int(declared_rows["layer"].eq(layer).sum())
    layer_bounds.append({"layer": layer, **precision_bounds(rows, n_declared)})
precision_bounds_by_layer = pd.DataFrame(layer_bounds)

annotator_bounds = []
for (annotator, layer), rows in reviewed_spans.groupby(["annotator", "layer"]):
    n_declared = int((declared_rows["annotator"].eq(annotator)
                      & declared_rows["layer"].eq(layer)).sum())
    annotator_bounds.append({
        "annotator": annotator, "layer": layer,
        **precision_bounds(rows, n_declared),
    })
precision_bounds_by_annotator = pd.DataFrame(annotator_bounds).sort_values(
    ["layer", "annotator"]).reset_index(drop=True)
precision_bounds_by_layer.to_csv(
    OUTPUT / "precision_bounds.csv", index=False, lineterminator="\n")
precision_bounds_by_annotator.to_csv(
    OUTPUT / "precision_bounds_by_annotator.csv", index=False, lineterminator="\n")
display(precision_bounds_by_layer)
display(precision_bounds_by_annotator)

        layer  kept_upper  deleted  declared_rejections  precision_lower  precision_upper
0    evidence        4814        5                   18         0.995227         0.998962
1  photometry        1942        0                    2         0.998970         1.000000

        annotator       layer  kept_upper  deleted  declared_rejections  precision_lower  precision_upper
0          Andrii    evidence         237        0                    0         1.000000         1.000000
1         Camille    evidence         663        5                   17         0.967066         0.992515
2          Dahlia    evidence         559        0                    0         1.000000         1.000000
3           Eslam    evidence         462        0                    0         1.000000         1.000000
4         Patrice    evidence         342        0                    0         1.000000         1.000000
5   Priyadarshini    evidence         574        0                    0         1.000000         1.000000
6           Sarah    evidence         587        0                    1         0.998296         1.000000
7          Xinyue    evidence         358        0                    0         1.000000         1.000000
8          Yodgor    evidence         501        0                    0         1.000000         1.000000
9          Zhanat    evidence         531        0                    0         1.000000         1.000000
10         Andrii  photometry         266        0                    0         1.000000         1.000000
11        Camille  photometry         194        0                    1         0.994845         1.000000
12         Dahlia  photometry         141        0                    0         1.000000         1.000000
13          Eslam  photometry         314        0                    0         1.000000         1.000000
14        Patrice  photometry         119        0                    0         1.000000         1.000000
15  Priyadarshini  photometry          98        0                    0         1.000000         1.000000
16          Sarah  photometry         396        0                    1         0.997475         1.000000
17         Xinyue  photometry         154        0                    0         1.000000         1.000000
18         Yodgor  photometry         135        0                    0         1.000000         1.000000
19         Zhanat  photometry         125        0                    0         1.000000         1.000000

### 4b.4 Coverage of the structured signal

Coverage is counted across all assigned annotator names. Signal A and Signal B are
practices observed in the data, not campaign-wide rejection instructions.

In [14]:
all_annotators = set(assignments["annotator"].dropna().unique())
signal_a_annotators = set(signal_a_rows["annotator"])
signal_b_annotators = set(signal_b_rows["annotator"])
either_annotators = signal_a_annotators | signal_b_annotators
neither_annotators = all_annotators - either_annotators
signal_coverage = pd.DataFrame([
    {"coverage": "all assigned", "n_annotators": len(all_annotators),
     "annotators": ", ".join(sorted(all_annotators))},
    {"coverage": "Signal A", "n_annotators": len(signal_a_annotators),
     "annotators": ", ".join(sorted(signal_a_annotators))},
    {"coverage": "Signal B", "n_annotators": len(signal_b_annotators),
     "annotators": ", ".join(sorted(signal_b_annotators))},
    {"coverage": "either signal", "n_annotators": len(either_annotators),
     "annotators": ", ".join(sorted(either_annotators))},
    {"coverage": "neither signal", "n_annotators": len(neither_annotators),
     "annotators": ", ".join(sorted(neither_annotators))},
])
layer_signal_coverage = pd.DataFrame([
    {"layer": layer,
     "signal_a_annotators": signal_a_rows.loc[
         signal_a_rows["layer"].eq(layer), "annotator"].nunique(),
     "signal_b_annotators": signal_b_rows.loc[
         signal_b_rows["layer"].eq(layer), "annotator"].nunique()}
    for layer in ["evidence", "photometry"]
])
display(signal_coverage)
display(layer_signal_coverage)

         coverage  n_annotators                                                                             annotators
0    all assigned            10  Andrii, Camille, Dahlia, Eslam, Patrice, Priyadarshini, Sarah, Xinyue, Yodgor, Zhanat
1        Signal A             1                                                                                Camille
2        Signal B             2                                                                         Camille, Sarah
3   either signal             2                                                                         Camille, Sarah
4  neither signal             8                  Andrii, Dahlia, Eslam, Patrice, Priyadarshini, Xinyue, Yodgor, Zhanat

        layer  signal_a_annotators  signal_b_annotators
0    evidence                    1                    2
1  photometry                    0                    2

### 4b.5 Finding

The campaign had no structured field for recording that a pre-annotation should not
exist. Rejections were therefore left either in non-aggregable free-text comments or
improvised through existing schema fields such as `certainty`. Precision can only be
bounded, not measured: even the lower bound is incomplete because the guide did not
document `certainty=rejected` as a rejection mechanism and described photometry
certainty only as generally `confirmed`. The concrete requirement for a future campaign
is a dedicated rejection field, either a boolean or an explicitly reserved value,
rather than a free-text convention.

## 5. Where the extractor fails

Exact span pairing and structured feature changes are measured independently. Only
corrected rows containing at least one non-comment field enter the field analysis.

In [15]:
pairing_rows = []
for layer, rows in reviewed_spans.groupby("layer"):
    matched = int(rows["match_status"].isin(["accepted", "corrected"]).sum())
    deleted = int(rows["match_status"].eq("deleted").sum())
    pairing_rows.append({
        "layer": layer, "matched_baseline_spans": matched,
        "deleted_baseline_spans": deleted,
        "exact_baseline_span_pairing_rate": matched / (matched + deleted),
    })
pairing_rates = pd.DataFrame(pairing_rows)
pairing_rates.to_csv(
    OUTPUT / "pairing_rates.csv", index=False, lineterminator="\n")
display(pairing_rates)

        layer  matched_baseline_spans  deleted_baseline_spans  exact_baseline_span_pairing_rate
0    evidence                    4814                       5                          0.998962
1  photometry                    1942                       0                          1.000000

In [16]:
field_rows = []
matched_counts = (reviewed_spans.loc[
    reviewed_spans["match_status"].isin(["accepted", "corrected"])]
    .groupby("layer").size())
for layer, rows in corrected_rows.loc[
        corrected_rows["correction_kind"].eq("content")].groupby("layer"):
    field_counts = pd.Series([
        field
        for fields in rows["parsed_changed_fields"]
        for field in sorted(set(fields))
    ]).value_counts()
    for field, count in field_counts.items():
        field_rows.append({
            "layer": layer, "field": field, "rows_changed": int(count),
            "matched_pairs": int(matched_counts[layer]),
            "percent_of_matched_pairs": 100 * count / matched_counts[layer],
        })
field_change_rates = pd.DataFrame(field_rows).sort_values(
    ["layer", "rows_changed", "field"], ascending=[True, False, True])
field_change_rates.to_csv(
    OUTPUT / "field_change_rates.csv", index=False, lineterminator="\n")
display(field_change_rates)

         layer               field  rows_changed  matched_pairs  percent_of_matched_pairs
0     evidence             comment            44           4814                  0.914001
1     evidence           certainty            24           4814                  0.498546
2     evidence               value            15           4814                  0.311591
4     evidence               label             9           4814                  0.186955
3     evidence              target             9           4814                  0.186955
5     evidence                unit             3           4814                  0.062318
6   photometry             comment           298           1942                 15.345005
7   photometry          instrument           213           1942                 10.968074
8   photometry  photometric_system           131           1942                  6.745623
9   photometry  obs_time_reference           124           1942                  6.385170
10  photometry        obs_time_raw            69           1942                  3.553038
11  photometry   exposure_time_raw            39           1942                  2.008239
12  photometry    photometric_band            34           1942                  1.750772
13  photometry       obs_time_type            33           1942                  1.699279
14  photometry     magnitude_error            15           1942                  0.772400
15  photometry           certainty            11           1942                  0.566426
16  photometry        timezone_raw             7           1942                  0.360453
17  photometry              target             3           1942                  0.154480
18  photometry    measurement_type             2           1942                  0.102987
19  photometry         limit_sigma             1           1942                  0.051493

Exact baseline-span pairing is **99.90%** for evidence and **100%** for photometry.
Among evidence content corrections, `certainty` differs on 24 of 4,814 matched pairs
(**0.50%**), `value` on 15 (**0.31%**), and `label` and `target` on 9 each
(**0.19%**). Photometry attributes change much more often: `instrument` on 213 of
1,942 pairs (**10.97%**), `photometric_system` on 131 (**6.75%**), and
`obs_time_reference` on 124 (**6.39%**). Thus the extractor places spans almost
perfectly but fills some photometry fields less reliably. Comment changes that
accompany content corrections remain counted, but their text is not interpreted.

## 6. Inter-annotator agreement

One item is one baseline span identified by
`(document_name, begin, end, span_index)`. Its value is the annotator's final nominal
value for the feature. Deletions are the explicit category `<DELETED>`; null and empty
final values remain visible as `<NULL>` and `<EMPTY>`.

The `krippendorff` package is not installed in the project environment, so nominal
alpha is implemented directly below using Krippendorff's coincidence matrix.

In [17]:
print(f"krippendorff package installed: {importlib.util.find_spec('krippendorff') is not None}")


def final_nominal_value(row, feature):
    if row.match_status == "deleted":
        return "<DELETED>"
    value = getattr(row, feature)
    if pd.isna(value):
        return "<NULL>"
    if isinstance(value, str) and value == "":
        return "<EMPTY>"
    return str(value)


def nominal_alpha(ratings):
    groups = [group["value"].tolist()
              for _, group in ratings.groupby("item", sort=False)
              if len(group) >= 2]
    if not groups:
        return {"alpha": np.nan, "raw_agreement": np.nan, "n_items": 0,
                "n_annotators": ratings["annotator"].nunique(),
                "agreeing_pairs": 0, "disagreeing_pairs": 0,
                "category_distribution": "{}",
                "degenerate_reason": "no item has 2 ratings"}
    categories = sorted({value for values in groups for value in values})
    category_index = {value: index for index, value in enumerate(categories)}
    coincidence = np.zeros((len(categories), len(categories)), dtype=float)
    agreeing_pairs = 0
    all_pairs = 0
    for values in groups:
        n_values = len(values)
        counts = pd.Series(values).value_counts()
        all_pairs += n_values * (n_values - 1) // 2
        agreeing_pairs += sum(int(count * (count - 1) // 2) for count in counts)
        for first, n_first in counts.items():
            for second, n_second in counts.items():
                coincidence[category_index[first], category_index[second]] += (
                    n_first * (n_second - (first == second)) / (n_values - 1))
    total = coincidence.sum()
    observed_disagreement = (total - np.trace(coincidence)) / total
    marginals = coincidence.sum(axis=1)
    expected_disagreement = (
        (total * total - np.square(marginals).sum()) / (total * (total - 1))
        if total > 1 else np.nan)
    if expected_disagreement == 0:
        alpha = np.nan
        reason = "no expected disagreement: all usable ratings have one category"
    else:
        alpha = 1 - observed_disagreement / expected_disagreement
        reason = ""
    distribution = pd.Series(
        [value for values in groups for value in values]
    ).value_counts().sort_index().to_dict()
    return {
        "alpha": alpha, "raw_agreement": agreeing_pairs / all_pairs,
        "n_items": len(groups), "n_annotators": ratings["annotator"].nunique(),
        "agreeing_pairs": agreeing_pairs,
        "disagreeing_pairs": all_pairs - agreeing_pairs,
        "category_distribution": json.dumps(distribution, sort_keys=True),
        "degenerate_reason": reason,
    }


AGREEMENT_FEATURES = {
    "evidence": ["label", "certainty"],
    "photometry": ["measurement_type", "instrument", "photometric_system",
                   "obs_time_reference"],
}
alpha_rows = []
for layer, features in AGREEMENT_FEATURES.items():
    layer_rows = reviewed_spans.loc[
        reviewed_spans["layer"].eq(layer) &
        reviewed_spans["match_status"].isin(["accepted", "corrected", "deleted"])
    ].copy()
    layer_rows["item"] = (
        layer_rows["document_name"] + "|" + layer_rows["begin"].astype(str) + "|" +
        layer_rows["end"].astype(str) + "|" + layer_rows["span_index"].astype(str))
    active_names = active_annotators[layer]
    for feature in features:
        ratings = layer_rows.copy()
        ratings["value"] = [final_nominal_value(row, feature)
                            for row in ratings.itertuples()]
        perimeters = {
            "full": ratings,
            "restricted": ratings.loc[ratings["annotator"].isin(active_names)],
        }
        documents_for_layer = sorted(ratings["document_name"].unique())
        for perimeter_name, perimeter_rows in perimeters.items():
            for document_name in documents_for_layer + ["POOLED"]:
                selected = (perimeter_rows if document_name == "POOLED" else
                            perimeter_rows.loc[
                                perimeter_rows["document_name"].eq(document_name)])
                alpha_rows.append({
                    "perimeter": perimeter_name, "layer": layer,
                    "feature": feature, "document_name": document_name,
                    **nominal_alpha(selected[["item", "annotator", "value"]]),
                })
alpha_results = pd.DataFrame(alpha_rows)
alpha_results.to_csv(
    OUTPUT / "krippendorff_alpha.csv", index=False, lineterminator="\n")
print("Annotators retained by the restricted perimeter:")
for layer, names in active_annotators.items():
    excluded = sorted(set(per_annotator_profile.loc[
        per_annotator_profile["layer"].eq(layer), "annotator"]) - names)
    print(f"{layer}: retained={len(names)}; excluded={', '.join(excluded)}")
display(alpha_results.loc[alpha_results["perimeter"].eq("full")])
display(alpha_results.loc[alpha_results["perimeter"].eq("restricted")])

krippendorff package installed: False

Annotators retained by the restricted perimeter:
evidence: retained=7; excluded=Andrii, Xinyue, Yodgor
photometry: retained=8; excluded=Andrii, Xinyue

,perimeter,layer,feature,document_name,alpha,raw_agreement,n_items,n_annotators,agreeing_pairs,disagreeing_pairs,category_distribution,degenerate_reason
0,full,evidence,label,event_2025aji.xmi,0.981968,0.986733,201,3,595,8,"{""<DELETED>"": 4, ""CLASSIFICATION_INTERPRETATION"": 3, ""COUNTERPART_ASSOCIATION"": 75, ""EVENT_IDENTITY"": 284, ""HIGH_ENERGY_PROPERTY"": 36, ""LIGHTCURVE_EVOLUTION"": 81, ""LOCALIZATION"": 25, ""NEGATIVE_STATEMENT"": 3, ""REDSHIFT_CONTEXT"": 9, ""REDSHIFT_EVENT"": 15, ""SPECTROSCOPY"": 24, ""T90"": 3, ""TRIGGER_INSTRUMENT"": 21, ""TRIGGER_TIME"": 20}",
1,full,evidence,label,event_2026owq.xmi,1.000000,1.000000,204,3,612,0,"{""CLASSIFICATION_INTERPRETATION"": 21, ""COUNTERPART_ASSOCIATION"": 66, ""EVENT_IDENTITY"": 309, ""HIGH_ENERGY_PROPERTY"": 42, ""HOST_CONTEXT"": 3, ""LIGHTCURVE_EVOLUTION"": 75, ""LOCALIZATION"": 15, ""REDSHIFT_CONTEXT"": 3, ""REDSHIFT_EVENT"": 21, ""SPECTROSCOPY"": 24, ""T90"": 6, ""TRIGGER_INSTRUMENT"": 15, ""TRIGGER_TIME"": 12}",
2,full,evidence,label,event_EP-260623_025405.xmi,1.000000,1.000000,96,2,96,0,"{""CLASSIFICATION_INTERPRETATION"": 2, ""COUNTERPART_ASSOCIATION"": 24, ""DURATION_GENERAL"": 4, ""EVENT_IDENTITY"": 82, ""HIGH_ENERGY_PROPERTY"": 16, ""LIGHTCURVE_EVOLUTION"": 18, ""LOCALIZATION"": 12, ""REDSHIFT_EVENT"": 14, ""SPECTROSCOPY"": 4, ""TRIGGER_INSTRUMENT"": 8, ""TRIGGER_TIME"": 8}",
3,full,evidence,label,event_GCN-251013_173943.xmi,1.000000,1.000000,237,3,711,0,"{""CLASSIFICATION_INTERPRETATION"": 18, ""COUNTERPART_ASSOCIATION"": 90, ""DURATION_GENERAL"": 3, ""EVENT_IDENTITY"": 333, ""HIGH_ENERGY_PROPERTY"": 33, ""LIGHTCURVE_EVOLUTION"": 69, ""LOCALIZATION"": 30, ""REDSHIFT_EVENT"": 27, ""SPECTROSCOPY"": 9, ""T90"": 12, ""TRIGGER_INSTRUMENT"": 54, ""TRIGGER_TIME"": 33}",
4,full,evidence,label,event_GCN-251222_170549.xmi,0.979171,0.983471,242,2,238,4,"{""<NULL>"": 2, ""CLASSIFICATION_INTERPRETATION"": 6, ""COUNTERPART_ASSOCIATION"": 48, ""DURATION_GENERAL"": 4, ""EVENT_IDENTITY"": 192, ""HIGH_ENERGY_PROPERTY"": 56, ""LIGHTCURVE_EVOLUTION"": 36, ""LOCALIZATION"": 22, ""NEGATIVE_STATEMENT"": 2, ""REDSHIFT_CONTEXT"": 2, ""REDSHIFT_EVENT"": 13, ""SPECTROSCOPY"": 8, ""T90"": 6, ""TRIGGER_INSTRUMENT"": 60, ""TRIGGER_TIME"": 27}",
5,full,evidence,label,event_GCN-260604_202037.xmi,0.991032,0.993151,146,2,145,1,"{""<NULL>"": 1, ""CLASSIFICATION_INTERPRETATION"": 10, ""COUNTERPART_ASSOCIATION"": 18, ""DURATION_GENERAL"": 4, ""EVENT_IDENTITY"": 128, ""HIGH_ENERGY_PROPERTY"": 44, ""HOST_CONTEXT"": 2, ""LIGHTCURVE_EVOLUTION"": 18, ""LOCALIZATION"": 12, ""REDSHIFT_EVENT"": 5, ""T90"": 8, ""TRIGGER_INSTRUMENT"": 30, ""TRIGGER_TIME"": 12}",
6,full,evidence,label,event_GCN-260614_134953.xmi,1.000000,1.000000,73,2,73,0,"{""CLASSIFICATION_INTERPRETATION"": 6, ""COUNTERPART_ASSOCIATION"": 4, ""EVENT_IDENTITY"": 40, ""HIGH_ENERGY_PROPERTY"": 16, ""LIGHTCURVE_EVOLUTION"": 2, ""LOCALIZATION"": 18, ""T90"": 10, ""TRIGGER_INSTRUMENT"": 34, ""TRIGGER_TIME"": 16}",
7,full,evidence,label,event_GRB-241025_013651.xmi,0.988700,0.991507,157,3,467,4,"{""<DELETED>"": 1, ""<NULL>"": 1, ""CLASSIFICATION_INTERPRETATION"": 9, ""COUNTERPART_ASSOCIATION"": 29, ""DURATION_GENERAL"": 6, ""EVENT_IDENTITY"": 216, ""HIGH_ENERGY_PROPERTY"": 63, ""LIGHTCURVE_EVOLUTION"": 15, ""LOCALIZATION"": 27, ""REDSHIFT_CONTEXT"": 3, ""REDSHIFT_EVENT"": 12, ""SPECTROSCOPY"": 12, ""T90"": 9, ""TRIGGER_INSTRUMENT"": 45, ""TRIGGER_TIME"": 23}",
8,full,evidence,label,event_GRB-260708A.xmi,0.982117,0.985294,68,4,402,6,"{""CLASSIFICATION_INTERPRETATION"": 12, ""COUNTERPART_ASSOCIATION"": 28, ""DURATION_GENERAL"": 4, ""EVENT_IDENTITY"": 96, ""HIGH_ENERGY_PROPERTY"": 26, ""LIGHTCURVE_EVOLUTION"": 18, ""LOCALIZATION"": 16, ""SPECTROSCOPY"": 4, ""T90"": 8, ""TRIGGER_INSTRUMENT"": 36, ""TRIGGER_TIME"": 24}",
9,full,evidence,label,event_GRB241030.xmi,0.997428,0.998069,259,4,1551,3,"{""CLASSIFICATION_INTERPRETATION"": 20, ""COUNTERPART_ASSOCIATION"": 112, ""DURATION_GENERAL"": 8, ""EVENT_IDENTITY"": 476, ""HIGH_ENERGY_PROPERTY"": 100, ""HOST_CONTEXT"": 12, ""LIGHTCURVE_EVOLUTION"": 44, ""LOCALIZATION"": 44, ""NEGATIVE_STATEMENT"": 4, ""REDSHIFT_CONTEXT"": 3, ""REDSHIFT_EVENT"": 29, ""SPECTROSCOPY"": 28, ""T90"": 12, ""TRIGGER_INSTRUMENT"": 108, ""TRIGGER_TIME"": 36}",
10,full,evidence,label,POOLED,0.992374,0.994711,1683,10,4890,26,"{""<DELETED>"": 5, ""<NULL>"": 4, ""CLASSIFICATION_INTERPRETATION"": 107, ""COUNTERPART_ASSOCIATION"": 494, ""DURATION_GENERAL"": 33, ""EVENT_IDENTITY"": 2156, ""HIGH_ENERGY_PROPERTY"": 432, ""HOST_CONTEXT"": 17, ""LIGHTCURVE_EVOLUTION"": 376, ""LOCALIZATION"": 221, ""NEGATIVE_STATEMENT"": 9, ""REDSHIFT_CONTEXT"": 20, ""REDSHIFT_EVENT"": 136, ""SPECTROSCOPY"": 113, ""T90"": 74, ""TRIGGER_INSTRUMENT"": 411, ""TRIGGER_TIME"": 211}",
22,full,evidence,certainty,event_2025aji.xmi,0.899456,0.976783,201,3,589,14,"{""<DELETED>"": 4, ""candidate"": 72, ""confirmed"": 524, ""tentative"": 3}",
23,full,evidence,certainty,event_2026owq.xmi,1.000000,1.000000,204,3,612,0,"{""candidate"": 66, ""confirmed"": 516, ""rejected"": 6, ""tentative"": 21, ""unclear"": 3}",
24,full,evidence,certainty,event_EP-260623_025405.xmi,1.000000,1.000000,96,2,96,0,"{""candidate"": 24, ""confirmed"": 164, ""tentative"": 4}",
25,full,evidence,certainty,event_GCN-251013_173943.xmi,1.000000,1.000000,237,3,711,0,"{""candidate"": 90, ""confirmed"": 600, ""tentative"": 21}",
26,full,evidence,certainty,event_GCN-251222_170549.xmi,0.811080,0.954545,242,2,231,11,"{""candidate"": 48, ""confirmed"": 419, ""rejected"": 8, ""tentative"": 9}",
27,full,evidence,certainty,event_GCN-260604_202037.xmi,1.000000,1.000000,146,2,146,0,"{""candidate"": 18, ""confirmed"": 264, ""tentative"": 8, ""unclear"": 2}",
28,full,evidence,certainty,event_GCN-260614_134953.xmi,1.000000,1.000000,73,2,73,0,"{""candidate"": 4, ""confirmed"": 134, ""tentative"": 8}",
29,full,evidence,certainty,event_GRB-241025_013651.xmi,0.951126,0.991507,157,3,467,4,"{""<DELETED>"": 1, ""candidate"": 30, ""confirmed"": 427, ""rejected"": 1, ""tentative"": 12}",
30,full,evidence,certainty,event_GRB-260708A.xmi,0.862785,0.963235,68,4,393,15,"{""candidate"": 28, ""confirmed"": 231, ""rejected"": 5, ""tentative"": 8}",
31,full,evidence,certainty,event_GRB241030.xmi,0.971698,0.992278,259,4,1542,12,"{""candidate"": 109, ""confirmed"": 876, ""rejected"": 4, ""tentative"": 37, ""unclear"": 10}",
32,full,evidence,certainty,POOLED,0.950989,0.988609,1683,10,4860,56,"{""<DELETED>"": 5, ""candidate"": 489, ""confirmed"": 4155, ""rejected"": 24, ""tentative"": 131, ""unclear"": 15}",
44,full,photometry,measurement_type,event_2025aji.xmi,0.987430,0.993884,109,3,325,2,"{""<NULL>"": 1, ""detection"": 194, ""upper_limit"": 132}",
45,full,photometry,measurement_type,event_2026owq.xmi,1.000000,1.000000,68,3,204,0,"{""detection"": 198, ""upper_limit"": 6}",
46,full,photometry,measurement_type,event_EP-260623_025405.xmi,1.000000,1.000000,19,2,19,0,"{""detection"": 36, ""upper_limit"": 2}",
47,full,photometry,measurement_type,event_GCN-251013_173943.xmi,0.986730,0.997494,266,3,796,2,"{""<NULL>"": 1, ""detection"": 714, ""upper_limit"": 83}",
48,full,photometry,measurement_type,event_GCN-251222_170549.xmi,1.000000,1.000000,37,2,37,0,"{""detection"": 66, ""upper_limit"": 8}",
49,full,photometry,measurement_type,event_GCN-260604_202037.xmi,1.000000,1.000000,62,2,62,0,"{""detection"": 54, ""upper_limit"": 70}",
50,full,photometry,measurement_type,event_GCN-260614_134953.xmi,NaN,1.000000,7,2,7,0,"{""detection"": 14}",no expected disagreement: all usable ratings have one category
51,full,photometry,measurement_type,event_GRB-241025_013651.xmi,1.000000,1.000000,45,3,135,0,"{""detection"": 60, ""upper_limit"": 75}",
52,full,photometry,measurement_type,event_GRB-260708A.xmi,NaN,1.000000,3,4,18,0,"{""detection"": 12}",no expected disagreement: all usable ratings have one category
53,full,photometry,measurement_type,event_GRB241030.xmi,1.000000,1.000000,54,4,324,0,"{""detection"": 180, ""upper_limit"": 36}",
54,full,photometry,measurement_type,POOLED,0.993871,0.997929,670,10,1927,4,"{""<NULL>"": 2, ""detection"": 1528, ""upper_limit"": 412}",
66,full,photometry,instrument,event_2025aji.xmi,0.692544,0.767584,109,3,251,76,"{""1m-PicduMidi"": 3, ""7DT"": 15, ""<EMPTY>"": 118, ""AS-32"": 3, ""AZT-33IK"": 9, ""AbAO-T70"": 3, ""C-GFT"": 3, ""COLIBRI"": 2, ""ESO/Rem60cm"": 2, ""KAO"": 3, ""KNC"": 3, ""LCO/Sinistro"": 2, ""LCOGT"": 1, ""MASTER"": 9, ""MASTER-OAFA"": 108, ""Mistral"": 1, ""NAO-2m"": 3, ""NOT/ALFOSC"": 2, ""PROMPT-5"": 9, ""PROMPT-6"": 9, ""PROMPT-MO"": 6, ""TNOT"": 3, ""UVOT"": 9, ""VLT"": 1}",
67,full,photometry,instrument,event_2026owq.xmi,-0.066126,0.784314,68,3,160,44,"{""<EMPTY>"": 182, ""ALFOSC"": 8, ""ATLAS"": 4, ""COLIBRI"": 5, ""GOTO"": 2, ""SAO RAS"": 1, ""Terskol"": 2}",
68,full,photometry,instrument,event_EP-260623_025405.xmi,-0.143488,0.263158,19,2,5,14,"{""<EMPTY>"": 22, ""COLIBRI"": 4, ""LOT"": 2, ""Liverpool telescope"": 4, ""REM 60 cm"": 1, ""TRT"": 1, ""VT"": 4}",
69,full,photometry,instrument,event_GCN-251013_173943.xmi,1.000000,1.000000,266,3,798,0,"{""<EMPTY>"": 657, ""CDK17 AITP"": 3, ""CrAO/ZTSh"": 3, ""Koshka/Ziess-1000"": 6, ""MASTER-SAAO"": 81, ""Mondy/AZT-33IK"": 24, ""Montarrenti Obs."": 3, ""SAO/Zeiss-1000"": 18, ""iT72"": 3}",
70,full,photometry,instrument,event_GCN-251222_170549.xmi,0.454796,0.486486,37,2,18,19,"{""1.6m Mephisto"": 6, ""<EMPTY>"": 11, ""AbAO/AS-32"": 2, ""COLIBRI"": 2, ""FTW"": 2, ""GOTO"": 2, ""LCO"": 1, ""MASTER"": 2, ""MASTER-Tunka"": 4, ""Mephisto"": 6, ""Mondy"": 2, ""NOT"": 1, ""NUTTelA-TAO"": 8, ""PRIME"": 2, ""SLT"": 2, ""SVOM/COLIBRI"": 2, ""TEC160FL"": 4, ""VLT/X-shooter"": 1, ""VT"": 6, ""ZTSH"": 2, ""ZTSH BVRI"": 2, ""iT72"": 4}",
71,full,photometry,instrument,event_GCN-260604_202037.xmi,1.000000,1.000000,62,2,62,0,"{""<EMPTY>"": 50, ""A1/CDK17"": 4, ""AITP/CDK17"": 2, ""MASTER"": 8, ""MASTER-Kislovodsk"": 20, ""MASTER-Tavrida"": 40}",
72,full,photometry,instrument,event_GCN-260614_134953.xmi,-0.857143,0.000000,7,2,0,7,"{""<EMPTY>"": 7, ""SVOM/VT"": 7}",
73,full,photometry,instrument,event_GRB-241025_013651.xmi,0.839184,0.881481,45,3,119,16,"{""<EMPTY>"": 58, ""AZT-33IK"": 1, ""COLIBRI"": 1, ""DDOTI"": 1, ""GROWTH-India"": 1, ""KNC"": 6, ""KNC-iT11"": 6, ""KNC-iT21"": 6, ""LBT"": 1, ""MASTER-Tunka"": 33, ""SAO RAS"": 1, ""TNOT"": 1, ""TRT"": 1, ""TRT-SRO"": 18}",
74,full,photometry,instrument,event_GRB-260708A.xmi,0.500000,0.666667,3,4,12,6,"{""<EMPTY>"": 6, ""LCO 1m"": 2, ""iT30"": 4}",
75,full,photometry,instrument,event_GRB241030.xmi,0.250070,0.425926,54,4,138,186,"{""<EMPTY>"": 99, ""AKO"": 1, ""C-GFT"": 2, ""COGT"": 1, ""COLIBRI"": 4, ""Global MASTER-NET"": 1, ""INAF"": 1, ""LCO"": 3, ""LCOGT"": 1, ""LOT"": 16, ""Las Cumbres"": 1, ""MASTER-Tavrida"": 25, ""MITSuME"": 1, ""MITSuME Akeno"": 1, ""Mephisto"": 12, ""Mondy"": 4, ""OHP"": 1, ""OHP/T193"": 1, ""SAO RAS"": 5, ""SVOM/C-GFT"": 3, ""SVOM/UVOT"": 9, ""SVOM/VT"": 2, ""Sinistro"": 2, ""Sun Yat-seen"": 1, ""Sun Yat-sen University 80cm infrared telescope"": 1, ""TNOT"": 3, ""TRT"": 2, ""ULL-ASTRO MASTER"": 1, ""ULL-ASTRO-MASTER"": 1, ""UVOT"": 9, ""VT"": 2}",
76,full,photometry,instrument,POOLED,0.706953,0.809425,670,10,1563,368,"{""1.6m Mephisto"": 6, ""1m-PicduMidi"": 3, ""7DT"": 15, ""<EMPTY>"": 1210, ""A1/CDK17"": 4, ""AITP/CDK17"": 2, ""AKO"": 1, ""ALFOSC"": 8, ""AS-32"": 3, ""ATLAS"": 4, ""AZT-33IK"": 10, ""AbAO-T70"": 3, ""AbAO/AS-32"": 2, ""C-GFT"": 5, ""CDK17 AITP"": 3, ""COGT"": 1, ""COLIBRI"": 18, ""CrAO/ZTSh"": 3, ""DDOTI"": 1, ""ESO/Rem60cm"": 2, ""FTW"": 2, ""GOTO"": 4, ""GROWTH-India"": 1, ""Global MASTER-NET"": 1, ""INAF"": 1, ""KAO"": 3, ""KNC"": 9, ""KNC-iT11"": 6, ""KNC-iT21"": 6, ""Koshka/Ziess-1000"": 6, ""LBT"": 1, ""LCO"": 4, ""LCO 1m"": 2, ""LCO/Sinistro"": 2, ""LCOGT"": 2, ""LOT"": 18, ""Las Cumbres"": 1, ""Liverpool telescope"": 4, ""MASTER"": 19, ""MASTER-Kislovodsk"": 20, ""MASTER-OAFA"": 108, ""MASTER-SAAO"": 81, ""MASTER-Tavrida"": 65, ""MASTER-Tunka"": 37, ""MITSuME"": 1, ""MITSuME Akeno"": 1, ""Mephisto"": 18, ""Mistral"": 1, ""Mondy"": 6, ""Mondy/AZT-33IK"": 24, ""Montarrenti Obs."": 3, ""NAO-2m"": 3, ""NOT"": 1, ""NOT/ALFOSC"": 2, ""NUTTelA-TAO"": 8, ""OHP"": 1, ""OHP/T193"": 1, ""PRIME"": 2, ""PROMPT-5"": 9, ""PROMPT-6"": 9, ""PROMPT-MO"": 6, ""REM 60 cm"": 1, ""SAO RAS"": 7, ""SAO/Zeiss-1000"": 18, ""SLT"": 2, ""SVOM/C-GFT"": 3, ""SVOM/COLIBRI"": 2, ""SVOM/UVOT"": 9, ""SVOM/VT"": 9, ""Sinistro"": 2, ""Sun Yat-seen"": 1, ""Sun Yat-sen University 80cm infrared telescope"": 1, ""TEC160FL"": 4, ""TNOT"": 7, ""TRT"": 4, ""TRT-SRO"": 18, ""Terskol"": 2, ""ULL-ASTRO MASTER"": 1, ""ULL-ASTRO-MASTER"": 1, ""UVOT"": 18, ""VLT"": 1, ""VLT/X-shooter"": 1, ""VT"": 12, ""ZTSH"": 2, ""ZTSH BVRI"": 2, ""iT30"": 4, ""iT72"": 7}",
88,full,photometry,photometric_system,event_2025aji.xmi,0.854644,0.920489,109,3,301,26,"{""AB"": 106, ""Vega"": 30, ""unknown"": 191}",
89,full,photometry,photometric_system,event_2026owq.xmi,0.395833,0.823529,68,3,168,36,"{""AB"": 168, ""unknown"": 36}",
90,full,photometry,photometric_system,event_EP-260623_025405.xmi,0.511013,0.842105,19,2,16,3,"{""AB"": 31, ""Vega"": 2, ""unknown"": 5}",
91,full,photometry,photometric_system,event_GCN-251013_173943.xmi,1.000000,1.000000,266,3,798,0,"{""AB"": 54, ""Vega"": 6, ""unknown"": 738}",
92,full,photometry,photometric_system,event_GCN-251222_170549.xmi,0.557576,0.810811,37,2,30,7,"{""AB"": 54, ""Vega"": 5, ""unknown"": 15}",
93,full,photometry,photometric_system,event_GCN-260604_202037.xmi,1.000000,1.000000,62,2,62,0,"{""AB"": 40, ""unknown"": 84}",
94,full,photometry,photometric_system,event_GCN-260614_134953.xmi,NaN,1.000000,7,2,7,0,"{""AB"": 14}",no expected disagreement: all usable ratings have one category
95,full,photometry,photometric_system,event_GRB-241025_013651.xmi,1.000000,1.000000,45,3,135,0,"{""AB"": 9, ""Vega"": 57, ""unknown"": 69}",
96,full,photometry,photometric_system,event_GRB-260708A.xmi,0.592593,0.777778,3,4,14,4,"{""AB"": 8, ""Vega"": 2, ""unknown"": 2}",
97,full,photometry,photometric_system,event_GRB241030.xmi,0.416956,0.623457,54,4,202,122,"{""AB"": 78, ""Vega"": 46, ""unknown"": 92}",
98,full,photometry,photometric_system,POOLED,0.831816,0.897462,670,10,1733,198,"{""AB"": 562, ""Vega"": 148, ""unknown"": 1232}",
110,full,photometry,obs_time_reference,event_2025aji.xmi,0.985205,0.993884,109,3,325,2,"{""absolute_time"": 90, ""observation_mid"": 1, ""trigger_time_t0"": 234, ""unknown"": 2}",
111,full,photometry,obs_time_reference,event_2026owq.xmi,0.198760,0.450980,68,3,92,112,"{""absolute_time"": 100, ""observation_mid"": 8, ""observation_start"": 30, ""trigger_time_t0"": 40, ""unknown"": 26}",
112,full,photometry,obs_time_reference,event_EP-260623_025405.xmi,0.132813,0.368421,19,2,7,12,"{""absolute_time"": 14, ""observation_mid"": 4, ""observation_start"": 8, ""trigger_time_t0"": 12}",
113,full,photometry,obs_time_reference,event_GCN-251013_173943.xmi,1.000000,1.000000,266,3,798,0,"{""absolute_time"": 534, ""trigger_time_t0"": 75, ""unknown"": 189}",
114,full,photometry,obs_time_reference,event_GCN-251222_170549.xmi,0.771732,0.864865,37,2,32,5,"{""absolute_time"": 35, ""observation_start"": 5, ""trigger_time_t0"": 32, ""unknown"": 2}",
115,full,photometry,obs_time_reference,event_GCN-260604_202037.xmi,0.848522,0.935484,62,2,58,4,"{""absolute_time"": 92, ""observation_mid"": 4, ""trigger_time_t0"": 16, ""unknown"": 12}",
116,full,photometry,obs_time_reference,event_GCN-260614_134953.xmi,1.000000,1.000000,7,2,7,0,"{""absolute_time"": 6, ""trigger_time_t0"": 8}",
117,full,photometry,obs_time_reference,event_GRB-241025_013651.xmi,0.849888,0.911111,45,3,123,12,"{""absolute_time"": 47, ""observation_mid"": 2, ""observation_start"": 4, ""trigger_time_t0"": 72, ""unknown"": 10}",
118,full,photometry,obs_time_reference,event_GRB-260708A.xmi,NaN,1.000000,3,4,18,0,"{""trigger_time_t0"": 12}",no expected disagreement: all usable ratings have one category
119,full,photometry,obs_time_reference,event_GRB241030.xmi,0.584185,0.728395,54,4,236,88,"{""absolute_time"": 101, ""observation_mid"": 2, ""observation_start"": 38, ""trigger_time_t0"": 68, ""unknown"": 7}",
120,full,photometry,obs_time_reference,POOLED,0.811989,0.878301,670,10,1696,235,"{""absolute_time"": 1019, ""observation_mid"": 21, ""observation_start"": 85, ""trigger_time_t0"": 569, ""unknown"": 248}",

,perimeter,layer,feature,document_name,alpha,raw_agreement,n_items,n_annotators,agreeing_pairs,disagreeing_pairs,category_distribution,degenerate_reason
11,restricted,evidence,label,event_2025aji.xmi,0.973008,0.980100,201,2,197,4,"{""<DELETED>"": 4, ""CLASSIFICATION_INTERPRETATION"": 2, ""COUNTERPART_ASSOCIATION"": 50, ""EVENT_IDENTITY"": 189, ""HIGH_ENERGY_PROPERTY"": 24, ""LIGHTCURVE_EVOLUTION"": 54, ""LOCALIZATION"": 16, ""NEGATIVE_STATEMENT"": 2, ""REDSHIFT_CONTEXT"": 6, ""REDSHIFT_EVENT"": 10, ""SPECTROSCOPY"": 16, ""T90"": 2, ""TRIGGER_INSTRUMENT"": 14, ""TRIGGER_TIME"": 13}",
12,restricted,evidence,label,event_2026owq.xmi,1.000000,1.000000,204,3,612,0,"{""CLASSIFICATION_INTERPRETATION"": 21, ""COUNTERPART_ASSOCIATION"": 66, ""EVENT_IDENTITY"": 309, ""HIGH_ENERGY_PROPERTY"": 42, ""HOST_CONTEXT"": 3, ""LIGHTCURVE_EVOLUTION"": 75, ""LOCALIZATION"": 15, ""REDSHIFT_CONTEXT"": 3, ""REDSHIFT_EVENT"": 21, ""SPECTROSCOPY"": 24, ""T90"": 6, ""TRIGGER_INSTRUMENT"": 15, ""TRIGGER_TIME"": 12}",
13,restricted,evidence,label,event_EP-260623_025405.xmi,NaN,NaN,0,1,0,0,{},no item has 2 ratings
14,restricted,evidence,label,event_GCN-251013_173943.xmi,1.000000,1.000000,237,2,237,0,"{""CLASSIFICATION_INTERPRETATION"": 12, ""COUNTERPART_ASSOCIATION"": 60, ""DURATION_GENERAL"": 2, ""EVENT_IDENTITY"": 222, ""HIGH_ENERGY_PROPERTY"": 22, ""LIGHTCURVE_EVOLUTION"": 46, ""LOCALIZATION"": 20, ""REDSHIFT_EVENT"": 18, ""SPECTROSCOPY"": 6, ""T90"": 8, ""TRIGGER_INSTRUMENT"": 36, ""TRIGGER_TIME"": 22}",
15,restricted,evidence,label,event_GCN-251222_170549.xmi,0.979171,0.983471,242,2,238,4,"{""<NULL>"": 2, ""CLASSIFICATION_INTERPRETATION"": 6, ""COUNTERPART_ASSOCIATION"": 48, ""DURATION_GENERAL"": 4, ""EVENT_IDENTITY"": 192, ""HIGH_ENERGY_PROPERTY"": 56, ""LIGHTCURVE_EVOLUTION"": 36, ""LOCALIZATION"": 22, ""NEGATIVE_STATEMENT"": 2, ""REDSHIFT_CONTEXT"": 2, ""REDSHIFT_EVENT"": 13, ""SPECTROSCOPY"": 8, ""T90"": 6, ""TRIGGER_INSTRUMENT"": 60, ""TRIGGER_TIME"": 27}",
16,restricted,evidence,label,event_GCN-260604_202037.xmi,NaN,NaN,0,1,0,0,{},no item has 2 ratings
17,restricted,evidence,label,event_GCN-260614_134953.xmi,1.000000,1.000000,73,2,73,0,"{""CLASSIFICATION_INTERPRETATION"": 6, ""COUNTERPART_ASSOCIATION"": 4, ""EVENT_IDENTITY"": 40, ""HIGH_ENERGY_PROPERTY"": 16, ""LIGHTCURVE_EVOLUTION"": 2, ""LOCALIZATION"": 18, ""T90"": 10, ""TRIGGER_INSTRUMENT"": 34, ""TRIGGER_TIME"": 16}",
18,restricted,evidence,label,event_GRB-241025_013651.xmi,0.983073,0.987261,157,2,155,2,"{""<DELETED>"": 1, ""<NULL>"": 1, ""CLASSIFICATION_INTERPRETATION"": 6, ""COUNTERPART_ASSOCIATION"": 19, ""DURATION_GENERAL"": 4, ""EVENT_IDENTITY"": 144, ""HIGH_ENERGY_PROPERTY"": 42, ""LIGHTCURVE_EVOLUTION"": 10, ""LOCALIZATION"": 18, ""REDSHIFT_CONTEXT"": 2, ""REDSHIFT_EVENT"": 8, ""SPECTROSCOPY"": 8, ""T90"": 6, ""TRIGGER_INSTRUMENT"": 30, ""TRIGGER_TIME"": 15}",
19,restricted,evidence,label,event_GRB-260708A.xmi,0.982117,0.985294,68,4,402,6,"{""CLASSIFICATION_INTERPRETATION"": 12, ""COUNTERPART_ASSOCIATION"": 28, ""DURATION_GENERAL"": 4, ""EVENT_IDENTITY"": 96, ""HIGH_ENERGY_PROPERTY"": 26, ""LIGHTCURVE_EVOLUTION"": 18, ""LOCALIZATION"": 16, ""SPECTROSCOPY"": 4, ""T90"": 8, ""TRIGGER_INSTRUMENT"": 36, ""TRIGGER_TIME"": 24}",
20,restricted,evidence,label,event_GRB241030.xmi,0.996572,0.997426,259,3,775,2,"{""CLASSIFICATION_INTERPRETATION"": 15, ""COUNTERPART_ASSOCIATION"": 84, ""DURATION_GENERAL"": 6, ""EVENT_IDENTITY"": 357, ""HIGH_ENERGY_PROPERTY"": 75, ""HOST_CONTEXT"": 9, ""LIGHTCURVE_EVOLUTION"": 33, ""LOCALIZATION"": 33, ""NEGATIVE_STATEMENT"": 3, ""REDSHIFT_CONTEXT"": 2, ""REDSHIFT_EVENT"": 22, ""SPECTROSCOPY"": 21, ""T90"": 9, ""TRIGGER_INSTRUMENT"": 81, ""TRIGGER_TIME"": 27}",
21,restricted,evidence,label,POOLED,0.990221,0.993351,1441,7,2689,18,"{""<DELETED>"": 5, ""<NULL>"": 3, ""CLASSIFICATION_INTERPRETATION"": 80, ""COUNTERPART_ASSOCIATION"": 359, ""DURATION_GENERAL"": 20, ""EVENT_IDENTITY"": 1549, ""HIGH_ENERGY_PROPERTY"": 303, ""HOST_CONTEXT"": 12, ""LIGHTCURVE_EVOLUTION"": 274, ""LOCALIZATION"": 158, ""NEGATIVE_STATEMENT"": 7, ""REDSHIFT_CONTEXT"": 15, ""REDSHIFT_EVENT"": 92, ""SPECTROSCOPY"": 87, ""T90"": 55, ""TRIGGER_INSTRUMENT"": 306, ""TRIGGER_TIME"": 156}",
33,restricted,evidence,certainty,event_2025aji.xmi,0.850588,0.965174,201,2,194,7,"{""<DELETED>"": 4, ""candidate"": 47, ""confirmed"": 349, ""tentative"": 2}",
34,restricted,evidence,certainty,event_2026owq.xmi,1.000000,1.000000,204,3,612,0,"{""candidate"": 66, ""confirmed"": 516, ""rejected"": 6, ""tentative"": 21, ""unclear"": 3}",
35,restricted,evidence,certainty,event_EP-260623_025405.xmi,NaN,NaN,0,1,0,0,{},no item has 2 ratings
36,restricted,evidence,certainty,event_GCN-251013_173943.xmi,1.000000,1.000000,237,2,237,0,"{""candidate"": 60, ""confirmed"": 400, ""tentative"": 14}",
37,restricted,evidence,certainty,event_GCN-251222_170549.xmi,0.811080,0.954545,242,2,231,11,"{""candidate"": 48, ""confirmed"": 419, ""rejected"": 8, ""tentative"": 9}",
38,restricted,evidence,certainty,event_GCN-260604_202037.xmi,NaN,NaN,0,1,0,0,{},no item has 2 ratings
39,restricted,evidence,certainty,event_GCN-260614_134953.xmi,1.000000,1.000000,73,2,73,0,"{""candidate"": 4, ""confirmed"": 134, ""tentative"": 8}",
40,restricted,evidence,certainty,event_GRB-241025_013651.xmi,0.928351,0.987261,157,2,155,2,"{""<DELETED>"": 1, ""candidate"": 20, ""confirmed"": 284, ""rejected"": 1, ""tentative"": 8}",
41,restricted,evidence,certainty,event_GRB-260708A.xmi,0.862785,0.963235,68,4,393,15,"{""candidate"": 28, ""confirmed"": 231, ""rejected"": 5, ""tentative"": 8}",
42,restricted,evidence,certainty,event_GRB241030.xmi,0.962265,0.989704,259,3,769,8,"{""candidate"": 82, ""confirmed"": 657, ""rejected"": 3, ""tentative"": 28, ""unclear"": 7}",
43,restricted,evidence,certainty,POOLED,0.933627,0.984115,1441,7,2664,43,"{""<DELETED>"": 5, ""candidate"": 355, ""confirmed"": 2990, ""rejected"": 23, ""tentative"": 98, ""unclear"": 10}",
55,restricted,photometry,measurement_type,event_2025aji.xmi,0.981243,0.990826,109,2,108,1,"{""<NULL>"": 1, ""detection"": 129, ""upper_limit"": 88}",
56,restricted,photometry,measurement_type,event_2026owq.xmi,1.000000,1.000000,68,3,204,0,"{""detection"": 198, ""upper_limit"": 6}",
57,restricted,photometry,measurement_type,event_EP-260623_025405.xmi,1.000000,1.000000,19,2,19,0,"{""detection"": 36, ""upper_limit"": 2}",
58,restricted,photometry,measurement_type,event_GCN-251013_173943.xmi,0.980121,0.996241,266,2,265,1,"{""<NULL>"": 1, ""detection"": 476, ""upper_limit"": 55}",
59,restricted,photometry,measurement_type,event_GCN-251222_170549.xmi,1.000000,1.000000,37,2,37,0,"{""detection"": 66, ""upper_limit"": 8}",
60,restricted,photometry,measurement_type,event_GCN-260604_202037.xmi,1.000000,1.000000,62,2,62,0,"{""detection"": 54, ""upper_limit"": 70}",
61,restricted,photometry,measurement_type,event_GCN-260614_134953.xmi,NaN,1.000000,7,2,7,0,"{""detection"": 14}",no expected disagreement: all usable ratings have one category
62,restricted,photometry,measurement_type,event_GRB-241025_013651.xmi,1.000000,1.000000,45,2,45,0,"{""detection"": 40, ""upper_limit"": 50}",
63,restricted,photometry,measurement_type,event_GRB-260708A.xmi,NaN,1.000000,3,4,18,0,"{""detection"": 12}",no expected disagreement: all usable ratings have one category
64,restricted,photometry,measurement_type,event_GRB241030.xmi,1.000000,1.000000,54,4,324,0,"{""detection"": 180, ""upper_limit"": 36}",
65,restricted,photometry,measurement_type,POOLED,0.992049,0.998167,670,8,1089,2,"{""<NULL>"": 2, ""detection"": 1205, ""upper_limit"": 315}",
77,restricted,photometry,instrument,event_2025aji.xmi,0.559767,0.651376,109,2,71,38,"{""1m-PicduMidi"": 2, ""7DT"": 15, ""<EMPTY>"": 66, ""AS-32"": 2, ""AZT-33IK"": 6, ""AbAO-T70"": 2, ""C-GFT"": 3, ""COLIBRI"": 2, ""ESO/Rem60cm"": 2, ""KAO"": 2, ""KNC"": 2, ""LCO/Sinistro"": 2, ""LCOGT"": 1, ""MASTER"": 6, ""MASTER-OAFA"": 72, ""Mistral"": 1, ""NAO-2m"": 2, ""NOT/ALFOSC"": 2, ""PROMPT-5"": 6, ""PROMPT-6"": 6, ""PROMPT-MO"": 4, ""TNOT"": 2, ""UVOT"": 9, ""VLT"": 1}",
78,restricted,photometry,instrument,event_2026owq.xmi,-0.066126,0.784314,68,3,160,44,"{""<EMPTY>"": 182, ""ALFOSC"": 8, ""ATLAS"": 4, ""COLIBRI"": 5, ""GOTO"": 2, ""SAO RAS"": 1, ""Terskol"": 2}",
79,restricted,photometry,instrument,event_EP-260623_025405.xmi,-0.143488,0.263158,19,2,5,14,"{""<EMPTY>"": 22, ""COLIBRI"": 4, ""LOT"": 2, ""Liverpool telescope"": 4, ""REM 60 cm"": 1, ""TRT"": 1, ""VT"": 4}",
80,restricted,photometry,instrument,event_GCN-251013_173943.xmi,1.000000,1.000000,266,2,266,0,"{""<EMPTY>"": 438, ""CDK17 AITP"": 2, ""CrAO/ZTSh"": 2, ""Koshka/Ziess-1000"": 4, ""MASTER-SAAO"": 54, ""Mondy/AZT-33IK"": 16, ""Montarrenti Obs."": 2, ""SAO/Zeiss-1000"": 12, ""iT72"": 2}",
81,restricted,photometry,instrument,event_GCN-251222_170549.xmi,0.454796,0.486486,37,2,18,19,"{""1.6m Mephisto"": 6, ""<EMPTY>"": 11, ""AbAO/AS-32"": 2, ""COLIBRI"": 2, ""FTW"": 2, ""GOTO"": 2, ""LCO"": 1, ""MASTER"": 2, ""MASTER-Tunka"": 4, ""Mephisto"": 6, ""Mondy"": 2, ""NOT"": 1, ""NUTTelA-TAO"": 8, ""PRIME"": 2, ""SLT"": 2, ""SVOM/COLIBRI"": 2, ""TEC160FL"": 4, ""VLT/X-shooter"": 1, ""VT"": 6, ""ZTSH"": 2, ""ZTSH BVRI"": 2, ""iT72"": 4}",
82,restricted,photometry,instrument,event_GCN-260604_202037.xmi,1.000000,1.000000,62,2,62,0,"{""<EMPTY>"": 50, ""A1/CDK17"": 4, ""AITP/CDK17"": 2, ""MASTER"": 8, ""MASTER-Kislovodsk"": 20, ""MASTER-Tavrida"": 40}",
83,restricted,photometry,instrument,event_GCN-260614_134953.xmi,-0.857143,0.000000,7,2,0,7,"{""<EMPTY>"": 7, ""SVOM/VT"": 7}",
84,restricted,photometry,instrument,event_GRB-241025_013651.xmi,0.767320,0.822222,45,2,37,8,"{""<EMPTY>"": 36, ""AZT-33IK"": 1, ""COLIBRI"": 1, ""DDOTI"": 1, ""GROWTH-India"": 1, ""KNC"": 4, ""KNC-iT11"": 4, ""KNC-iT21"": 4, ""LBT"": 1, ""MASTER-Tunka"": 22, ""SAO RAS"": 1, ""TNOT"": 1, ""TRT"": 1, ""TRT-SRO"": 12}",
85,restricted,photometry,instrument,event_GRB-260708A.xmi,0.500000,0.666667,3,4,12,6,"{""<EMPTY>"": 6, ""LCO 1m"": 2, ""iT30"": 4}",
86,restricted,photometry,instrument,event_GRB241030.xmi,0.250070,0.425926,54,4,138,186,"{""<EMPTY>"": 99, ""AKO"": 1, ""C-GFT"": 2, ""COGT"": 1, ""COLIBRI"": 4, ""Global MASTER-NET"": 1, ""INAF"": 1, ""LCO"": 3, ""LCOGT"": 1, ""LOT"": 16, ""Las Cumbres"": 1, ""MASTER-Tavrida"": 25, ""MITSuME"": 1, ""MITSuME Akeno"": 1, ""Mephisto"": 12, ""Mondy"": 4, ""OHP"": 1, ""OHP/T193"": 1, ""SAO RAS"": 5, ""SVOM/C-GFT"": 3, ""SVOM/UVOT"": 9, ""SVOM/VT"": 2, ""Sinistro"": 2, ""Sun Yat-seen"": 1, ""Sun Yat-sen University 80cm infrared telescope"": 1, ""TNOT"": 3, ""TRT"": 2, ""ULL-ASTRO MASTER"": 1, ""ULL-ASTRO-MASTER"": 1, ""UVOT"": 9, ""VT"": 2}",
87,restricted,photometry,instrument,POOLED,0.641320,0.704858,670,8,769,322,"{""1.6m Mephisto"": 6, ""1m-PicduMidi"": 2, ""7DT"": 15, ""<EMPTY>"": 917, ""A1/CDK17"": 4, ""AITP/CDK17"": 2, ""AKO"": 1, ""ALFOSC"": 8, ""AS-32"": 2, ""ATLAS"": 4, ""AZT-33IK"": 7, ""AbAO-T70"": 2, ""AbAO/AS-32"": 2, ""C-GFT"": 5, ""CDK17 AITP"": 2, ""COGT"": 1, ""COLIBRI"": 18, ""CrAO/ZTSh"": 2, ""DDOTI"": 1, ""ESO/Rem60cm"": 2, ""FTW"": 2, ""GOTO"": 4, ""GROWTH-India"": 1, ""Global MASTER-NET"": 1, ""INAF"": 1, ""KAO"": 2, ""KNC"": 6, ""KNC-iT11"": 4, ""KNC-iT21"": 4, ""Koshka/Ziess-1000"": 4, ""LBT"": 1, ""LCO"": 4, ""LCO 1m"": 2, ""LCO/Sinistro"": 2, ""LCOGT"": 2, ""LOT"": 18, ""Las Cumbres"": 1, ""Liverpool telescope"": 4, ""MASTER"": 16, ""MASTER-Kislovodsk"": 20, ""MASTER-OAFA"": 72, ""MASTER-SAAO"": 54, ""MASTER-Tavrida"": 65, ""MASTER-Tunka"": 26, ""MITSuME"": 1, ""MITSuME Akeno"": 1, ""Mephisto"": 18, ""Mistral"": 1, ""Mondy"": 6, ""Mondy/AZT-33IK"": 16, ""Montarrenti Obs."": 2, ""NAO-2m"": 2, ""NOT"": 1, ""NOT/ALFOSC"": 2, ""NUTTelA-TAO"": 8, ""OHP"": 1, ""OHP/T193"": 1, ""PRIME"": 2, ""PROMPT-5"": 6, ""PROMPT-6"": 6, ""PROMPT-MO"": 4, ""REM 60 cm"": 1, ""SAO RAS"": 7, ""SAO/Zeiss-1000"": 12, ""SLT"": 2, ""SVOM/C-GFT"": 3, ""SVOM/COLIBRI"": 2, ""SVOM/UVOT"": 9, ""SVOM/VT"": 9, ""Sinistro"": 2, ""Sun Yat-seen"": 1, ""Sun Yat-sen University 80cm infrared telescope"": 1, ""TEC160FL"": 4, ""TNOT"": 6, ""TRT"": 4, ""TRT-SRO"": 12, ""Terskol"": 2, ""ULL-ASTRO MASTER"": 1, ""ULL-ASTRO-MASTER"": 1, ""UVOT"": 18, ""VLT"": 1, ""VLT/X-shooter"": 1, ""VT"": 12, ""ZTSH"": 2, ""ZTSH BVRI"": 2, ""iT30"": 4, ""iT72"": 6}",
99,restricted,photometry,photometric_system,event_2025aji.xmi,0.886072,0.935780,109,2,102,7,"{""AB"": 76, ""Vega"": 21, ""unknown"": 121}",
100,restricted,photometry,photometric_system,event_2026owq.xmi,0.395833,0.823529,68,3,168,36,"{""AB"": 168, ""unknown"": 36}",
101,restricted,photometry,photometric_system,event_EP-260623_025405.xmi,0.511013,0.842105,19,2,16,3,"{""AB"": 31, ""Vega"": 2, ""unknown"": 5}",
102,restricted,photometry,photometric_system,event_GCN-251013_173943.xmi,1.000000,1.000000,266,2,266,0,"{""AB"": 36, ""Vega"": 4, ""unknown"": 492}",
103,restricted,photometry,photometric_system,event_GCN-251222_170549.xmi,0.557576,0.810811,37,2,30,7,"{""AB"": 54, ""Vega"": 5, ""unknown"": 15}",
104,restricted,photometry,photometric_system,event_GCN-260604_202037.xmi,1.000000,1.000000,62,2,62,0,"{""AB"": 40, ""unknown"": 84}",
105,restricted,photometry,photometric_system,event_GCN-260614_134953.xmi,NaN,1.000000,7,2,7,0,"{""AB"": 14}",no expected disagreement: all usable ratings have one category
106,restricted,photometry,photometric_system,event_GRB-241025_013651.xmi,1.000000,1.000000,45,2,45,0,"{""AB"": 6, ""Vega"": 38, ""unknown"": 46}",
107,restricted,photometry,photometric_system,event_GRB-260708A.xmi,0.592593,0.777778,3,4,14,4,"{""AB"": 8, ""Vega"": 2, ""unknown"": 2}",
108,restricted,photometry,photometric_system,event_GRB241030.xmi,0.416956,0.623457,54,4,202,122,"{""AB"": 78, ""Vega"": 46, ""unknown"": 92}",
109,restricted,photometry,photometric_system,POOLED,0.811707,0.835930,670,8,912,179,"{""AB"": 511, ""Vega"": 118, ""unknown"": 893}",
121,restricted,photometry,obs_time_reference,event_2025aji.xmi,0.977841,0.990826,109,2,108,1,"{""absolute_time"": 60, ""observation_mid"": 1, ""trigger_time_t0"": 156, ""unknown"": 1}",
122,restricted,photometry,obs_time_reference,event_2026owq.xmi,0.198760,0.450980,68,3,92,112,"{""absolute_time"": 100, ""observation_mid"": 8, ""observation_start"": 30, ""trigger_time_t0"": 40, ""unknown"": 26}",
123,restricted,photometry,obs_time_reference,event_EP-260623_025405.xmi,0.132813,0.368421,19,2,7,12,"{""absolute_time"": 14, ""observation_mid"": 4, ""observation_start"": 8, ""trigger_time_t0"": 12}",
124,restricted,photometry,obs_time_reference,event_GCN-251013_173943.xmi,1.000000,1.000000,266,2,266,0,"{""absolute_time"": 356, ""trigger_time_t0"": 50, ""unknown"": 126}",
125,restricted,photometry,obs_time_reference,event_GCN-251222_170549.xmi,0.771732,0.864865,37,2,32,5,"{""absolute_time"": 35, ""observation_start"": 5, ""trigger_time_t0"": 32, ""unknown"": 2}",
126,restricted,photometry,obs_time_reference,event_GCN-260604_202037.xmi,0.848522,0.935484,62,2,58,4,"{""absolute_time"": 92, ""observation_mid"": 4, ""trigger_time_t0"": 16, ""unknown"": 12}",
127,restricted,photometry,obs_time_reference,event_GCN-260614_134953.xmi,1.000000,1.000000,7,2,7,0,"{""absolute_time"": 6, ""trigger_time_t0"": 8}",
128,restricted,photometry,obs_time_reference,event_GRB-241025_013651.xmi,0.779339,0.866667,45,2,39,6,"{""absolute_time"": 30, ""observation_mid"": 2, ""observation_start"": 4, ""trigger_time_t0"": 48, ""unknown"": 6}",
129,restricted,photometry,obs_time_reference,event_GRB-260708A.xmi,NaN,1.000000,3,4,18,0,"{""trigger_time_t0"": 12}",no expected disagreement: all usable ratings have one category
130,restricted,photometry,obs_time_reference,event_GRB241030.xmi,0.584185,0.728395,54,4,236,88,"{""absolute_time"": 101, ""observation_mid"": 2, ""observation_start"": 38, ""trigger_time_t0"": 68, ""unknown"": 7}",
131,restricted,photometry,obs_time_reference,POOLED,0.762336,0.791017,670,8,863,228,"{""absolute_time"": 794, ""observation_mid"": 21, ""observation_start"": 85, ""trigger_time_t0"": 442, ""unknown"": 180}",

These are not conventional reliability figures. Reviewers edited a shared
pre-annotation rather than annotating independently from scratch, so agreement partly
measures that nobody changed the supplied value. Full/restricted pooled alpha and raw
agreement are **0.9924/0.9902** and **99.47%/99.34%** for evidence `label`, and
**0.9939/0.9920** and **99.79%/99.82%** for photometry `measurement_type`. In
contrast, photometry `instrument` is **0.7070/0.6413** with **80.94%/70.49%** raw
agreement, `photometric_system` is **0.8318/0.8117** with **89.75%/83.59%**, and
`obs_time_reference` is **0.8120/0.7623** with **87.83%/79.10%**. The scheme is
substantially more stable about what the span represents than about these attributes.

## 7. Declared limitations

- Comments were free text with no controlled vocabulary, so their content is not
  aggregated. The countable record shows that 443 corrections modify only `comment`.
- Precision's upper bound counts only deletions as false positives. Part 4b reports a
  schema-only lower bound alongside it.
- The campaign had no structured rejection mechanism. The lower bound is itself a floor
  because it captures only annotators who improvised rejection through existing fields.
- Recall depends on review depth because an omission appears only when a reviewer creates
  the missing span.
- There is no curated consensus layer; the corpus contains independent validations of a
  shared pre-annotation.
- Two annotators produced no corrections in either layer. Their unchanged rows provide no
  observed correction signal.