# SkyPortal corpus — exploratory data analysis (A)

This notebook measures the five flattened SkyPortal tables in
`data/interim/skyportal_corpus/`: field coverage, identity and key integrity,
datetime semantics, and the anomalies that normalisation will have to face.

It is **descriptive only**. It cleans nothing, fixes nothing, and writes no data
file. Free-text and person-name columns are never displayed in full; they are
reported as length statistics only. Decisions taken from these measurements
appear in the final cell.

In [1]:
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 250)

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents]
            if (p / "data/interim/skyportal_corpus").is_dir())
CORPUS = ROOT / "data/interim/skyportal_corpus"

TABLE_NAMES = ["sources", "comments", "photometry", "spectra", "followup_requests"]
EXPECTED_SHAPE = {"sources": (982, 114), "comments": (2950, 13), "photometry": (7968, 44),
                  "spectra": (1, 52), "followup_requests": (2359, 164)}

TABLES = {}
for table_name in TABLE_NAMES:
    table_path = CORPUS / f"{table_name}.parquet"
    frame = pd.read_parquet(table_path)
    if len(frame) == 0:  # zero rows is a stop condition, never a result
        raise ValueError(f"Table '{table_name}' loaded 0 rows from {table_path}")
    TABLES[table_name] = frame
    print(f"{table_name:18s} rows={len(frame):5d} columns={frame.shape[1]:4d}  <- {table_path}")

EMPTY_TOKENS = {"", "[]", "{}"}
FREE_TEXT_TABLES = {"comments", "followup_requests"}
PERSON_RE = re.compile(r"(first_name|last_name|username|contact_email|contact_phone|oauth_uid"
                       r"|author_name|reporter|discoverer|^pis$|observers|reducers|bio"
                       r"|affiliations|allocation\.pi$)", re.I)
ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?)?$")


def has_content(series):
    """True where a cell holds real content: '', '[]', '{}' and blanks are empty."""
    def alive(value):
        if value is None:
            return False
        if isinstance(value, str):
            return value.strip() not in EMPTY_TOKENS
        if isinstance(value, float) and np.isnan(value):
            return False
        return True
    return series.map(alive)


def is_iso_text(values):
    """True when every present value looks like an ISO-8601 date or timestamp."""
    return len(values) > 0 and values.map(lambda v: bool(ISO_RE.match(v))).all()


def clip(value, limit=40):
    """Keep any displayed value short; long values are truncated on sight."""
    text = str(value)
    return f"{text[:limit]}..." if len(text) > limit else text


def summarise(table, column, series, content):
    """Describe one column under the rules fixed for this notebook."""
    if not content.any():
        return "EMPTY"
    present = series[content]
    if pd.api.types.is_bool_dtype(series):
        return " | ".join(f"{k}={v}" for k, v in present.value_counts().items())
    if pd.api.types.is_numeric_dtype(series):
        return f"min={present.min():.6g} / median={present.median():.6g} / max={present.max():.6g}"
    text = present.astype(str).str.strip()
    if is_iso_text(text):
        return f"earliest={text.min()} / latest={text.max()}"
    if table in FREE_TEXT_TABLES or PERSON_RE.search(column):
        lengths = text.map(len)
        return f"length min={lengths.min()} / median={lengths.median():.0f} / max={lengths.max()}"
    if text.nunique() <= 12:
        return " | ".join(f"{clip(k)}={v}" for k, v in text.value_counts().items())
    return " | ".join(clip(v) for v in text.drop_duplicates().head(3))


def census(table):
    """One row per column: coverage and a rule-based summary, emptiest first."""
    frame = TABLES[table]
    rows = []
    for column in frame.columns:
        series = frame[column]
        content = has_content(series)
        rows.append({"column": column, "dtype": str(series.dtype),
                     "non_null": int(series.notna().sum()),
                     "coverage_pct": round(100 * content.sum() / len(frame), 2),
                     "distinct": int(series[content].astype(str).nunique()),
                     "summary": summarise(table, column, series, content)})
    return pd.DataFrame(rows).sort_values(["coverage_pct", "column"]).reset_index(drop=True)


def census_footer(table, report):
    """One line stating how much of the table carries no usable content."""
    empty = sorted(report.loc[report["coverage_pct"] == 0, "column"])
    low = int((report["coverage_pct"] < 5).sum())
    return (f"{table}: entirely empty columns = {len(empty)} | columns under 5% content "
            f"coverage (empty included) = {low} | empty columns = {empty}")


controls = pd.DataFrame(
    [{"table": n, "expected_rows": EXPECTED_SHAPE[n][0], "observed_rows": TABLES[n].shape[0],
      "expected_cols": EXPECTED_SHAPE[n][1], "observed_cols": TABLES[n].shape[1],
      "status": "PASS" if TABLES[n].shape == EXPECTED_SHAPE[n] else "FAIL"} for n in TABLE_NAMES])
print("\nCONTROLS")
print(controls.to_string(index=False))

sources            rows=  982 columns= 114  <- /home/meneses/project_astronomical/MAFORAI/data/interim/skyportal_corpus/sources.parquet
comments           rows= 2950 columns=  13  <- /home/meneses/project_astronomical/MAFORAI/data/interim/skyportal_corpus/comments.parquet
photometry         rows= 7968 columns=  44  <- /home/meneses/project_astronomical/MAFORAI/data/interim/skyportal_corpus/photometry.parquet
spectra            rows=    1 columns=  52  <- /home/meneses/project_astronomical/MAFORAI/data/interim/skyportal_corpus/spectra.parquet
followup_requests  rows= 2359 columns= 164  <- /home/meneses/project_astronomical/MAFORAI/data/interim/skyportal_corpus/followup_requests.parquet

CONTROLS
            table  expected_rows  observed_rows  expected_cols  observed_cols status
          sources            982            982            114            114   PASS
         comments           2950           2950             13             13   PASS
       photometry           7968           7968             44             44   PASS
          spectra              1              1             52             52   PASS
followup_requests           2359           2359            164            164   PASS

In [2]:
sources_census = census("sources")
print(census_footer("sources", sources_census))
sources_census

sources: entirely empty columns = 25 | columns under 5% content coverage (empty included) = 53 | empty columns = ['altdata', 'dec_dis', 'dec_err', 'detect_photometry_count', 'dist_nearest_source', 'e_mag_nearest_source', 'host.a', 'host.alt_name', 'host.distmpc_unc', 'host.mag_fuv', 'host.mag_nuv', 'host.mag_w1', 'host.mag_w2', 'host.mag_w3', 'host.mag_w4', 'host.magk', 'host.redshift', 'host.redshift_error', 'host.sfr_w4', 'mag_nearest_source', 'mpc_name', 'ra_dis', 'ra_err', 'score', 'tns_info.end_prop_period']

,column,dtype,non_null,coverage_pct,distinct,summary
0,altdata,object,0,0.00,0,EMPTY
1,dec_dis,object,0,0.00,0,EMPTY
2,dec_err,object,0,0.00,0,EMPTY
3,detect_photometry_count,object,0,0.00,0,EMPTY
4,dist_nearest_source,object,0,0.00,0,EMPTY
5,e_mag_nearest_source,object,0,0.00,0,EMPTY
6,host.a,object,0,0.00,0,EMPTY
7,host.alt_name,object,0,0.00,0,EMPTY
8,host.distmpc_unc,object,0,0.00,0,EMPTY
9,host.mag_fuv,object,0,0.00,0,EMPTY
10,host.mag_nuv,object,0,0.00,0,EMPTY
11,host.mag_w1,object,0,0.00,0,EMPTY
12,host.mag_w2,object,0,0.00,0,EMPTY
13,host.mag_w3,object,0,0.00,0,EMPTY
14,host.mag_w4,object,0,0.00,0,EMPTY
15,host.magk,object,0,0.00,0,EMPTY
16,host.redshift,object,0,0.00,0,EMPTY
17,host.redshift_error,object,0,0.00,0,EMPTY
18,host.sfr_w4,object,0,0.00,0,EMPTY
19,mag_nearest_source,object,0,0.00,0,EMPTY
20,mpc_name,object,0,0.00,0,EMPTY
21,ra_dis,object,0,0.00,0,EMPTY
22,ra_err,object,0,0.00,0,EMPTY
23,score,object,0,0.00,0,EMPTY
24,tns_info.end_prop_period,object,0,0.00,0,EMPTY
25,host.b2a,float64,1,0.10,1,min=0.851138 / median=0.851138 / max=0.851138
26,host.btc,float64,1,0.10,1,min=16.4 / median=16.4 / max=16.4
27,host.magb,float64,1,0.10,1,min=16.4 / median=16.4 / max=16.4
28,host.mstar,float64,1,0.10,1,min=7.1095e+09 / median=7.1095e+09 / max=7.1095e+09
29,host.pa,float64,1,0.10,1,min=152.6 / median=152.6 / max=152.6
30,host.sfr_fuv,float64,1,0.10,1,min=0.876272 / median=0.876272 / max=0.876272
31,tns_info.host_redshift,float64,1,0.10,1,min=0.241995 / median=0.241995 / max=0.241995
32,host.catalog_id,float64,2,0.20,1,min=1 / median=1 / max=1
33,host.created_at,object,2,0.20,2,earliest=2023-03-30T15:55:30.378272 / latest=2023-03-30T15:55:44.068376
34,host.dec,float64,2,0.20,2,min=32.9141 / median=51.2972 / max=69.6804
35,host.distmpc,float64,2,0.20,2,min=170.853 / median=181.279 / max=191.705
36,host.healpix,float64,2,0.20,2,min=3.69015e+17 / median=4.52145e+17 / max=5.35275e+17
37,host.id,float64,2,0.20,2,min=1.01232e+07 / median=1.01586e+07 / max=1.01941e+07
38,host.modified,object,2,0.20,2,earliest=2023-03-30T15:55:30.378272 / latest=2023-03-30T15:55:44.068376
39,host.name,object,2,0.20,2,KUG 1049+331=1 | CLU J095558.5+694049=1
40,host.ra,float64,2,0.20,2,min=148.994 / median=156.093 / max=163.193
41,host_offset,float64,2,0.20,2,min=3.74389 / median=6.3264 / max=8.90891
42,tns_info.class_ads_bibcodes,object,2,0.20,1,2025TNSCR4119....1B=2
43,annotations,object,982,0.31,2,"[{""created_at"":""2025-10-17T08:06:31.9588...=2 | [{""id"":9,""modified"":""2026-07-08T19:22:45...=1"
44,host_id,float64,3,0.31,2,min=1.01232e+07 / median=1.01941e+07 / max=1.01941e+07
45,tns_info.hostname,object,3,0.31,3,NGC2398=1 | Quaia 1070591=1 | WISEA J214414.02-112617.9=1
46,tns_info.spectra,object,29,1.02,9,"[{""jd"":2460962.3354166667,""public"":1,""ex...=2 | [{""jd"":2460996.7950462964,""public"":1,""ex...=1 | [{""jd"":2460993.5,""public"":1,""exptime"":nu...=1 | [{""jd"":2460993.5,""public"":1,""exptime"":nu...=1 | [{""jd"":2460714.8538078703,""public"":1,""ex...=1 | [{""jd"":2460714.754826389,""public"":1,""exp...=1 | [{""jd"":2460631.2635648,""public"":1,""expti...=1 | [{""jd"":2460502.694456,""public"":1,""exptim...=1 | [{""jd"":2460412.1081829,""public"":1,""expti...=1"
47,tns_info.redshift,float64,11,1.12,9,min=0.002435 / median=0.098 / max=0.572
48,tns_info.object_type.id,float64,12,1.22,5,min=3 / median=7 / max=23
49,tns_info.object_type.name,object,12,1.22,5,SN Ia=5 | SN Ic-BL=2 | Afterglow=2 | SN II=2 | SLSN-II=1
50,tns_info.discovery_ads_bibcode,object,17,1.73,12,2025TNSTR4100....1O=2 | 2025TNSTR3254....1K=2 | 2026TNSTR2856....1Z=2 | 2025TNSTR2538....1K=2 | 2025TNSTR.931....1S=2 | 2025TNSTR4551....1T=1 | 2025TNSTR4553....1G=1 | 2025TNSTR4552....1T=1 | 2025TNSTR2954....1K=1 | 2025TNSTR.521....1C=1 | 2025TNSTR.518....1K=1 | 2025TNSTR.404....1L=1
51,redshift_error,float64,22,2.24,8,min=0 / median=0.01 / max=0.63
52,redshift_origin,object,44,4.48,22,GCN 39585 | GCN 39278 | GCN 37228 and 37013
53,tns_info.discmagfilter.family,object,84,6.31,7,Sloan=25 | ZTF=14 | P1=10 | GOTO=6 | ATLAS=4 | BlackGem=2 | Swift-UVOT=1
54,tns_info.discoverer_internal_name,object,84,7.03,58,length min=6 / median=12 / max=29
55,tns_info.internal_names,object,84,7.23,59,"PS25emv | MASTER OT J145749.59+284903.0, | ,GOTO25inc"
56,tns_info.dec,object,84,8.55,71,+12:01:23.39 | -42:48:16.71 | +28:49:02.82
57,tns_info.decdeg,float64,84,8.55,71,min=-82.791 / median=-18.7727 / max=80.45
58,tns_info.decdeg_err,object,84,8.55,8,0=72 | 0.00013888888888889=6 | 0.0027777777777778=1 | 5e-05=1 | 3.0555555555556e-05=1 | 0.00055555555555556=1 | 5.5555555555556e-06=1 | 2.7777777777778e-05=1
59,tns_info.discmagfilter.id,object,84,8.55,19,"""58"" | ""22"" | ""0"""
60,tns_info.discmagfilter.name,object,84,8.55,10,r=28 | Other=12 | g=12 | Clear=10 | i=7 | L=6 | orange=4 | BG-q=2 | z=2 | U=1
61,tns_info.discoverer,object,84,8.55,41,length min=11 / median=292 / max=868
62,tns_info.discovery_data_source.group_name,object,84,8.55,13,Pan-STARRS | None | MASTER
63,tns_info.discovery_data_source.groupid,float64,84,8.55,13,min=0 / median=48 / max=139
64,tns_info.discoverydate,object,84,8.55,67,earliest=2024-04-02 09:17:13.344 / latest=2026-07-08 22:42:34.272
65,tns_info.discoverymag,object,84,8.55,70,20.18 | 20.97 | 15.9
66,tns_info.name_prefix,object,84,8.55,2,AT=74 | SN=10
67,tns_info.objid,float64,84,8.55,71,min=149014 / median=175789 / max=213331
68,tns_info.objname,object,84,8.55,71,2025qir | 2025fhm | 2026ofi
69,tns_info.photometry,object,84,8.55,71,"[{""jd"":2460861.09547,""flux"":20.18,""expti... | [{""jd"":2460738.8020023,""flux"":20.97,""exp... | [{""jd"":2461196.37776,""flux"":17.12,""expti..."
70,tns_info.public,float64,84,8.55,1,min=1 / median=1 / max=1
71,tns_info.ra,object,84,8.55,71,20:03:29.517 | 13:53:34.680 | 14:57:49.526
72,tns_info.radeg,float64,84,8.55,71,min=2.03128 / median=167.276 / max=345.836
73,tns_info.radeg_err,object,84,8.55,8,0=72 | 0.00013888888888889=6 | 0.0027777777777778=1 | 4.7222222222222e-05=1 | 3.6111111111111e-05=1 | 0.00055555555555556=1 | 1.3888888888889e-05=1 | 2.7777777777778e-05=1
74,tns_info.reporter,object,84,8.55,17,length min=5 / median=11 / max=29
75,tns_info.reporterid,float64,84,8.55,17,min=125 / median=42529 / max=159514
76,tns_info.reporting_group.group_name,object,84,8.55,15,Pan-STARRS | STARGATE | MASTER
77,tns_info.reporting_group.groupid,float64,84,8.55,15,min=0 / median=48 / max=139
78,tns_info.source,object,84,8.55,2,bot=71 | user=13
79,tns_name,object,84,8.55,71,AT 2025qir | SN 2025fhm | AT 2026ofi
80,angular_diameter_distance,float64,102,10.39,57,min=99.0816 / median=1586.42 / max=1791.57
81,dm,float64,102,10.39,57,min=35.0787 / median=45.6686 / max=48.5204
82,luminosity_distance,float64,102,10.39,57,min=103.692 / median=13605.9 / max=50591.3
83,redshift,float64,102,10.39,57,min=0.023 / median=1.7585 / max=5.26
84,redshift_history,object,106,10.79,60,"[{""value"":""0.704"",""set_at_utc"":""2026-06-... | [{""value"":""0.661"",""set_at_utc"":""2025-07-... | [{""value"":""4.368"",""set_at_utc"":""2025-03-..."
85,t0,float64,224,22.81,127,min=59893.1 / median=60963.5 / max=61239.5
86,gcn_crossmatch,object,290,24.85,104,"[""2026-07-07 16:45:24""] | [""2026-07-03 03:13:57""] | [""2026-06-23 02:54:05""]"
87,alias,object,285,29.02,117,"[""EP260707a""] | [""EP 260703A""] | [""EP 260623a""]"
88,tags,object,982,30.14,215,"[{""id"":614,""name"":""EP"",""objtagoption_id""... | [{""id"":656,""name"":""EP"",""objtagoption_id""... | [{""id"":562,""name"":""EP"",""objtagoption_id""..."
89,classifications,object,982,36.76,307,"[{""classification"":""GRB"",""origin"":null,""... | [{""classification"":""GRB"",""origin"":null,""... | [{""classification"":""GO GRANDMA"",""origin""..."
90,photstats,object,982,37.78,322,"[{""obj_id"":""EP-260707_164524"",""first_det... | [{""obj_id"":""EP-260623_025405"",""first_det... | [{""obj_id"":""EP260618a"",""first_detected_f..."
91,summary,object,375,38.19,240,Initial detection was made by **EP-WXT**... | **Einstein Probe/WXT detected the fast X... | **EP/WXT** triggered **X-ray transient**...
92,summary_history,object,384,39.10,256,"[{""is_bot"":false,""summary"":""Initial dete... | [{""is_bot"":false,""summary"":""**Einstein P... | [{""is_bot"":false,""summary"":""**EP/WXT** t..."
93,origin,object,451,45.93,3,Einstein Probe=199 | Swift=131 | SVOM=121
94,capture_run,object,982,100.00,1,20260720=982
95,comment_exists,bool,982,100.00,2,True=509 | False=473
96,created_at,object,982,100.00,800,earliest=2022-11-10T02:28:36.269786 / latest=2026-07-18T11:17:50.920996
97,dec,float64,982,100.00,775,min=-89.029 / median=-8.693 / max=300.11
98,gal_lat,float64,982,100.00,798,min=-85.4632 / median=0.282142 / max=88.0633
99,gal_lon,float64,982,100.00,798,min=-178.748 / median=-3.24639 / max=179.96
100,groups,object,982,100.00,897,"[{""nickname"":null,""modified"":""2022-07-13... | [{""nickname"":null,""modified"":""2022-07-13... | [{""nickname"":null,""modified"":""2022-07-13..."
101,healpix,int64,982,100.00,798,min=4.7118e+14 / median=1.86142e+18 / max=3.43912e+18
102,id,object,982,100.00,800,EP-260710_180701 | EP-260707_164524 | EP-260706_215841
103,internal_key,object,982,100.00,800,474fdd29-ca8f-4358-833a-34fefbad29a0 | 4c88f38b-0a72-491c-9d04-b5961160c758 | 616e0702-afdb-4f17-a461-10625c6ecf1c
104,is_roid,bool,982,100.00,1,False=982
105,modified,object,982,100.00,800,earliest=2023-05-21T19:41:45.148510 / latest=2026-07-19T09:50:32.482435
106,offset,float64,982,100.00,1,min=0 / median=0 / max=0
107,photometry_exists,bool,982,100.00,2,False=637 | True=345
108,ra,float64,982,100.00,791,min=0 / median=197.18 / max=359.054
109,source_file,object,982,100.00,5,sources_page_001.json=400 | sources_page_002.json=355 | sources_page_003.json=120 | sources_page_004.json=100 | sources_page_005.json=7
110,source_profile,object,982,100.00,4,grandma_base=407 | ep=219 | grb=201 | gcn=155
111,spectrum_exists,bool,982,100.00,2,False=981 | True=1
112,transient,bool,982,100.00,1,False=982
113,varstar,bool,982,100.00,1,False=982

In [3]:
photometry_census = census("photometry")
print(census_footer("photometry", photometry_census))
photometry_census

photometry: entirely empty columns = 2 | columns under 5% content coverage (empty included) = 22 | empty columns = ['dec_unc', 'ra_unc']

,column,dtype,non_null,coverage_pct,distinct,summary
0,dec_unc,object,0,0.00,0,EMPTY
1,ra_unc,object,0,0.00,0,EMPTY
2,altdata.Telescope,object,1,0.01,1,Colibri=1
3,altdata.energy_band,object,1,0.01,1,10 keV - 10 MeV=1
4,altdata.fluence,object,1,0.01,1,7.70e-6 erg/cm^2=1
5,altdata.redshift,object,1,0.01,1,0.764=1
6,altdata.warning,object,2,0.03,2,VT_R band is not the same as besselr=1 | VT_B band is not the same as besselb=1
7,altdata.Exposure,object,4,0.05,4,6minutes=1 | 4minutes=1 | 5minutes=1 | 14minutes=1
8,altdata.filter,object,5,0.06,3,VT_B=2 | VT_R=2 | r=1
9,altdata.comment,object,6,0.08,4,calibrated using nearby stars from USNO-...=3 | VT-R band is not the same as Bessel R=1 | VT_B band is not the same as Bessel B=1 | It is not sure Mag is in Vega but we use...=1
10,altdata.calibration,object,12,0.15,7,"calibrated against nearby USNO-B1 stars ...=3 | calibrated against nearby USNO-B1.0 star...=3 | calibrated against PanSTARRS DR1, not co...=2 | calculated with respect to the PS1 catal...=1 | calibrated against the PS1 catalog=1 | limit is estimated from comparison to ne...=1 | calibrated against Pan-STARRS field star...=1"
11,altdata.telescope,object,21,0.26,7,Swift=9 | SVOM/VT=4 | Liverpool Telescope=2 | COATLI/HUITZI=2 | LCOGT=2 | Swift/UVOT=1 | GMG=1
12,altdata.Note,object,27,0.34,27,STD4182 | STD4183 | STD4184
13,altdata.GCN,object,56,0.70,33,https://gcn.nasa.gov/circulars/45021 | https://gcn.nasa.gov/circulars/45024 | https://gcn.nasa.gov/circulars/44990
14,altdata.imported_from,object,70,0.88,1,fink=70
15,altdata.instrument,object,99,1.24,49,COLIBRu00cd | REM | BOOTES-5/JGU
16,altdata.Instrument,object,135,1.69,4,ROS=90 | VT=21 | Prompt5=19 | Prompt6=5
17,altdata.meta1,object,193,2.35,8,Leavitt Observatory GCN 42333 arbitrary ...=53 | Calapai Observatory GCN 42275 arbitrary ...=40 | BBO GCN 42262 arbitrary upper limit arbi...=39 | None=26 | swfitgcn=17 | MXT-expo1800=5 | MXT-expo1697.384=4 | swiftgcn=3
18,altdata.colorterm,object,330,4.14,88,-0.48 | -0.07 | XX
19,altdata.colorterm_applied,object,330,4.14,2,n=217 | y=113
20,altdata.ima_name,object,330,4.14,330,SN2023wrk_2023_11_06-ciey.fits | SN2023wrk_SERRAU_2023-11-07T04-33-42-sta... | SN2023wrk_SN2023wrk_SERRAU_2023-11-07T05...
21,altdata.n_im,object,330,4.14,21,1 | 15 | 5
22,altdata.stdview,object,1061,13.32,1045,3405 | 3406 | 3407
23,altdata.note,object,1274,15.99,555,arbitrary UL | task 4821 | task 4816
24,altdata.exposure,object,1336,16.77,347,2x80 | 3x50 | 6x300
25,magerr,float64,3921,49.21,1616,min=0.0001 / median=0.06 / max=17.2
26,snr,float64,3923,49.23,1665,min=-0.57144 / median=18.0956 / max=10857.4
27,mag,float64,3929,49.31,3087,min=11.89 / median=18.19 / max=32.1805
28,dec,float64,4361,54.73,271,min=-82.7911 / median=-27.3142 / max=83.5756
29,ra,float64,4361,54.73,270,min=2.03128 / median=198.677 / max=359.102
30,capture_run,object,7968,100.00,1,20260724=7968
31,created_at,object,7968,100.00,7968,earliest=2022-11-10T15:36:48.606536 / latest=2026-07-24T12:20:01.229218
32,filter,object,7968,100.00,39,atlaso | sdssg | sdssr
33,groups,object,7968,100.00,153,"[{""id"":1,""name"":""provisioned-admin"",""nic... | [{""id"":3,""name"":""GRANDMA"",""nickname"":nul... | [{""id"":2,""name"":""Sitewide Group"",""nickna..."
34,id,int64,7968,100.00,7968,min=826 / median=33934.5 / max=104025
35,instrument_id,int64,7968,100.00,60,min=1 / median=35 / max=127
36,instrument_name,object,7968,100.00,60,ATLAS | Les-Makes/T60 | TAROT/TCH
37,limiting_mag,float64,7968,100.00,2347,min=-1 / median=19.36 / max=35
38,magsys,object,7968,100.00,1,ab=7968
39,mjd,float64,7968,100.00,7129,min=2024 / median=60568 / max=61582.2
40,obj_id,object,7968,100.00,240,2024abfo | 2024hiu | 2024hiw
41,origin,object,7968,100.00,75,None | stdview | fp
42,source_dir,object,7968,100.00,240,2024abfo | 2024hiu | 2024hiw
43,source_file,object,7968,100.00,1,photometry.json=7968

In [4]:
comments_census = census("comments")
print(census_footer("comments", comments_census))
comments_census

comments: entirely empty columns = 1 | columns under 5% content coverage (empty included) = 1 | empty columns = ['origin']

             column   dtype  non_null  coverage_pct  distinct                                                                  summary
0            origin  object         0          0.00         0                                                                    EMPTY
1   attachment_name  object       223          7.56       190                                        length min=7 / median=52 / max=54
2         author_id   int64      2950        100.00        76                                              min=3 / median=39 / max=189
3               bot    bool      2950        100.00         2                                                    False=2767 | True=183
4       capture_run  object      2950        100.00         1                                          length min=8 / median=8 / max=8
5        created_at  object      2950        100.00      2781  earliest=2022-11-10T06:21:24.729276 / latest=2026-07-21T07:31:02.676796
6                id   int64      2950        100.00      2950                                       min=156 / median=2123.5 / max=3651
7          modified  object      2950        100.00      2781  earliest=2022-11-10T06:21:24.729276 / latest=2026-07-21T07:31:02.676796
8            obj_id  object      2950        100.00       351                                        length min=6 / median=12 / max=28
9      resourceType  object      2950        100.00         1                                          length min=7 / median=7 / max=7
10       source_dir  object      2950        100.00       351                                        length min=6 / median=12 / max=28
11      source_file  object      2950        100.00         1                                       length min=13 / median=13 / max=13
12             text  object      2950        100.00      2810                                      length min=5 / median=58 / max=1883

In [5]:
followup_census = census("followup_requests")
print(census_footer("followup_requests", followup_census))
followup_census

followup_requests: entirely empty columns = 20 | columns under 5% content coverage (empty included) = 50 | empty columns = ['allocation.group.description', 'allocation.group.nickname', 'allocation.instrument.last_status_update', 'allocation.instrument.listener_classname', 'allocation.instrument.tns_id', 'allocation.instrument.treasuremap_id', 'allocation.proposal_id', 'allocation.validity_ranges', 'obj.altdata', 'obj.dec_dis', 'obj.dec_err', 'obj.detect_photometry_count', 'obj.dist_nearest_source', 'obj.e_mag_nearest_source', 'obj.mag_nearest_source', 'obj.mpc_name', 'obj.ra_dis', 'obj.ra_err', 'obj.score', 'obj.tns_info.end_prop_period']

                                                                           column    dtype  non_null  coverage_pct  distinct                                                                  summary
0                                                    allocation.group.description   object         0          0.00         0                                                                    EMPTY
1                                                       allocation.group.nickname   object         0          0.00         0                                                                    EMPTY
2                                        allocation.instrument.last_status_update   object         0          0.00         0                                                                    EMPTY
3                                        allocation.instrument.listener_classname   object         0          0.00         0                                                                    EMPTY
4                                                    allocation.instrument.tns_id   object         0          0.00         0                                                                    EMPTY
5                                            allocation.instrument.treasuremap_id   object         0          0.00         0                                                                    EMPTY
6                                                          allocation.proposal_id   object         0          0.00         0                                                                    EMPTY
7                                                      allocation.validity_ranges   object         9          0.00         0                                                                    EMPTY
8                                                                     obj.altdata   object         0          0.00         0                                                                    EMPTY
9                                                                     obj.dec_dis   object         0          0.00         0                                                                    EMPTY
10                                                                    obj.dec_err   object         0          0.00         0                                                                    EMPTY
11                                                    obj.detect_photometry_count   object         0          0.00         0                                                                    EMPTY
12                                                        obj.dist_nearest_source   object         0          0.00         0                                                                    EMPTY
13                                                       obj.e_mag_nearest_source   object         0          0.00         0                                                                    EMPTY
14                                                         obj.mag_nearest_source   object         0          0.00         0                                                                    EMPTY
15                                                                   obj.mpc_name   object         0          0.00         0                                                                    EMPTY
16                                                                     obj.ra_dis   object         0          0.00         0                                                                    EMPTY
17                                                                     obj.ra_err   object         0          0.00         0                                                                    EMPTY
18                                                                      obj.score   object         0          0.00         0                                                                    EMPTY
19                                                   obj.tns_info.end_prop_period   object         0          0.00         0                                                                    EMPTY
20                                                          payload.exp_time_just   object         1          0.04         1                                    length min=127 / median=127 / max=127
21                                                    payload.immediate_objective   object         1          0.04         1                                    length min=110 / median=110 / max=110
22                                                        payload.monitoring_freq  float64         1          0.04         1                                                 min=1 / median=1 / max=1
23                                                               payload.obs_type   object         1          0.04         1                                       length min=11 / median=11 / max=11
24                                                           payload.science_just   object         1          0.04         1                                       length min=87 / median=87 / max=87
25                                                            payload.source_type   object         1          0.04         1                                       length min=12 / median=12 / max=12
26                                                                payload.urgency   object         1          0.04         1                                          length min=1 / median=1 / max=1
27                                                              payload.uvot_mode   object         1          0.04         1                                          length min=7 / median=7 / max=7
28                                                          payload.xrt_countrate  float64         1          0.04         1                                  min=0.0025 / median=0.0025 / max=0.0025
29                                                     obj.tns_info.host_redshift  float64         2          0.08         1                            min=0.241995 / median=0.241995 / max=0.241995
30                                                           payload.camera_model   object         2          0.08         2                                         length min=7 / median=9 / max=11
31                                                   payload.expected_sensitivity  float64         5          0.21         2                                              min=21 / median=22 / max=22
32                                                                    payload.snr  float64         5          0.21         1                                                 min=5 / median=5 / max=5
33                                               payload.use_expected_sensitivity   object         5          0.21         1                                          length min=4 / median=4 / max=4
34                                                               payload.position   object        11          0.47         1                                       length min=29 / median=29 / max=29
35                                                                       watchers   object      2359          0.47        11                                    length min=131 / median=132 / max=262
36                                                           payload.request_type   object        12          0.51         2                                       length min=12 / median=17 / max=17
37                                                obj.tns_info.class_ads_bibcodes   object        16          0.68         1                                       length min=19 / median=19 / max=19
38                                                                    obj.host_id  float64        18          0.76         2                   min=1.01232e+07 / median=1.01941e+07 / max=1.01941e+07
39                                                          obj.tns_info.hostname   object        26          1.10         3                                        length min=7 / median=25 / max=25
40                                             obj.tns_info.discovery_ads_bibcode   object        33          1.40         7                                       length min=19 / median=19 / max=19
41                                                                   payload.date   object        36          1.53        27                earliest=2025-02-18T02:00:00 / latest=2025-03-19T20:30:00
42                                                                  requester.bio   object        55          1.70         2                                       length min=29 / median=53 / max=53
43                                                      requester.expiration_date   object        48          2.03         5                earliest=2024-07-05T00:00:00 / latest=2026-05-21T00:00:00
44                                                           obj.tns_info.spectra   object       252          2.20         4                                    length min=468 / median=629 / max=877
45                                                          obj.tns_info.redshift  float64        57          2.42         4                                   min=0.002435 / median=0.09 / max=0.572
46                                                    obj.tns_info.object_type.id  float64        58          2.46         4                                               min=3 / median=10 / max=23
47                                                  obj.tns_info.object_type.name   object        58          2.46         4                                          length min=5 / median=5 / max=9
48                                                             obj.redshift_error  float64        70          2.97         8                                          min=0 / median=0.001 / max=0.63
49                                                            obj.redshift_origin   object       108          4.58        18                                         length min=3 / median=9 / max=26
50                                                           payload.station_name   object       213          9.03         9                                         length min=3 / median=3 / max=13
51                                              obj.tns_info.discmagfilter.family   object       347         11.19         6                                         length min=2 / median=5 / max=10
52                                                                   obj.redshift  float64       274         11.62        47                                      min=0.023 / median=0.764 / max=5.26
53                                                                        comment   object       283         12.00       282                                       length min=38 / median=38 / max=38
54                                                           obj.redshift_history   object       295         12.51        49                                     length min=97 / median=121 / max=452
55                 allocation.instrument.sensitivity_data.ps1::open.exposure_time  float64       301         12.76         2                                             min=30 / median=30 / max=180
56            allocation.instrument.sensitivity_data.ps1::open.limiting_magnitude   object       301         12.76         2                                          length min=2 / median=2 / max=4
57                        allocation.instrument.sensitivity_data.ps1::open.magsys   object       301         12.76         1                                          length min=2 / median=2 / max=2
58                     allocation.instrument.sensitivity_data.ps1::open.zeropoint  float64       301         12.76         2                                        min=26.3 / median=26.3 / max=28.2
59                                          obj.tns_info.discoverer_internal_name   object       347         13.14        30                                        length min=7 / median=23 / max=29
60                                                         requester.affiliations   object       914         13.52        18                                       length min=7 / median=10 / max=112
61                                                    obj.tns_info.internal_names   object       347         13.82        31                                       length min=7 / median=23 / max=116
62                                                                payload.filters   object       330         13.82        13                                        length min=5 / median=16 / max=24
63                                                                payload.airmass   object       330         13.99         8                                          length min=1 / median=3 / max=3
64                                                 payload.observation_preference   object       330         13.99         2                                       length min=15 / median=17 / max=17
65                                                               obj.tns_info.dec   object       347         14.71        41                                       length min=12 / median=12 / max=12
66                                                            obj.tns_info.decdeg  float64       347         14.71        41                                 min=-82.791 / median=3.62838 / max=80.45
67                                                        obj.tns_info.decdeg_err   object       347         14.71         6                                         length min=1 / median=1 / max=19
68                                                  obj.tns_info.discmagfilter.id   object       347         14.71        16                                          length min=1 / median=2 / max=5
69                                                obj.tns_info.discmagfilter.name   object       347         14.71         9                                          length min=1 / median=1 / max=6
70                                                        obj.tns_info.discoverer   object       347         14.71        31                                     length min=11 / median=357 / max=868
71                                  obj.tns_info.discovery_data_source.group_name   object       347         14.71        12                                         length min=3 / median=6 / max=10
72                                     obj.tns_info.discovery_data_source.groupid  float64       347         14.71        12                                              min=0 / median=71 / max=139
73                                                     obj.tns_info.discoverydate   object       347         14.71        40        earliest=2024-04-02 09:17:13.344 / latest=2026-07-08 22:42:34.272
74                                                      obj.tns_info.discoverymag   object       347         14.71        40                                          length min=2 / median=6 / max=7
75                                                       obj.tns_info.name_prefix   object       347         14.71         2                                          length min=2 / median=2 / max=2
76                                                             obj.tns_info.objid  float64       347         14.71        41                                  min=149014 / median=150415 / max=213331
77                                                           obj.tns_info.objname   object       347         14.71        41                                          length min=7 / median=7 / max=8
78                                                        obj.tns_info.photometry   object       347         14.71        41                                   length min=281 / median=605 / max=4693
79                                                            obj.tns_info.public  float64       347         14.71         1                                                 min=1 / median=1 / max=1
80                                                                obj.tns_info.ra   object       347         14.71        41                                       length min=12 / median=12 / max=12
81                                                             obj.tns_info.radeg  float64       347         14.71        41                               min=2.03128 / median=165.475 / max=345.836
82                                                         obj.tns_info.radeg_err   object       347         14.71         6                                         length min=1 / median=1 / max=19
83                                                          obj.tns_info.reporter   object       347         14.71        16                                        length min=5 / median=12 / max=29
84                                                        obj.tns_info.reporterid  float64       347         14.71        16                                      min=125 / median=66140 / max=159514
85                                        obj.tns_info.reporting_group.group_name   object       347         14.71        14                                         length min=3 / median=8 / max=10
86                                           obj.tns_info.reporting_group.groupid  float64       347         14.71        14                                              min=0 / median=74 / max=139
87                                                            obj.tns_info.source   object       347         14.71         2                                          length min=3 / median=3 / max=4
88                                                                   obj.tns_name   object       347         14.71        41                                       length min=10 / median=10 / max=11
89                                                        requester.contact_phone   object       348         14.75        19                                       length min=12 / median=12 / max=14
90                                                                      obj.alias   object       364         15.43        89                                       length min=13 / median=15 / max=34
91                                                        requester.contact_email   object       376         15.94        29                                       length min=13 / median=22 / max=32
92                                                                         obj.t0  float64       384         16.28        94                               min=60260.6 / median=60961.7 / max=61239.5
93                                                            requester.oauth_uid   object       399         16.91        32                                       length min=15 / median=19 / max=42
94   allocation.instrument.configuration_data.specific_configuration.station_name   object       417         17.68         3                                       length min=11 / median=12 / max=13
95                                                                  target_groups   object      2359         19.37         8                                    length min=186 / median=186 / max=457
96                                                             obj.gcn_crossmatch   object       588         21.62        87                                       length min=23 / median=23 / max=70
97                                             allocation.default_share_group_ids   object       549         23.27         1                                          length min=3 / median=3 / max=3
98                                                                    obj.summary   object       570         24.16       131                                     length min=8 / median=282 / max=2184
99                                                            obj.summary_history   object       609         25.82       135                                 length min=113 / median=1135 / max=41427

In [6]:
spectra_census = census("spectra")
print(census_footer("spectra", spectra_census))
spectra_census

spectra: entirely empty columns = 10 | columns under 5% content coverage (empty included) = 10 | empty columns = ['altdata.', 'annotations', 'assignment_id', 'comments', 'followup_request_id', 'origin', 'owner.bio', 'owner.contact_phone', 'owner.expiration_date', 'units']

                           column    dtype  non_null  coverage_pct  distinct                                                                  summary
0                        altdata.   object         1           0.0         0                                                                    EMPTY
1                     annotations   object         1           0.0         0                                                                    EMPTY
2                   assignment_id   object         0           0.0         0                                                                    EMPTY
3                        comments   object         1           0.0         0                                                                    EMPTY
4             followup_request_id   object         0           0.0         0                                                                    EMPTY
5                          origin   object         0           0.0         0                                                                    EMPTY
6                       owner.bio   object         0           0.0         0                                                                    EMPTY
7             owner.contact_phone   object         0           0.0         0                                                                    EMPTY
8           owner.expiration_date   object         0           0.0         0                                                                    EMPTY
9                           units   object         0           0.0         0                                                                    EMPTY
10  altdata.Using DEbass pipeline   object         1         100.0         1                                                                    v04=1
11  altdata.Using Splice pipeline   object         1         100.0         1                                                                    v04=1
12         altdata.Using metadata   object         1         100.0         1                                                                    m01=1
13                    capture_run   object         1         100.0         1                                                               20260724=1
14                     created_at   object         1         100.0         1  earliest=2026-02-18T08:18:01.812257 / latest=2026-02-18T08:18:01.812257
15                         errors   object         1         100.0         1                            [59.629,57.773,59.735,60.805,60.625,58.6...=1
16              external_observer   object         1         100.0         1                                                             Liana Rauf=1
17                    external_pi   object         1         100.0         1                                                             Liana Rauf=1
18               external_reducer   object         1         100.0         1                                                             Liana Rauf=1
19                         fluxes   object         1         100.0         1                            [84.263,59.684,11.712,42.072,56.556,-27....=1
20                         groups   object         1         100.0         1                            [{"created_at":"2022-07-13T14:24:42.2566...=1
21                             id    int64         1         100.0         1                                              min=36 / median=36 / max=36
22                  instrument_id    int64         1         100.0         1                                              min=15 / median=15 / max=15
23                instrument_name   object         1         100.0         1                                                      Spectrograph UAGS=1
24                          label   object         1         100.0         1                            Data obtained using ANU 2.3m Telescope/ ...=1
25                       modified   object         1         100.0         1  earliest=2026-02-18T08:18:01.812257 / latest=2026-02-18T08:18:01.812257
26                         obj_id   object         1         100.0         1                                                                2026cex=1
27               obj_internal_key   object         1         100.0         1                                   bc432b99-9847-47fd-8379-bd6e918fa55f=1
28                    observed_at   object         1         100.0         1                earliest=2026-02-11T12:31:12 / latest=2026-02-11T12:31:12
29                observed_at_mjd  float64         1         100.0         1                               min=61082.5 / median=61082.5 / max=61082.5
30                      observers   object         1         100.0         1                                    length min=368 / median=368 / max=368
31         original_file_filename   object         1         100.0         1                            OBK-1273120-WiFeS-Splice-UT20260211T1159...=1
32           original_file_string   object         1         100.0         1                           # Submitted by liana.rauf@anu.edu.au\n# R...=1
33             owner.affiliations   object         1         100.0         1                                       length min=38 / median=38 / max=38
34            owner.contact_email   object         1         100.0         1                                       length min=22 / median=22 / max=22
35               owner.created_at   object         1         100.0         1  earliest=2026-02-07T10:30:40.150257 / latest=2026-02-07T10:30:40.150257
36               owner.first_name   object         1         100.0         1                                          length min=7 / median=7 / max=7
37                       owner.id    int64         1         100.0         1                                           min=158 / median=158 / max=158
38                   owner.is_bot     bool         1         100.0         1                                                                  False=1
39                owner.last_name   object         1         100.0         1                                       length min=10 / median=10 / max=10
40                 owner.modified   object         1         100.0         1  earliest=2026-06-26T05:10:13.391131 / latest=2026-06-26T05:10:13.391131
41                owner.oauth_uid   object         1         100.0         1                                       length min=22 / median=22 / max=22
42                 owner.username   object         1         100.0         1                                       length min=10 / median=10 / max=10
43                       owner_id    int64         1         100.0         1                                           min=158 / median=158 / max=158
44                            pis   object         1         100.0         1                                    length min=368 / median=368 / max=368
45                       reducers   object         1         100.0         1                                    length min=368 / median=368 / max=368
46                     source_dir   object         1         100.0         1                                                                2026cex=1
47                    source_file   object         1         100.0         1                                                           spectra.json=1
48                   telescope_id    int64         1         100.0         1                                              min=17 / median=17 / max=17
49                 telescope_name   object         1         100.0         1                                                               ShAO-T2m=1
50                           type   object         1         100.0         1                                                                 source=1
51                    wavelengths   object         1         100.0         1                            [3403.1,3403.87,3404.64,3405.42,3406.19,...=1

In [7]:
DIRTY_ID_RE = re.compile(r"^\s|\s$|[\t\n/]|[^\x00-\x7F]")
DETAIL_TABLES = ["comments", "photometry", "spectra", "followup_requests"]

source_ids = TABLES["sources"]["id"].astype(str)
id_set = set(source_ids)
rows = [{"check": "source identity column", "table": "sources", "subject": "id",
         "finding": f"distinct={source_ids.nunique()} / distinct after strip="
                    f"{source_ids.str.strip().nunique()} / stable="
                    f"{source_ids.nunique() == source_ids.str.strip().nunique()}"}]

for value in sorted({v for v in source_ids.unique() if DIRTY_ID_RE.search(v)}):
    rows.append({"check": "dirty identifier", "table": "sources", "subject": repr(value),
                 "finding": "carries whitespace, tab, newline, slash or non-ASCII"})

for name in DETAIL_TABLES:
    frame = TABLES[name]
    source_dir = frame["source_dir"].astype(str)
    obj_id = frame["obj_id"].astype(str)
    unmatched = sorted(set(source_dir) - id_set)
    rows.append({"check": "source_dir vs sources.id", "table": name,
                 "subject": f"distinct source_dir={source_dir.nunique()}",
                 "finding": f"values absent from sources.id={len(unmatched)} "
                            f"{[repr(v) for v in unmatched[:10]]} / detail rows failing an exact "
                            f"join={int((~source_dir.isin(id_set)).sum())}"})
    rows.append({"check": "detail keys", "table": name,
                 "subject": f"own id column 'id': unique={frame['id'].nunique() == len(frame)} "
                            f"(distinct={frame['id'].nunique()} of {len(frame)} rows)",
                 "finding": f"parent reference: 'obj_id' (and capture path 'source_dir'); "
                            f"obj_id equals source_dir on {int((obj_id == source_dir).sum())} "
                            f"of {len(frame)} rows"})

identity = pd.DataFrame(rows)
identity

                      check              table                                                        subject                                                                                                    finding
0    source identity column            sources                                                             id                                                      distinct=800 / distinct after strip=800 / stable=True
1          dirty identifier            sources                                                  'AT2023toh\t'                                                       carries whitespace, tab, newline, slash or non-ASCII
2  source_dir vs sources.id           comments                                        distinct source_dir=351                                   values absent from sources.id=0 [] / detail rows failing an exact join=0
3               detail keys           comments   own id column 'id': unique=True (distinct=2950 of 2950 rows)  parent reference: 'obj_id' (and capture path 'source_dir'); obj_id equals source_dir on 2950 of 2950 rows
4  source_dir vs sources.id         photometry                                        distinct source_dir=240                                   values absent from sources.id=0 [] / detail rows failing an exact join=0
5               detail keys         photometry   own id column 'id': unique=True (distinct=7968 of 7968 rows)  parent reference: 'obj_id' (and capture path 'source_dir'); obj_id equals source_dir on 7968 of 7968 rows
6  source_dir vs sources.id            spectra                                          distinct source_dir=1                                   values absent from sources.id=0 [] / detail rows failing an exact join=0
7               detail keys            spectra         own id column 'id': unique=True (distinct=1 of 1 rows)        parent reference: 'obj_id' (and capture path 'source_dir'); obj_id equals source_dir on 1 of 1 rows
8  source_dir vs sources.id  followup_requests                                        distinct source_dir=395                                   values absent from sources.id=0 [] / detail rows failing an exact join=0
9               detail keys  followup_requests  own id column 'id': unique=False (distinct=2339 of 2359 rows)  parent reference: 'obj_id' (and capture path 'source_dir'); obj_id equals source_dir on 2339 of 2359 rows

In [8]:
ISO_TZ_RE = re.compile(r"(Z|[+-]\d{2}:?\d{2})$")
MJD_RE = re.compile(r"(^|[._])(mjd|t0)$|_mjd$", re.I)
OBSERVATION_RE = re.compile(r"(mjd|(^|\.)t0$|observed_at|discoverydate|start_date|end_date"
                            r"|payload\.date$)", re.I)

rows = []
for name in TABLE_NAMES:
    frame = TABLES[name]
    for column in frame.columns:
        series = frame[column]
        present = series[has_content(series)]
        if present.empty:
            continue
        if present.map(lambda v: isinstance(v, str)).all():
            text = present.astype(str).str.strip()
            if not is_iso_text(text):
                continue
            fmt = "ISO"
            zone = "aware" if text.map(lambda v: bool(ISO_TZ_RE.search(v))).any() else "naive"
            low, high = text.min(), text.max()
        elif MJD_RE.search(column) and pd.api.types.is_numeric_dtype(series):
            fmt, zone = "MJD", "implicit UTC, no offset stored"
            low, high = f"{present.min():.5f}", f"{present.max():.5f}"
        else:
            continue
        rows.append({"table": name, "column": column, "format": fmt, "timezone": zone,
                     "min": low, "max": high, "null_count": int(len(frame) - len(present)),
                     "meaning": "OBSERVATION_TIME" if OBSERVATION_RE.search(column) else "RECORD_TIME"})

datetimes = pd.DataFrame(rows)
print("Best candidate per table for 'when this fact became known' (causal truncation anchor):")
for name in TABLE_NAMES:
    frame = TABLES[name]
    covered = int(has_content(frame["created_at"]).sum())
    observation = datetimes[(datetimes["table"] == name) & (datetimes["meaning"] == "OBSERVATION_TIME")]
    rival = ", ".join(f"{r.column} ({len(frame) - r.null_count}/{len(frame)})"
                      for r in observation.itertuples()) or "none"
    print(f"  {name:18s} -> created_at  RECORD_TIME, populated {covered}/{len(frame)}. It is the only "
          f"column that dates every row and marks entry into SkyPortal; OBSERVATION_TIME rivals "
          f"[{rival}] date the sky event, not the knowledge, and are sparse.")
datetimes

Best candidate per table for 'when this fact became known' (causal truncation anchor):
  sources            -> created_at  RECORD_TIME, populated 982/982. It is the only column that dates every row and marks entry into SkyPortal; OBSERVATION_TIME rivals [t0 (224/982), tns_info.discoverydate (84/982)] date the sky event, not the knowledge, and are sparse.
  comments           -> created_at  RECORD_TIME, populated 2950/2950. It is the only column that dates every row and marks entry into SkyPortal; OBSERVATION_TIME rivals [none] date the sky event, not the knowledge, and are sparse.
  photometry         -> created_at  RECORD_TIME, populated 7968/7968. It is the only column that dates every row and marks entry into SkyPortal; OBSERVATION_TIME rivals [mjd (7968/7968)] date the sky event, not the knowledge, and are sparse.
  spectra            -> created_at  RECORD_TIME, populated 1/1. It is the only column that dates every row and marks entry into SkyPortal; OBSERVATION_TIME rivals [observed_at (1/1), observed_at_mjd (1/1)] date the sky event, not the knowledge, and are sparse.
  followup_requests  -> created_at  RECORD_TIME, populated 2359/2359. It is the only column that dates every row and marks entry into SkyPortal; OBSERVATION_TIME rivals [payload.end_date (2322/2359), payload.start_date (2322/2359), obj.tns_info.discoverydate (347/2359), obj.t0 (384/2359), payload.date (36/2359)] date the sky event, not the knowledge, and are sparse.

                table                            column format                        timezone                         min                         max  null_count           meaning
0             sources                          modified    ISO                           naive  2023-05-21T19:41:45.148510  2026-07-19T09:50:32.482435           0       RECORD_TIME
1             sources                                t0    MJD  implicit UTC, no offset stored                 59893.10298                 61239.46984         758  OBSERVATION_TIME
2             sources                        created_at    ISO                           naive  2022-11-10T02:28:36.269786  2026-07-18T11:17:50.920996           0       RECORD_TIME
3             sources            tns_info.discoverydate    ISO                           naive     2024-04-02 09:17:13.344     2026-07-08 22:42:34.272         898  OBSERVATION_TIME
4             sources                   host.created_at    ISO                           naive  2023-03-30T15:55:30.378272  2023-03-30T15:55:44.068376         980       RECORD_TIME
5             sources                     host.modified    ISO                           naive  2023-03-30T15:55:30.378272  2023-03-30T15:55:44.068376         980       RECORD_TIME
6            comments                        created_at    ISO                           naive  2022-11-10T06:21:24.729276  2026-07-21T07:31:02.676796           0       RECORD_TIME
7            comments                          modified    ISO                           naive  2022-11-10T06:21:24.729276  2026-07-21T07:31:02.676796           0       RECORD_TIME
8          photometry                               mjd    MJD  implicit UTC, no offset stored                  2024.00000                 61582.21003           0  OBSERVATION_TIME
9          photometry                        created_at    ISO                           naive  2022-11-10T15:36:48.606536  2026-07-24T12:20:01.229218           0       RECORD_TIME
10            spectra                        created_at    ISO                           naive  2026-02-18T08:18:01.812257  2026-02-18T08:18:01.812257           0       RECORD_TIME
11            spectra                          modified    ISO                           naive  2026-02-18T08:18:01.812257  2026-02-18T08:18:01.812257           0       RECORD_TIME
12            spectra                       observed_at    ISO                           naive         2026-02-11T12:31:12         2026-02-11T12:31:12           0  OBSERVATION_TIME
13            spectra                   observed_at_mjd    MJD  implicit UTC, no offset stored                 61082.52167                 61082.52167           0  OBSERVATION_TIME
14            spectra                  owner.created_at    ISO                           naive  2026-02-07T10:30:40.150257  2026-02-07T10:30:40.150257           0       RECORD_TIME
15            spectra                    owner.modified    ISO                           naive  2026-06-26T05:10:13.391131  2026-06-26T05:10:13.391131           0       RECORD_TIME
16  followup_requests                          modified    ISO                           naive  2023-05-20T15:32:23.647874  2026-07-18T15:59:36.067511           0       RECORD_TIME
17  followup_requests                  payload.end_date    ISO                           naive  2023-05-21 15:32:23.785537  2026-07-25 11:17:54.667915          37  OBSERVATION_TIME
18  followup_requests                payload.start_date    ISO                           naive  2023-05-20 15:32:23.785512     2026-07-18 11:22:04.743          37  OBSERVATION_TIME
19  followup_requests                        created_at    ISO                           naive  2023-05-20T15:32:23.647874  2026-07-18T13:27:33.309894           0       RECORD_TIME
20  followup_requests                    obj.created_at    ISO                           naive  2023-05-20T15:32:23.647874  2026-07-18T11:17:50.920996           0       RECORD_TIME
21  followup_requests        obj.tns_info.discoverydate    ISO                           naive     2024-04-02 09:17:13.344     2026-07-08 22:42:34.272        2012  OBSERVATION_TIME
22  followup_requests                      obj.modified    ISO                           naive  2023-05-21T19:41:45.148510  2026-07-23T08:46:48.980289           0       RECORD_TIME
23  followup_requests                            obj.t0    MJD  implicit UTC, no offset stored                 60260.63802                 61239.46984        1975  OBSERVATION_TIME
24  followup_requests             allocation.created_at    ISO                           naive  2023-01-04T17:44:59.078218  2026-03-11T09:17:18.745104           0       RECORD_TIME
25  followup_requests               allocation.modified    ISO                           naive  2023-01-06T09:46:20.808231  2026-06-03T14:56:43.618175           0       RECORD_TIME
26  followup_requests       allocation.group.created_at    ISO                           naive  2022-05-26T13:16:28.636962  2022-07-13T14:24:42.256661           0       RECORD_TIME
27  followup_requests         allocation.group.modified    ISO                           naive  2022-05-26T13:16:28.636962  2022-07-13T14:24:42.256661           0       RECORD_TIME
28  followup_requests    allocation.instrument.modified    ISO                           naive  2022-10-18T12:34:36.926657  2026-06-07T12:54:04.683091           0       RECORD_TIME
29  followup_requests  allocation.instrument.created_at    ISO                           naive  2022-05-26T13:16:29.168555  2025-08-20T13:53:42.035256           0       RECORD_TIME
30  followup_requests         requester.expiration_date    ISO                           naive         2024-07-05T00:00:00         2026-05-21T00:00:00        2311       RECORD_TIME
31  followup_requests              requester.created_at    ISO                           naive  2022-05-27T13:57:45.880360  2026-06-08T08:16:35.681675        1445       RECORD_TIME
32  followup_requests                requester.modified    ISO                           naive  2024-07-05T09:23:20.179147  2026-07-23T14:09:24.177415        1445       RECORD_TIME
33  followup_requests                      payload.date    ISO                           naive         2025-02-18T02:00:00         2025-03-19T20:30:00        2323  OBSERVATION_TIME

In [9]:
ID_RE = re.compile(r"(^|[._])id$|_id$", re.I)
SENTINELS = [-9999, -999, -99, -9, -1, 999]
CATEGORICAL = [("sources", "source_profile"), ("sources", "origin"), ("sources", "redshift_origin"),
               ("comments", "resourceType"), ("photometry", "filter"), ("photometry", "magsys"),
               ("photometry", "instrument_name"), ("photometry", "origin"),
               ("followup_requests", "allocation.instrument.name")]
STATUS_PREFIXES = ["failed to submit", "submitted for", "submitted", "deleted", "complete",
                   "rejected", "pending"]
findings = []


def add(table, column, issue, affected, detail):
    findings.append({"table": table, "column": column, "issue": issue,
                     "affected_rows": affected, "detail": detail})


def safe(table, value):
    """Never let a comments/followup value reach the output in full."""
    text = str(value)
    if table in FREE_TEXT_TABLES:
        return f"{text[:20]}..." if len(text) > 20 else text
    return clip(text, 60)


for name in TABLE_NAMES:
    frame = TABLES[name]
    for column in frame.columns:
        series, content = frame[column], has_content(frame[column])
        if not content.any():
            add(name, column, "no content in any row", len(frame), "column is entirely empty")
            continue
        present = series[content]
        types = sorted({type(v).__name__ for v in present})
        if len(types) > 1:
            add(name, column, "python type varies between rows", len(present), f"types={types}")
        if present.map(lambda v: isinstance(v, str)).all():
            text = present.astype(str)
            stripped = int((text != text.str.strip()).sum())
            if stripped:
                add(name, column, "leading or trailing whitespace", stripped, "values not shown")
            replacement = int(text.str.contains("\ufffd", regex=False).sum())
            if replacement:
                add(name, column, "contains U+FFFD", replacement, "values not shown")
        elif pd.api.types.is_numeric_dtype(series) and not pd.api.types.is_bool_dtype(series):
            if not ID_RE.search(column):  # id=999 is a real key, not a sentinel
                hits = int(present.isin(SENTINELS).sum())
                if hits:
                    add(name, column, "sentinel-like numeric value", hits,
                        f"values={sorted(set(present[present.isin(SENTINELS)]))}")
            if column.lower().split(".")[-1] in {"ra", "dec"} and (present == 0).any():
                add(name, column, "exactly zero coordinate", int((present == 0).sum()),
                    "0.0 is indistinguishable from a missing coordinate")
            if ("err" in column.lower() or "unc" in column.lower()) and (present < 0).any():
                add(name, column, "negative uncertainty", int((present < 0).sum()), "value < 0")
    duplicated = int(frame[[c for c in frame.columns if c != "id"]].astype(str).duplicated().sum())
    add(name, "<whole row>", "rows identical on every column except id", duplicated,
        "0 means no such duplicate exists")

for name, column in CATEGORICAL:
    counts = TABLES[name][column][has_content(TABLES[name][column])].astype(str).value_counts()
    for value, count in counts.items():
        add(name, column, "categorical label", int(count), f"value={safe(name, value)!r}")

status = TABLES["followup_requests"]["status"].astype(str).str.strip()
add("followup_requests", "status", "categorical column is free-form", len(status),
    f"{status.nunique()} distinct values over {len(status)} rows; error text is concatenated "
    f"into the status label")
assigned = pd.Series(False, index=status.index)
for prefix in STATUS_PREFIXES:
    match = status.str.startswith(prefix) & ~assigned
    assigned |= match
    add("followup_requests", "status", "status prefix", int(match.sum()), f"prefix={prefix!r}")
add("followup_requests", "status", "status prefix", int((~assigned).sum()), "prefix=<unclassified>")

duplicate_ids = TABLES["followup_requests"]["id"]
repeated = duplicate_ids[duplicate_ids.duplicated()].unique()
block = TABLES["followup_requests"][duplicate_ids.isin(repeated)].astype(str)
varying = [c for c in TABLES["followup_requests"].columns if block.groupby(block["id"])[c].nunique().max() > 1]
add("followup_requests", "id", "primary key is not unique", int(duplicate_ids.duplicated().sum()),
    f"{len(repeated)} ids appear twice; within a repeated id only {varying} differ")

profiles = TABLES["sources"].groupby("id")["source_profile"].nunique()
multi = set(profiles[profiles > 1].index)
block = TABLES["sources"][TABLES["sources"]["id"].isin(multi)]
compare = [c for c in TABLES["sources"].columns if c not in ("source_profile", "source_file")]
raw_diff, canonical_diff = set(), set()
for _, group in block.groupby("id"):
    for column in compare:
        values = group[column].tolist()
        if len({repr(v) for v in values}) > 1:
            raw_diff.add(column)
            canon = {json.dumps(json.loads(v), sort_keys=True) if isinstance(v, str)
                     and v[:1] in "[{" else repr(v) for v in values}
            if len(canon) > 1:
                canonical_diff.add(column)
add("sources", "id", "same source captured under several profiles", len(block),
    f"{len(multi)} ids span more than one profile, occupying {len(block)} of {len(TABLES['sources'])} rows")
add("sources", "id", "multi-profile rows differ before JSON key ordering is normalised",
    len(block), f"columns differing raw={sorted(raw_diff)}")
add("sources", "id", "multi-profile rows still differ after JSON keys are sorted", len(block),
    f"columns differing canonically={sorted(canonical_diff)}; the rest differed only by key order")

candidates = pd.DataFrame(findings).sort_values(["table", "issue", "column"]).reset_index(drop=True)
raised = set(candidates["issue"])
print("Checks that ran and raised nothing:",
      [issue for issue in ["python type varies between rows", "contains U+FFFD",
                           "negative uncertainty", "sentinel-like numeric value",
                           "exactly zero coordinate"] if issue not in raised])
candidates

Checks that ran and raised nothing: ['python type varies between rows', 'contains U+FFFD', 'negative uncertainty']

,table,column,issue,affected_rows,detail
0,comments,resourceType,categorical label,2950,value='sources'
1,comments,text,leading or trailing whitespace,551,values not shown
2,comments,origin,no content in any row,2950,column is entirely empty
3,comments,<whole row>,rows identical on every column except id,0,0 means no such duplicate exists
4,followup_requests,status,categorical column is free-form,2359,187 distinct values over 2359 rows; error text is concatenated into the status label
5,followup_requests,allocation.instrument.name,categorical label,250,value='FRAM-Auger'
6,followup_requests,allocation.instrument.name,categorical label,229,value='FRAM-CTA-N'
7,followup_requests,allocation.instrument.name,categorical label,206,value='TAROT/TRE'
8,followup_requests,allocation.instrument.name,categorical label,172,value='TRT'
9,followup_requests,allocation.instrument.name,categorical label,116,value='TAROT/TCH'
10,followup_requests,allocation.instrument.name,categorical label,95,value='TAROT/TCA'
11,followup_requests,allocation.instrument.name,categorical label,95,value='OPD/1.6m'
12,followup_requests,allocation.instrument.name,categorical label,92,value='ShAO-T60'
13,followup_requests,allocation.instrument.name,categorical label,91,value='KAO'
14,followup_requests,allocation.instrument.name,categorical label,89,value='UBAI/ST-60'
15,followup_requests,allocation.instrument.name,categorical label,89,value='UBAI/NT-60'
16,followup_requests,allocation.instrument.name,categorical label,88,value='Lisnyky/Schmidt'
17,followup_requests,allocation.instrument.name,categorical label,87,value='OST-CDK'
18,followup_requests,allocation.instrument.name,categorical label,86,value='SOAR/Spartan'
19,followup_requests,allocation.instrument.name,categorical label,86,value='Les-Makes/T60'
20,followup_requests,allocation.instrument.name,categorical label,86,value='GMG-2.4'
21,followup_requests,allocation.instrument.name,categorical label,85,value='PicduMidi/T1M'
22,followup_requests,allocation.instrument.name,categorical label,85,value='UBAI/AZT-22'
23,followup_requests,allocation.instrument.name,categorical label,85,value='OAJ/T80'
24,followup_requests,allocation.instrument.name,categorical label,85,value='OSN/T150'
25,followup_requests,allocation.instrument.name,categorical label,35,value='TAROT'
26,followup_requests,allocation.instrument.name,categorical label,11,value='ZTF'
27,followup_requests,allocation.instrument.name,categorical label,6,value='AbAO-T70'
28,followup_requests,allocation.instrument.name,categorical label,5,value='TTT'
29,followup_requests,allocation.instrument.name,categorical label,3,value='ATLAS'
30,followup_requests,allocation.instrument.name,categorical label,1,value='NUTTelA-TAO '
31,followup_requests,allocation.instrument.name,categorical label,1,value='UVOTXRT'
32,followup_requests,obj.dec,exactly zero coordinate,17,0.0 is indistinguishable from a missing coordinate
33,followup_requests,obj.ra,exactly zero coordinate,17,0.0 is indistinguishable from a missing coordinate
34,followup_requests,allocation.instrument.name,leading or trailing whitespace,1,values not shown
35,followup_requests,allocation.pi,leading or trailing whitespace,172,values not shown
36,followup_requests,obj.id,leading or trailing whitespace,17,values not shown
37,followup_requests,obj.redshift_origin,leading or trailing whitespace,8,values not shown
38,followup_requests,obj.summary,leading or trailing whitespace,108,values not shown
39,followup_requests,obj.tns_info.discoverer,leading or trailing whitespace,17,values not shown
40,followup_requests,obj.tns_info.reporter,leading or trailing whitespace,6,values not shown
41,followup_requests,obj_id,leading or trailing whitespace,17,values not shown
42,followup_requests,source_dir,leading or trailing whitespace,17,values not shown
43,followup_requests,status,leading or trailing whitespace,2,values not shown
44,followup_requests,allocation.group.description,no content in any row,2359,column is entirely empty
45,followup_requests,allocation.group.nickname,no content in any row,2359,column is entirely empty
46,followup_requests,allocation.instrument.last_status_update,no content in any row,2359,column is entirely empty
47,followup_requests,allocation.instrument.listener_classname,no content in any row,2359,column is entirely empty
48,followup_requests,allocation.instrument.tns_id,no content in any row,2359,column is entirely empty
49,followup_requests,allocation.instrument.treasuremap_id,no content in any row,2359,column is entirely empty
50,followup_requests,allocation.proposal_id,no content in any row,2359,column is entirely empty
51,followup_requests,allocation.validity_ranges,no content in any row,2359,column is entirely empty
52,followup_requests,obj.altdata,no content in any row,2359,column is entirely empty
53,followup_requests,obj.dec_dis,no content in any row,2359,column is entirely empty
54,followup_requests,obj.dec_err,no content in any row,2359,column is entirely empty
55,followup_requests,obj.detect_photometry_count,no content in any row,2359,column is entirely empty
56,followup_requests,obj.dist_nearest_source,no content in any row,2359,column is entirely empty
57,followup_requests,obj.e_mag_nearest_source,no content in any row,2359,column is entirely empty
58,followup_requests,obj.mag_nearest_source,no content in any row,2359,column is entirely empty
59,followup_requests,obj.mpc_name,no content in any row,2359,column is entirely empty
60,followup_requests,obj.ra_dis,no content in any row,2359,column is entirely empty
61,followup_requests,obj.ra_err,no content in any row,2359,column is entirely empty
62,followup_requests,obj.score,no content in any row,2359,column is entirely empty
63,followup_requests,obj.tns_info.end_prop_period,no content in any row,2359,column is entirely empty
64,followup_requests,id,primary key is not unique,20,"20 ids appear twice; within a repeated id only ['target_groups', 'source_dir'] differ"
65,followup_requests,<whole row>,rows identical on every column except id,0,0 means no such duplicate exists
66,followup_requests,status,status prefix,1028,prefix='failed to submit'
67,followup_requests,status,status prefix,133,prefix='submitted for'
68,followup_requests,status,status prefix,948,prefix='submitted'
69,followup_requests,status,status prefix,103,prefix='deleted'
70,followup_requests,status,status prefix,40,prefix='complete'
71,followup_requests,status,status prefix,66,prefix='rejected'
72,followup_requests,status,status prefix,15,prefix='pending'
73,followup_requests,status,status prefix,26,prefix=<unclassified>
74,photometry,filter,categorical label,2740,value='atlaso'
75,photometry,filter,categorical label,1029,value='bessellr'
76,photometry,filter,categorical label,768,value='sdssr'
77,photometry,filter,categorical label,509,value='atlasc'
78,photometry,filter,categorical label,496,value='sdssi'
79,photometry,filter,categorical label,493,value='sdssg'
80,photometry,filter,categorical label,353,value='bessellv'
81,photometry,filter,categorical label,201,value='bessellb'
82,photometry,filter,categorical label,186,value='gaia::grp'
83,photometry,filter,categorical label,170,value='besselli'
84,photometry,filter,categorical label,154,value='sdssz'
85,photometry,filter,categorical label,143,value='gaia::gbp'
86,photometry,filter,categorical label,98,value='ztfr'
87,photometry,filter,categorical label,95,value='swiftxrt'
88,photometry,filter,categorical label,93,value='ps1::open'
89,photometry,filter,categorical label,92,value='ztfg'
90,photometry,filter,categorical label,49,value='uvot::white'
91,photometry,filter,categorical label,41,value='uvot::u'
92,photometry,filter,categorical label,34,value='2massj'
93,photometry,filter,categorical label,25,value='uvot::v'
94,photometry,filter,categorical label,24,value='uvot::b'
95,photometry,filter,categorical label,23,value='standard::r'
96,photometry,filter,categorical label,21,value='gotol'
97,photometry,filter,categorical label,19,value='uvot::uvw1'
98,photometry,filter,categorical label,19,value='ztfi'
99,photometry,filter,categorical label,15,value='uvot::uvm2'
100,photometry,filter,categorical label,13,value='uvot::uvw2'
101,photometry,filter,categorical label,13,value='2massh'
102,photometry,filter,categorical label,10,value='gaia::g'
103,photometry,filter,categorical label,8,value='sdssu'
104,photometry,filter,categorical label,7,value='ps1::r'
105,photometry,filter,categorical label,7,value='ps1::w'
106,photometry,filter,categorical label,6,value='standard::v'
107,photometry,filter,categorical label,5,value='2massks'
108,photometry,filter,categorical label,3,value='standard::b'
109,photometry,filter,categorical label,3,value='standard::i'
110,photometry,filter,categorical label,1,value='ps1::y'
111,photometry,filter,categorical label,1,value='standard::u'
112,photometry,filter,categorical label,1,value='gaia::grvs'
113,photometry,instrument_name,categorical label,3249,value='ATLAS'
114,photometry,instrument_name,categorical label,1049,value='GCN'
115,photometry,instrument_name,categorical label,367,value='NUTTelA-TAO '
116,photometry,instrument_name,categorical label,358,value='KNC'
117,photometry,instrument_name,categorical label,346,value='KNC-FR-CAM'
118,photometry,instrument_name,categorical label,318,value='VT'
119,photometry,instrument_name,categorical label,274,value='FRAM-CTA-N'
120,photometry,instrument_name,categorical label,244,value='TAROT/TCH'
121,photometry,instrument_name,categorical label,214,value='UVOTXRT'
122,photometry,instrument_name,categorical label,211,value='ZTF'
123,photometry,instrument_name,categorical label,137,value='SKYNET/Prompt'
124,photometry,instrument_name,categorical label,115,value='TAROT/TCA'
125,photometry,instrument_name,categorical label,114,value='FRAM-Auger'
126,photometry,instrument_name,categorical label,111,value='Mephisto'
127,photometry,instrument_name,categorical label,95,value='KAO'
128,photometry,instrument_name,categorical label,90,value='REM'
129,photometry,instrument_name,categorical label,86,value='COLIBRI-VIS'
130,photometry,instrument_name,categorical label,76,value='TRT-SRO'
131,photometry,instrument_name,categorical label,55,value='Les-Makes/T60'
132,photometry,instrument_name,categorical label,44,value='KAIT'
133,photometry,instrument_name,categorical label,39,value='UBAI/AZT-22'
134,photometry,instrument_name,categorical label,33,value='TRT'
135,photometry,instrument_name,categorical label,27,value='TRT-SBO'
136,photometry,instrument_name,categorical label,26,value='TAROT/TRE'
137,photometry,instrument_name,categorical label,23,value='LCO-SAAO'
138,photometry,instrument_name,categorical label,22,value='Euler'
139,photometry,instrument_name,categorical label,21,value='AbAO-T150'
140,photometry,instrument_name,categorical label,17,value='TTT'
141,photometry,instrument_name,categorical label,17,value='OPD/60cm'
142,photometry,instrument_name,categorical label,16,value='3KK'
143,photometry,instrument_name,categorical label,16,value='AbAO-T70'
144,photometry,instrument_name,categorical label,14,value='TNOT'
145,photometry,instrument_name,categorical label,13,value='UBAI/NT-60'
146,photometry,instrument_name,categorical label,12,value='HAO'
147,photometry,instrument_name,categorical label,11,value='Lisnyky/AZT-8'
148,photometry,instrument_name,categorical label,10,value='SOAR/Spartan'
149,photometry,instrument_name,categorical label,10,value='OPD/1.6m'
150,photometry,instrument_name,categorical label,9,value='PS1'
151,photometry,instrument_name,categorical label,9,value='PicduMidi/T1M'
152,photometry,instrument_name,categorical label,8,value='TRT-CTO'
153,photometry,instrument_name,categorical label,7,value='CFHT/MEGACAM'
154,photometry,instrument_name,categorical label,6,value='OHP/MISTRAL'
155,photometry,instrument_name,categorical label,6,value='Artemis'
156,photometry,instrument_name,categorical label,5,value='Wendelstein 3KK'
157,photometry,instrument_name,categorical label,5,value='GTC/OSIRIS'
158,photometry,instrument_name,categorical label,4,value='ASTEP'
159,photometry,instrument_name,categorical label,4,value='C2PU-O'
160,photometry,instrument_name,categorical label,3,value='NAO-1.5m'
161,photometry,instrument_name,categorical label,3,value='LCO_0m4-39'
162,photometry,instrument_name,categorical label,3,value='TRAPPIST-South'
163,photometry,instrument_name,categorical label,2,value='PlaneWave F7.15'
164,photometry,instrument_name,categorical label,2,value='PicduMidi/T50'
165,photometry,instrument_name,categorical label,2,value='Xinglong-2.16m'
166,photometry,instrument_name,categorical label,2,value='GoT1'
167,photometry,instrument_name,categorical label,2,value='VIRT'
168,photometry,instrument_name,categorical label,2,value='ROAD'
169,photometry,instrument_name,categorical label,1,value='NAO-2m'
170,photometry,instrument_name,categorical label,1,value='ShAO-T60'
171,photometry,instrument_name,categorical label,1,value='YAHPT Imager'
172,photometry,instrument_name,categorical label,1,value='MOSS'
173,photometry,magsys,categorical label,7968,value='ab'
174,photometry,origin,categorical label,2786,value='fp'
175,photometry,origin,categorical label,2135,value='None'
176,photometry,origin,categorical label,995,value='stdview'
177,photometry,origin,categorical label,975,value='GCN'
178,photometry,origin,categorical label,359,value='zmaksut'
179,photometry,origin,categorical label,289,value='stdweb'
180,photometry,origin,categorical label,135,value='weikang'
181,photometry,origin,categorical label,40,value='UVOT'
182,photometry,origin,categorical label,36,value='Alain'
183,photometry,origin,categorical label,35,value='Baader'
184,photometry,origin,categorical label,22,value='GCN '
185,photometry,origin,categorical label,17,value='XRT'
186,photometry,origin,categorical label,9,value='GRANDMA-GCN'
187,photometry,origin,categorical label,8,value='STDPipe analysis'
188,photometry,origin,categorical label,8,value='Broens-init'
189,photometry,origin,categorical label,8,value='zmaksut '
190,photometry,origin,categorical label,6,value='GCN 41162'
191,photometry,origin,categorical label,6,value='FTW'
192,photometry,origin,categorical label,6,value='Swift/UVOT'
193,photometry,origin,categorical label,6,value='Baader Planetarium'
194,photometry,origin,categorical label,6,value='stdpipe'
195,photometry,origin,categorical label,5,value='https://www.astronomerstelegram.org/?read=17646'
196,photometry,origin,categorical label,5,value='FINK science portal'
197,photometry,origin,categorical label,4,value='https://fink-portal.org/ZTF26aaedxli'
198,photometry,origin,categorical label,3,value='ZTF'
199,photometry,origin,categorical label,3,value='STDweb'
200,photometry,origin,categorical label,3,value='STDPipe'
201,photometry,origin,categorical label,2,value='https://www.astronomerstelegram.org/?read=17647'
202,photometry,origin,categorical label,2,"value='304.742900, -40.805100'"
203,photometry,origin,categorical label,2,value='MagicARPP'
204,photometry,origin,categorical label,2,value='GRANDMA'
205,photometry,origin,categorical label,2,value='GCN Circular 39737'
206,photometry,origin,categorical label,2,value='stdview:100'
207,photometry,origin,categorical label,2,value='STDpipe'
208,photometry,origin,categorical label,2,value='GCN 37773'
209,photometry,origin,categorical label,2,value='SVOM VT observation'
210,photometry,origin,categorical label,2,"value=""'QHY268mm + Baader filter g'''"""
211,photometry,origin,categorical label,1,value='GCN: 39827'
212,photometry,origin,categorical label,1,value='stdpipe-task1438-AB-FelipeSOARon10'
213,photometry,origin,categorical label,1,"value=""'QHY268MM + Baader filter r'''"""
214,photometry,origin,categorical label,1,"value=""'QHY268MM + Baader filter g'''"""
215,photometry,origin,categorical label,1,value='AbAO'
216,photometry,origin,categorical label,1,value='QHY268MM + Baader Filter + PRISM V11 + UCAC4'
217,photometry,origin,categorical label,1,value='https://gcn.nasa.gov/circulars/34881?query=GOTO23baj'
218,photometry,origin,categorical label,1,value='GCN 44551'
219,photometry,origin,categorical label,1,value='myanalyis'
220,photometry,origin,categorical label,1,value='OPD/60cm'
221,photometry,origin,categorical label,1,value='GCN 41184'
222,photometry,origin,categorical label,1,value='stdview 5968'
223,photometry,origin,categorical label,1,value='MXT'
224,photometry,origin,categorical label,1,value='CrAO/ZTSh'
225,photometry,origin,categorical label,1,"value='GCN 39831, COLIBRÍ observation'"
226,photometry,origin,categorical label,1,"value='GCN 39854, TNOT'"
227,photometry,origin,categorical label,1,value='GCN 39836'
228,photometry,origin,categorical label,1,value='TNS'
229,photometry,origin,categorical label,1,value='stdview 5904'
230,photometry,origin,categorical label,1,value='stdpipe-task143-AB-FelipeSOARon10'
231,photometry,origin,categorical label,1,value='VIRT'
232,photometry,origin,categorical label,1,value='http://stdweb.favor2.info/tasks/2995'
233,photometry,origin,categorical label,1,value='http://grandma-stdpipe.ijclab.in2p3.fr/tasks/4110'
234,photometry,origin,categorical label,1,value='http://grandma-stdpipe.ijclab.in2p3.fr/tasks/4104'
235,photometry,origin,categorical label,1,value='http://grandma-stdpipe.ijclab.in2p3.fr/tasks/4105'
236,photometry,origin,categorical label,1,value='http://grandma-stdpipe.ijclab.in2p3.fr/tasks/4108'
237,photometry,origin,categorical label,1,value='http://grandma-stdpipe.ijclab.in2p3.fr/tasks/4103'
238,photometry,origin,categorical label,1,value='TAROT-TCH'
239,photometry,origin,categorical label,1,value='GCN 39837'
240,photometry,origin,categorical label,1,value='GCN 39837 Liverpool Telescope'
241,photometry,origin,categorical label,1,value='STDweb Task 2511'
242,photometry,origin,categorical label,1,value='STDweb Task 2507'
243,photometry,origin,categorical label,1,value='STDweb Task 2508'
244,photometry,origin,categorical label,1,value='STDweb Task 2512'
245,photometry,origin,categorical label,1,value='stdview:1535'
246,photometry,origin,categorical label,1,value='stdview:1536'
247,photometry,origin,categorical label,1,value='stdview:1537'
248,photometry,origin,categorical label,1,value='stdview:1538'
249,photometry,altdata.GCN,leading or trailing whitespace,2,values not shown
250,photometry,altdata.note,leading or trailing whitespace,12,values not shown
251,photometry,instrument_name,leading or trailing whitespace,367,values not shown
252,photometry,origin,leading or trailing whitespace,30,values not shown
253,photometry,dec_unc,no content in any row,7968,column is entirely empty
254,photometry,ra_unc,no content in any row,7968,column is entirely empty
255,photometry,<whole row>,rows identical on every column except id,0,0 means no such duplicate exists
256,photometry,limiting_mag,sentinel-like numeric value,10,values=[-1.0]
257,sources,origin,categorical label,199,value='Einstein Probe'
258,sources,origin,categorical label,131,value='Swift'
259,sources,origin,categorical label,121,value='SVOM'
260,sources,redshift_origin,categorical label,3,value='NOT/ALFOSC'
261,sources,redshift_origin,categorical label,2,value='GCN 39585'
262,sources,redshift_origin,categorical label,2,value='GCN 37228 and 37013'
263,sources,redshift_origin,categorical label,2,value='Colibri (photo_z)'
264,sources,redshift_origin,categorical label,2,value='SVOM/COLIBRÍ (FM-GFT)'
265,sources,redshift_origin,categorical label,2,value='GCN 39278'
266,sources,redshift_origin,categorical label,2,value='(UL)'
267,sources,redshift_origin,categorical label,2,value='GTC'
268,sources,redshift_origin,categorical label,2,value='NOT'
269,sources,redshift_origin,categorical label,2,value='GCN 43490'
270,sources,redshift_origin,categorical label,2,value='GCN 42031'
271,sources,redshift_origin,categorical label,2,value='GCn 41363'
272,sources,redshift_origin,categorical label,2,value='GCN 41348'
273,sources,redshift_origin,categorical label,2,value='VLT/X-shooter GCN 41022'

In [10]:
HISTORY_PARENT = {"redshift_history": "redshift", "summary_history": "summary"}
HISTORY_VALUE = {"redshift_history": "value", "summary_history": "summary"}
UTC_OFFSET_RE = re.compile(r"([+-]\d{2}:?\d{2}|Z)$")

unique_sources = TABLES["sources"].drop_duplicates("id")  # one row per source before parsing
history_rows = []

for field, parent in HISTORY_PARENT.items():
    carrying = unique_sources[unique_sources[field].notna()]
    parsed = [(row["id"], index, entry) for _, row in carrying.iterrows()
              for index, entry in enumerate(json.loads(row[field]))]
    frame = pd.DataFrame([{"id": sid, "entry_index": index, **entry}
                          for sid, index, entry in parsed])
    value_key, stamps = HISTORY_VALUE[field], frame["set_at_utc"]
    per_source = frame["id"].value_counts()
    offset = stamps.dropna().map(lambda v: bool(UTC_OFFSET_RE.search(v)))
    unordered = frame.groupby("id")["set_at_utc"].apply(lambda s: list(s) != sorted(s))
    current = unique_sources.set_index("id")[parent]
    current = current[has_content(current)]
    latest = frame.sort_values("set_at_utc").groupby("id")[value_key].last()
    if field == "redshift_history":  # history stores the value as text, the parent as a float
        latest, current = latest.map(lambda v: None if v is None else float(v)), current.astype(float)
    shared = latest.index.intersection(current.index)
    matches = int(sum(latest[sid] == current[sid] for sid in shared))

    measured = [("sources carrying the field", len(carrying)), ("entries parsed", len(parsed)),
                ("entries per source", f"min={per_source.min()} / median={per_source.median():.0f}"
                 f" / max={per_source.max()} / most={per_source.idxmax()!r}")]
    for key in [c for c in frame.columns if c not in ("id", "entry_index")]:
        types = pd.Series([type(e[key]).__name__ for _, _, e in parsed if key in e]).value_counts()
        measured.append((f"key '{key}'", f"present in {sum(key in e for _, _, e in parsed)} entries"
                         " | types " + " ".join(f"{t}={n}" for t, n in types.items())))
    measured += [("entries with a null value (deletion events)", int(frame[value_key].isna().sum())),
                 ("set_at_utc range", f"{stamps.min()} .. {stamps.max()}"),
                 ("set_at_utc nulls", int(stamps.isna().sum())),
                 ("set_at_utc explicit UTC offset",
                  f"present={int(offset.sum())} / absent={int((~offset).sum())}"),
                 ("sources whose entries are not in chronological order",
                  f"{int(unordered.sum())} of {len(carrying)}"),
                 ("distinct set_by_user_id", frame["set_by_user_id"].nunique())]
    if field == "summary_history":
        measured += [("is_bot", " | ".join(f"{k}={v}" for k, v in frame["is_bot"].value_counts().items())),
                     ("analysis_id non-null", int(frame["analysis_id"].notna().sum()))]
    measured += [(f"history but no current '{parent}'", len(latest.index.difference(current.index))),
                 (f"latest entry by date vs current '{parent}'",
                  f"compared={len(shared)} / matches={matches} / mismatches={len(shared) - matches}")]
    history_rows += [{"field": field, "property": prop, "value": value} for prop, value in measured]

field_history = pd.DataFrame(history_rows)
field_history

               field                                              property                                                           value
0   redshift_history                            sources carrying the field                                                              60
1   redshift_history                                        entries parsed                                                              83
2   redshift_history                                    entries per source                       min=1 / median=1 / max=4 / most='2025aji'
3   redshift_history                                           key 'value'                 present in 83 entries | types str=80 NoneType=3
4   redshift_history                                      key 'set_at_utc'                            present in 83 entries | types str=83
5   redshift_history                                     key 'uncertainty'                present in 83 entries | types NoneType=63 str=20
6   redshift_history                                  key 'set_by_user_id'                            present in 83 entries | types int=83
7   redshift_history                                          key 'origin'                            present in 33 entries | types str=33
8   redshift_history           entries with a null value (deletion events)                                                               3
9   redshift_history                                      set_at_utc range  2023-10-19T21:18:35.567018 .. 2026-07-15T12:16:30.504968+00:00
10  redshift_history                                      set_at_utc nulls                                                               0
11  redshift_history                        set_at_utc explicit UTC offset                                          present=25 / absent=58
12  redshift_history  sources whose entries are not in chronological order                                                         0 of 60
13  redshift_history                               distinct set_by_user_id                                                              27
14  redshift_history                     history but no current 'redshift'                                                               2
15  redshift_history            latest entry by date vs current 'redshift'                         compared=58 / matches=58 / mismatches=0
16   summary_history                            sources carrying the field                                                             256
17   summary_history                                        entries parsed                                                            1274
18   summary_history                                    entries per source            min=1 / median=2 / max=48 / most='GCN-260604_202037'
19   summary_history                                          key 'is_bot'                       present in 1274 entries | types bool=1274
20   summary_history                                         key 'summary'            present in 1274 entries | types str=1249 NoneType=25
21   summary_history                                      key 'set_at_utc'                        present in 1274 entries | types str=1274
22   summary_history                                     key 'analysis_id'                   present in 1274 entries | types NoneType=1274
23   summary_history                                  key 'set_by_user_id'                        present in 1274 entries | types int=1274
24   summary_history           entries with a null value (deletion events)                                                              25
25   summary_history                                      set_at_utc range  2023-05-21T19:41:45.150176 .. 2026-07-19T09:50:32.481614+00:00
26   summary_history                                      set_at_utc nulls                                                               0
27   summary_history                        set_at_utc explicit UTC offset                                        present=552 / absent=722
28   summary_history  sources whose entries are not in chronological order                                                      141 of 256
29   summary_history                               distinct set_by_user_id                                                              48
30   summary_history                                                is_bot                                                      False=1274
31   summary_history                                  analysis_id non-null                                                               0
32   summary_history                      history but no current 'summary'                                                               6
33   summary_history             latest entry by date vs current 'summary'                       compared=250 / matches=250 / mismatches=0

## Decisions taken from these measurements

These decisions were taken by reading the tables above. Each one names
the finding that motivates it and the number of rows or columns it
affects. They are applied by `scripts/skyportal/02_normalise.py`, and
their effect is measured in notebook B.

| # | Decision | Motivating finding | Scope |
|---|---|---|---|
| 1 | `sources` carries one row per source: 982 -> 800. Profile membership moves into a list column. | 182 sources are returned by more than one profile query, occupying 364 rows. | 182 sources |
| 2 | When multi-profile copies of a source differ, keep the copy carrying host enrichment. Differences confined to JSON key ordering are not differences. The host family is the dotted `host.*` columns together with `host_offset`, which is derived from `host.ra` and `host.dec` and co-varies with them. | After canonicalising JSON key order, 1 of the 182 multi-profile sources genuinely differs, in 10 host-family columns. The other 181 are identical copies. | 1 source of 182 |
| 3 | `followup_requests` keeps the row where `source_dir == obj_id`: 2,359 -> 2,339. | 20 ids appear twice. `obj_id` is identical in both copies; only the capture directory differs. The 20 mismatching rows are exactly the discarded copies. | 20 rows |
| 4 | Strip whitespace from identifiers before any join. | `'AT2023toh\t'` in sources; 17 `obj_id` values in followup_requests. | 18 rows |
| 5 | Strip leading and trailing whitespace from all text columns. | `comments.text` 551, `photometry.instrument_name` 367, `allocation.pi` 172, `sources.summary` 58, `photometry.origin` 30, and others. `'NUTTelA-TAO '` counts as an instrument distinct from `'NUTTelA-TAO'`. | ~1,200 rows |
| 6 | Drop columns with no content in any row. | 25 in sources, 20 in followup_requests, 10 in spectra, 2 in photometry, 1 in comments. Empty strings and `[]` count as no content. | 58 columns |
| 7 | Drop `comments.resourceType`. | Constant `'sources'` across all 2,950 rows; it describes the endpoint, not the data. `photometry.magsys` is also constant but is retained: it is a property of the measurements. | 1 column |
| 8 | Retain sparse columns and document their coverage. | `redshift` is present on 50 sources only, but is a real value where present. Sparse is not empty. | ~100 columns |
| 9 | Add `status_normalised` with 8 values; retain `status` unchanged. | 187 distinct status strings resolve to 7 lifecycle prefixes plus 26 rows describing a processing result rather than a request state. `submitted for` alone produces 129 distinct strings because a timestamp is embedded in the label. | 2,359 rows |
| 10 | Type all datetime columns as datetime with UTC declared explicitly. | Every ISO column is timezone-naive on disk. | all tables |
| 11 | Set `limiting_mag = -1.0` to null. | 10 rows carry a sentinel, not a magnitude. | 10 rows |
| 12 | Set out-of-range `mjd` to null and flag it in a companion column. Rows are retained. | 3 rows of `GRB240911A` carry `mjd = 2024.0`, a calendar year in a day counter. 2 rows of `ZTF23aaptsuy` carry `mjd = 61582`, which falls in June 2027, 1,452 days after their own `created_at`. The remaining 14 rows whose `mjd` exceeds `created_at` differ by under a day and are normal UTC offset. | 5 rows of 7,968 |
| 13 | Flag coordinates equal to exactly 0.0 with a boolean column. Values are not nulled. | 3 in `sources.ra`, 1 in `sources.dec`, 17 in `followup_requests`. 0.0 is a valid coordinate and also what a missing value looks like; the corpus records the ambiguity rather than resolving it. | 21 rows |
| 14 | Leave `origin` and `redshift_origin` as they are, whitespace aside. | 75 distinct values in `photometry.origin`: URLs, circular numbers, coordinates, free text. These are hand-written provenance notes. Any equivalence rule would be right in some cases and wrong in others, and a wrong value is worse than an absent one. | no change |
| 15 | `created_at` is the causal truncation anchor in all five tables. | It is populated on 100% of rows in every table. `mjd`, `t0`, `observed_at` and `tns_info.discoverydate` date the sky event rather than the moment it became known, and are sparse. | all tables |
| 16 | Field history is expanded into a sixth table, `source_field_history`, one row per change. Source: `redshift_history` and `summary_history` in `sources`. Entries with a null value are kept as deletion events. `set_at_utc` is normalised to explicit UTC. `entry_index` records the original array position. `is_bot` is retained though constant; `analysis_id` is dropped as empty. The serialised columns remain in `sources`. | `redshift_history` holds 83 dated entries across 60 sources; `summary_history` holds 1,274 across 256. Each entry carries its value, the instant it was set and the user who set it. 141 of 256 summary histories are not stored in chronological order, so array position cannot be read as recency. | 1,357 rows from 266 sources |

Checks that ran and found nothing: values whose python type varies
between rows, the Unicode replacement character U+FFFD, negative
uncertainties, and rows identical on every column except their id.